Mods/RT Fusebox_SK/Defs/ResearchProjectDefs/ResearchProjects_RTFusebox.xml
Mods/RT Fusebox_SK/Defs/ThingDefs/Building_RTFusebox.xml

Если есть исследования предохранителей, надо бы их связать с самими постройками. А заодно и требования к этим исследованиям добавить, чтобы они не появлялись со старта игры.

fixing fusebox prerequisites

---

Mods/Core_SK/Defs/HelpDefs/HelpDefs_Gizmos.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Parts_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Got to at least mid-game before I realized I'd never created "spare parts" on the assembling workbench. Created one set because I had the materials, only to find that recipe was the key to the component shortage I'd had the entire playthrough.
Was tempted to remove "hand tools" from the building description because I still haven't seen them yet, but didn't for now. :>

"Spare Parts" to "Components"

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

* Fixed descriptions of the following tables to clarify that they **don't** need power:
* Oven
* Tailor's Loom
* Ammo Crafting Table
* Fixed descriptions of the following items to clarify that they **do** need power:
* Hydroponic Box
* Added PlaceWorker_ShowFacilitiesConnections (show electrical connections) to the following electric benches:
* Soylent Machine
* Coffee Machine
* Brewery
* Recycle Textile Bench
* Electric Crematorium
* Robotic Assembler
* Quantum Fabricator
* Hydroponic Basin
* Advanced Hydroponic Basin
* Hydroponic Pot
* Hydroponic Box
* Removed PlaceWorker_ShowFacilitiesConnections (show electrical connections) from the following non-electric benches:
* Oven
* Hand Sawmill
* Hand Smelting Furnace
* Tailor's Loom
* Hand Assembling Bench
* Fueled Smithy
* Hand Machining …

Dev fix typos

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_SK.xml

Pallet research prerequisites - Storage I (fix)
Skip research prerequisites - Storage II (fix)
__
у палета емкость 500 у скипа 800. по [дереву технологий](https://github.com/skyarkhangel/Hardcore-SK/blob/master/%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE/ResearchTreeSK.png) они оба открываются через Storage I. смысл в палете когда?
имхо я бы skip в Storage III запихнул, что бы продлить жизнь палетам по дольше.

Pallet & skip fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml

- should stop considering pathcost of multiple tiles as single
___
не думаю что это применимо к мешкам - на них можно физически залезть.

Moat & WallWire fix

---

Mods/Core/Defs/ThingDefs_Buildings/Buildings_Natural.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml

Compact machinery increased since 2 to 8. With the number of components that go to build, spend a lot of time to get 2 things - ridiculously.
Banana, apple, orange, peach, and other now not an AWFUL meals. Here it is better to make the character's trait "does not like fruit," or something like that.

Compact machinery, meals

---

Mods/Clutter_SK/Defs/ThingDefs/Furniture.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml
Mods/Miscellaneous_Objects/Defs/ThingDefs/Miscellaneous_Buildings_NanoPrinter.xml
Mods/Miscellaneous_Objects/Defs/ThingDefs/Miscellaneous_Buildings_NanoStorage.xml

- all storage containers now accept nothing by default
- "EquipmentRack" fix (unable to set storage settings)
___
@skyarkhangel 
1) "ClutterFreezer" и "RefrigeratedTrayRack" практически одно и тоже...
2) "Barrel" когда пустой имеет цвет материала, а когда полный то меняет цвет на стандартный.
3) Есть такая занимательная строчка [BillStoreMode_NearestStockpileAnyPriority](https://github.com/skyarkhangel/Hardcore-SK/blob/4a64805096f3138251874faaf960758ca28b8932/Mods/Core/Languages/English/Keyed/Dialogs_Various.xml#L133) однако она в биллах не появляется, а оче хотелось бы...
4) #278

Storages settings by default

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Turrets.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_WeaponComponents.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Heavy.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Launchers.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Pistols.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Rifle.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_RifleAdvanced.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_SMGs.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Shotguns.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Snipers.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Security.xml
Mods/Core_SK/Defs/ThingDefs_CR/Ammo_Cannons.xml
Mods/Core_SK/Defs/ThingDefs_CR/Projectiles_Cannons.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Crate.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Heavy.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Pistols.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Rifles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRifles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRiflesAdvanced.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Machineguns.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Sentry.xml

- various description fixes
- "Sentry naval cannon" now uses 35mm instead 30mm
- "GAU-8" now uses 30mm instead 35mm
- "Barret M82A1" now uses .50BMG instead 14.5mm
- "FN SCAR-H" now uses 7.62x51mm NATO instead 7.62x39mm Soviet
- "Tavor TAR-21" now uses 5.56x45mm NATO instead 5.45x39mm Russian
- added caliber info for most guns
- #306 & #305 
___
X_x

Weapon descriptions fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml

1) Fueled smithy now only can be fueled by coal or peat -- other fuels
could not give enough heat anyway
2) Whenever charcoal was accepted, coal is now accepted too
3) More uniform fueling requirements in description.

Fueled buildings cleanup

---

Mods/Core_SK/Defs/QuarryResourceDefs/QuarryResources_QRY.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Furniture.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

An attempt to fix #364 
My take: 
1) Glowstone lamp now requires an appropriate tech researched.
2) Requires ~3x more resources
3) Doesn't deplete
And nerfed a bit glowstones from quarry

Glowstone fix attempt#1: no depletion

---

Mods/Core_SK/Defs/ThingDefs_CR/Ammo.xml

Fixed 9x39 ammo firing wrong projectiles, 4 files simultaneous change: Ammo.xml, Projectiles.xml, Weapons_SniperRifles.xml, Projectiles_SK.xml.
Ammo.xml changes:
"Ammo_9x39Soviet_FMJ" linked projectile changed to "Bullet_9x39Soviet_FMJ" (was: "Bullet_9x39Soviet")
"Ammo_9x39Soviet_SH" linked projectile changed to "Bullet_9x39Soviet_SH" (was: "Bullet_545x39mmR_HP")

Fixed 9x39 ammo firing wrong projectiles

---

Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Player.xml

Adds PawnKindDefs called for by Core_SK.DLL::SK.Events.IncidentWorker_WandererJoin
this.pawnKindDef = PawnKindDef.Named("NorbalHeroPlayer");
this.pawnKindDef = PawnKindDef.Named("OrassanHunterPlayer");
this.pawnKindDef = PawnKindDef.Named("AsariHunterPlayer");

fixes missing PawnKindDefs

---

Mods/Core_SK/Defs/HediffDefs/HediffDefs_Enlighten.xml

Sometimes when your Colonists have their movement too low, entering darkness will make them become incapacited. It can be hilarious the first time but it gets old fast. This patch changes the bonus to a factor, so the situation will not happen.

Make Enlighten movement bonuses/penalties a factor

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorWood.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_PrimitiveFloors.xml

Changed beauty from 3 to 2 and increased work by 25% (except for the fancy tiki floor which uses gold), and amount of hay needed by +1. Also cleaned up the code inheritance (it was located in the wood floor xml for some reason but isn't actually used there, so it was moved over to the prim floor xml instead) and in-game descriptions.

Balance changes to prim floors

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml

The passive cooler tech wasn't giving you anything because the building was missing the prereq attribute. I also clarified the purpose of this building better in the description.

Fix passive cooler

---

Mods/Core/Defs/ThingDefs_Misc/Various_Stone.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Extracts.xml

The "cut stone blocks" and cut specific stone blocks (eg "cut marble blocks") were different. They now both yield the sand and rubble byproducts.
They also had mismatched speed and skill gain. The generic one was faster and gave more skill, whereas the specific ones used vanilla stats. I reset the generic to use vanilla stats as well. Cleaned up the labels too.

Fix stone cutting recipes

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Production.xml

Producing kindling is a crude, non-precision task that shouldn't take so long to do, especially considering how much of the stuff a base burns through now. I propose reducing the work, but also reducing the skill gain as well.
Also the description was displaying the wrong number for yield.

Proposed adjustment to kindling production

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture.xml

This removes the quality display on some of the furniture that was displaying it (the same attribute is used to show bed ownership, so I had to move that to the bedbase instead).
It also allows only stools to be placed in front of work benches.

Furniture fixes

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Security.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Start.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml

Two issues fixed:
A.) the Cheval de frise could not be built because it lacked a category
B.) you could build parapets before sandbags.
I changed it so it's now Cheval de frise (craftsmanship) -> sandbags (security 1) -> parapets (security 2) -> embrasures (security 3), and I felt it also made sense to gate security 2 behind construction 1.
Some typo fixes too.

Security progression refinements

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Walls.xml

I can't see any logical reason on why simple fences cost components and other type of walls do not. They're mostly just aesthetic buildings anyway. They're also unlocked at a cost-100, first tier research, suggesting they're intended for very early game use, but components are a premium in the early game so that doesn't align very well.
Increased the workload though, because digging post holes is rather labor intensive.

Proposed balance change to fences

---

Mods/Core/Defs/RecipeDefs/Recipes_Food.xml

Kibble was massively unbalanced, increasing the nutrition by a whopping 25x (0.05 x 2 in, 0.05 x 50 out).
The proposed formula would be a simple 2x yield instead.
It should probably also take a bit longer. This is a lot of food being prepared.

Fix kibble

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs.xml

It can't be worn over other pants, as the description claims. Was obviously causing some player confusion.

Holstered chaps description fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Pemmican is a starting tech for tribal start, but you're unable to make it until you get post-tribal tech (fueled stoves). The grill should be able to make this, I think.

Pemmican fix

---

Mods/Core/Defs/RecipeDefs/Recipes_Food.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Alcohol.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Bakery.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Canned.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Drinks.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Ingridients.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Livestock.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Medicals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Mushrooms.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorBrick.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorCarpet.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorMetallic.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorStone.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorWood.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_Natural.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_NaturalNew.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_PrimitiveFloors.xml

Meals are ready. Will do the rest later.
This update now also includes rebalance to the floors. The stone floors' description stated a beauty of 3, but it was really set at 2. I noticed that vanilla also uses beauty 2 for stone, so I just updated the descriptions to match.
I then rebalanced the other floors to better align with this:
primitive floors: 1 (from 2)
all "regular" floors (stone, wood, bricks): 2 (from 3)
carpets: 3 (from 4)
floors involving components and silver: 3 (unchanged)
gold: 4+ (unchanged)
This better aligns with the vanilla balance and shouldn't make rooms so easily beautiful now as it was before.

Bill label consistency sweep (meals)

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Giants.xml

The megabadger is in line with the megasloth, with slightly better blunt/sharp ratings and somewhat worse others. relative to rhino hide, the wooly rhino hide is slightly tougher, uglier/less valuable, and biased toward cold rather than heat insulation.

Fill out leather stat factors for the megabadger and wooly rhino.

---

Mods/CombatRealism/Defs/RecipeDefs_Ammo/Recipes_AmmoHighCaliber.xml
Mods/Core_SK/Defs/ThingDefs_CR/Ammo.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRifles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRiflesAdvanced.xml

Fix some labels for the 9x39mm ammo, and add missing recoil definitions for the VSS Vintorez and SRS99.

Touch up the burst-fire sniper rifles

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Temperate.xml

They're nearly twice as large as elk. But irl, caribou are smaller than elk.

Fix caribou size

---

Mods/Core_SK/Defs/ThingDefs_CaveFlora/Items_Resource_Organic.xml

85% medical potency was way too high compared to other, higher effort options. Even herbal medical kits aren't that high. 50% would put it in line with aloe (which is 45%).

Gleamcap balance

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

They probably shouldn't be able to store very bulky resources like stone blocks, lumber and ingots. This is what the Skips are intended to be used for.

Balance changes for barrels, baskets and chests

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Bakery.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Arid.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Farm.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Horse.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Temperate.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Tropical.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Ingridients.xml

This patch is the result of a day of discussion in the discord channel and documentation on the spreadsheet found here: https://docs.google.com/spreadsheets/d/12S8CbrwwbircwbaUqkPMy4qptjDuqqxn0ldeNJTZii8/
As well as a handful of minor fixes and tweaks that were made along the way, it mostly addresses how overpowered the milk and cheese industry was. This was due to HCSK creatures producing about 5x more milk compared to vanilla, combined with how good cheese was all around.
Animals now produce about 50% more milk than vanilla instead, and cheese production takes more effort now.

Cheese empire rebalance

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Martens.xml

I had misunderstood how baseHealthScale worked exactly when they were given a health buff recently.

Marten fix (again)

---

Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated_Vegetables.xml

Its wind exposure was a good 8x higher than everything else for some reason.

Fix lettuce wibble wobble

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

These buildings' impassability got reset to default due to their change in parent def.

Fix passability

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Components.xml
Mods/Core_SK/Defs/ThingDefs_FishIndustry/Races_Animal_Fish.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Tree_SK.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Wood.xml

Berries didn't have a bulk value set, and were much too high, so pawns couldn't grab enough. It was set to 0.3 because they have about 1/3rd the nutrition as other foods which are a bulk of 1.
This was through a new mini-abstract called SmallFruitFoodRawBase.

Fix being unable to tame with berries

---

Mods/Core_SK/Languages/English/Keyed/SN.xml

This may not belong here, but in an upstream location instead.

Grammar Fix in  SN.xml

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Synthetic.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Mechanoid.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml
Mods/Dubs Bad Hygiene/Defs/ThingDefs_Buildings/Buildings_Hygiene.xml
Mods/RedistHeat/Defs/ThingDefs/Buildings_TempController.xml

update:
-reverted cropsbase change
-nerfed mechanoid crawlers speed/cd/body (serpentine body too low, unhitable).
-removed flickable from both non power grid stoves.
-fixed tofu recipe.
-renamed RH heater so it overrides the vanilla one.
-added chairsearchradius to cover all ingestible defs, removing the need for table diner patch.

Fixes and stuff

---

Mods/Core/Languages/Russian-SK/DefInjected/WorkTypeDef/WorkTypes.xml

Just to make sure that they don't cross each other.
Для ская: В вокр табе названия друг на друга залезают, я их укоротил немного.

Russian work type allignment for WorkTab

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Furniture.xml

Dining room furniture I's tech level was at medieval. Changed DRF II from neolithic to medieval, as it's more logical that way.

Dining room furniture II techlevel update

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

Паллеты не позволяют хранить одежду, но она почему-то отмечена по умолчанию.
Из-за этого пропадали фильтры гнилое/свежее.

Remove apparrel default from pallet and skip

---

Mods/Core_SK/Defs/ThingDefs/Various_Stone.xml

remove sand and rubble output on specific stone type recipes to allow for do until X to work.

update specific stone recipes

---

Mods/Core_SK/Defs/ThingDefs_BodyParts/Items_BodyParts.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Medical.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Mushrooms.xml
Mods/Core_SK/Defs/ThoughtDefs/Thoughts_Memory_SK.xml

Moved Life support from Medicine category to BodyParts.
Pawns tried to use they in surgeries regardless of care policy. They have no defined MedicalPotency and not supposed to be meds.
Removed taste thought from antibiotics. It alredy added via hediff.
HadMedicalDrink used nowhere.

Moved Tinctures and antibiotics from Medicine category to Drugs

---

Mods/AllowTool/Languages/Russian-SK/DefInjected/WorkTypeDefs/WorkTypes.xml

При запуске приложения в протокол фиксируется предупреждение:
Duplicate def-linked translation key: HaulingUrgent.labelShort
Verse.Log:Warning(String)
Verse.DefInjectionPackage:HasError(FileInfo, String)
Verse.DefInjectionPackage:TryAddInjection(FileInfo, String, String)
Verse.DefInjectionPackage:AddDataFromFile(FileInfo)
Verse.LoadedLanguage:LoadFromFile_DefInject(FileInfo, Type)
Verse.LoadedLanguage:LoadData()
Verse.LoadedLanguage:TryGetTextFromKey(String, String&)
Verse.Translator:Translate(String)
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()

Fix double translated Hauling

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Fueled smithy is a more advanced version of the craftsman table, but is missing the ability to smelt weapons that the less advanced version has. -Szara

Add weapon smelt to fueled smithy

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

added the missing <designationCategory>Production</designationCategory> to hopper so shows on build menu

fix missing hopper

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml

Makes it so that baking 4 potatos doesn't magically produce one big potato that's way less heavy/bulky than those 4 potatos combined with more nutrinional value than those 4 potatos combined. Nutritional value and bulk/mass changed accordingly. The 75 stack limit now makes sense. Fixes issue where pawns without loadouts would hoard baked potatos in large quantities (10 or more). Deals with an issue of pawns returning to base up to 9 times per day to eat one baked potato due to the poor nutrinional value of this meal.

Changes to baked potatos for more realism.

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Medieval.xml

Fixed Tin's stuff properties. Gave Carbon Fiber Alloy some properties so it'll have an effect on apparel made out of it.
Gave all metals slightly thermally conductive properties, so they're useless as insulators in apparel. Except Alpha and Beta poly. Since they're used in stellar construction, I expect they have some amazing properties. Or not. Can always change them later.
Gave them all -5 heat/cold insulation, which, currently, makes both values worse for the pawn. Subject to balance changes based on how it plays with the stuff multipliers of the apparel, etc.

Metal insulation initial update

---

Mods/Core_SK/Defs/HediffDefs/HediffDefs_Enlighten.xml

At the moment, fishing, electronics, foraging and collecting scale with sight uncapped.
Combat, Medicine, and research have caps>1.
How about giving things who profit from better sight in reality higher caps?
Something like:
Tailoring 1,2
Sculpting 1,3
Drugsynthesis 1,2
Fishing down to 1,1
leave electronics, forage, collecting uncapped or something high like 1,5
Operations same as tending(why does tending scale with sight but not operating? OP?)
Or just slap Manipulation there instead of sight, which I would find quite meh.
What do you think?

Fixed dark environment impacting hearing not sight

---

Mods/Minerals/Defs/ThingsDefs_Minerals/StaticMinerals.xml
Mods/Minerals/Languages/Russian/DefInjected/ThingDef/StaticMinerals.xml

Change name from Uraninite Deposit to Uranium Deposit.
Переименовано с Уранитовых залежей на Урановые

Fix uranium name

---

Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/RCT_Traits.xml

1) Fix same name in russian localization for two different traits.
2) Fix "поглащает" to "поглощает"

Fix same name in russian localization for two different traits. Fix misprint.

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Imagine the next situation:
You choose start without totems, cairns and ship's chunks (some custom scenario, example);
- if you need some wood planks - you need to build hand sawmill;
- to build hand sawmill - you need some industrial components;
- to craft industrial components - you need to build hand assembling workbench;
- to build hand assembling workbench - you need 50 wood planks;
- to craft 50 wood planks - you need... oh wait... 
to build hand sawmill!
This weird I think.
Alternative ways to solve this problems:
1) delete industrial components from hand sawmill recipe craft;
2) adds industrial component recipe craft to craftsman table.
[RUS]
Предлагаю удалить деревянные доски из рецепта стола компонентов.
Представим следующую ситуацию:
Выбираем старт без тотемов, каирнов и …

Delete wood planks from hand assembling workbench craft

---

Mods/Infused_SK/Defs/InfusionDefs/IndustrialBoosted.xml

[ENG]
Fix Glitter Tech Shocking Melee infuse.
It was very-very-very powerful infuse (+1200 % (!!!)...).
[RUS]
Исправил зачарование ГиперТех шокирующий.
Он был слишком мощным (+1200 % (!!!)...).
- до фикса:
https://i.ibb.co/527VfsK/image.png
- после фикса:
https://i.ibb.co/NyqW69d/image.png
Почти 10-кратная разница в уроне была...

Fix Glitter Tech Shocking Melee infuse

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml

Add android leather some armor stats. It's had 150% heat armor and no have any sharp and blunt armor.
Добавил коже андроидов броню. У неё было 150% защиты от нагрева (которую она подтягивала из ванильной "LeatherBase", а с новой версией СЕ это очень много) и не было вообще никакой защиты от удара и проникновения. Добавил немного защиты, чтобы уж чуть-чуть была полезной.
Заявка:
https://github.com/skyarkhangel/Hardcore-SK/issues/2039

Add android leather some armor stats.

---

Mods/Infused_SK/Defs/InfusionDefs/IndustrialBoosted.xml

Light boost GlitterTech dam0-dam5 infused.
Before Infused_SK update this infusions give two type damage boost:
- multiplier damage boost;
- flat damage boost.
After Infused_SK update flat damage boost was deleted and GlitterTech dam0-dam5 became worst melee infusion with high market price boost.
I offer to return second damage mod to this infusions type.
Example GlitterTech dam5 after this patch: https://i.ibb.co/0tbh4fX/image.png
Before: https://i.ibb.co/NyqW69d/image.png
Небольшой буст зачарования типа ГиперТех dam0-dam5.
До обновления мода Infused_SK, данные типы зачарования давали два усиления урона в ближнем бою:
- множитель;
- чистая прибавка к урону.
После обновления этого мода, чистая прибавка к урону стала работать как % прибавка и была впоследствии удалена.
Теперь данное …

Light boost to GlitterTech dam0-dam5 infused

---

Mods/Infused_SK/Defs/InfusionDefs/MedievalEnchanted.xml

Fix ancient infusion. Now it give 330% armor multiplier.
https://cdn.discordapp.com/attachments/272924909649395712/705856661499412622/unknown.png
In early infusion version it gave 25% armor multiplier. Return it.
Исправил множитель брони у зачарования "Древний". В старых версиях он имел множитель 25%, после обновления Infused - стал 330%. Возвращаю 25%.

Fix ancient infusion

---

Mods/Androids/Defs/ThingDefs/Apparel_Android.xml

Fix some thermal wrapping stats and craft categories:
1) add some general stats (carrybulk, suppressability and other) like other apparels;
2) fix StuffEffectMultiplierArmor. It had old CE value;
3) replace "Leather" from craft to "HF" (thermal wrapping craft unlock only after android printer research and can't be created from spacer stuff, but you can craft it from neolithic leather... for real? :) )
Пофиксил некоторые параметры и изменил категорию крафта у Термической шали:
1) добавил основные статы по аналогии с другой одеждой (переносимый объем, подавляемость и т.д., добавил чуть-чуть, т.к. шаль слабовато походит на одежду, но все же обидно, что она ничего не дает);
2) пофиксил значение множителя брони материала, он был из старой версии CE;
3) заменил крафтовую категорию "Кожа" на …

Fix some thermal wrapping stats and categories

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorStone.xml

Поправил баг, с керамическим полом случайного мощения, который открывался тир 2 технологией, а не тир 3, как остальные полы того же типа.
I fixed a bug with a random-paving ceramic floor, which was opened by Tier 2 technology, and not Tier 3, like the rest of the floors of the same type.

Ceramic floor bug fix

---

Mods/Androids/Defs/AlienRace/AlienRace_Droids.xml

It was lesser than other races and some medieval weapon.
Исправил бронепробитие дроидов врукопашную. Значения были ниже, чем у других рас и некоторого оружия средневековья.

Fix droids melee armor penetration

---

Mods/CombatExtended/Defs/ThingDefs_Misc/Gas_Various.xml

Fix pawn accuracy in gas area.
It's temporary fix till things go better (adding scaling value of ppm and accuracy for example. Now even 1 ppm give full penalty. It ridiculous...)
Фикс точности в загазованной области.
Это временный фикс, оставим эту функцию до лучших времен (например, пока не появится скалирование точности от концентрации дыма. Сейчас даже 1 ppm режет точность пешки по максимуму. Это бред...)

Fix pawn accuracy in gas area (1.1)

---

Mods/CombatExtended/Defs/ThingDefs_Misc/Gas_Various.xml

Fix pawn accuracy in gas area.
It's temporary fix till things go better (adding scaling value of ppm and accuracy for example. Now even 1 ppm give full penalty. It ridiculous...)
Фикс точности в загазованной области.
Это временный фикс, оставим эту функцию до лучших времен (например, пока не появится скалирование точности от концентрации дыма. Сейчас даже 1 ppm режет точность пешки по максимуму. Это бред...)

Fix pawn accuracy in gas area (1.0)

---

Mods/Core_SK/Defs/HediffGiverSetDefs/HediffGiverSets_Diseases.xml
Mods/Core_SK/Patches/HediffGiverSetChanges.xml

Some conclusions after testing:
- filth from disease has some influence to performance (very noticeable in large colonies with 15+ pawns);
- even in vanilla rimworld it's very dangerous thing with good medicine start.
Некоторые выводы после тестирования:
- грязь от болезней влияет на производительность (причем очень заметно, если пешек 15+);
- даже в ванильной римке с хорошим стартом (в плане медицины) мод на распространение болезней довольно опасен.
P.S. на текущий момент в относительно развитых колониях эта система неплохо так влияет на фпс, создавая 1000 единиц грязи буквально на глазах... заставлять всех пешек убираться тоже не выход - будут лагать уже пешки :D
P.S.S. хотя бы на 1.0 стоит принять эти правки, грязь никуда не пропадает на этой версии.

Some small changes to new disease system (1.1)

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml

Fix Nova skin color generator. Skin color was unnatural by default and cannot be edited.
Исправил генератор цвета для кожи расы Нова. Цвет кожи нельзя было редактировать + у них был неестественный для них цвет кожи по умолчанию.

Fix Nova skin color generator

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Electronics.xml

Fix electronic components recipe.
Исправил рецепт электронных компонентов.
Он требовал продвинутый компонент, который можно скрафтить только из сверхпрочных сплавов.
Сверхпрочные сплавы можно скрафтить только после постройки электродуговой печи.
Для постройки электродуговой печи нужны электронные компоненты.
Для крафта электронных компонентов нужна электродуговая печь.
Круг замкнулся...

Fix electronic components recipe.

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Pawns_WorkRecipes.xml

Fix general labor speed rus translation
Исправил перевод параметра "general labor speed". 
Причины:
- задвоение и пресечение возможных недопониманий (у нас есть "Общая скорость работы" и "Скорость общей работы"...);
- не знаю, кто и зачем переводил его как "Скорость общей работы", когда само слово означает именно неквалифицированный труд. В 1.1. как я понял туда засунули шитье и ковку, в ХСК эти параметры все ещё остались и функционируют. Пока что сменю только название. Описание можно будет поправить позже, когда будет ясно, останутся ли с нами параметры ковки и шитья или нет.

Fix general labor speed rus translation

---

Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_WeaponComponents.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Carabines.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Grenades.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Heavy.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Launchers.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Misc.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Pistols.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Rifle.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_SMGs.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Shotguns.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Snipers.xml

Зачем нужно было класть продвинутые компоненты во ВСЕ рецепты? (они крафтятся из сверхпрочных материалов, большая часть из которых доступна только в космической ветке исследований, к сведению).
Я подозреваю, что это было сделано случайно, ибо крафтить вооружение начала прошлого века (например, ПТРД или пистолет M1911) из ферротитана или штейна это... как бы это так сказать... сильно...
Для части оружия действительно можно добавить подобные компоненты (например, СмартГан или МикроГан или какое-нибудь продвинутое хайтек оружие, но в обыкновенном огнестреле они избыточны. Достаточно обыкновенных прочных (например, стали) и пластика).
Возможность создания вооружения из-за этих компонентов отсутствует как таковая полностью до выхода в сверхпрочные материалы, которые ещё нужно потом выкопать и …

Why was it necessary to put advanced components in ALL weapon recipes?

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Grenades.xml

I was test this and it's still safe to throw grenades to new min range 
(except frag grenade. It's still very random thing):
Also fix norb hammer smelting drop.
Снизил минимальный радиус броска гранат. Протестировал, с новым радиусом все ещё довольно безопасно бросать гранаты (кроме осколочной, это настолько рандомная штука, что никакой минимальный радиус не спасет от этого (см. скриншот выше)).
Также исправил дроп после переплавки молота тора, дропались сверхпрочные компоненты

Some grenade min range and norb hammer smelting drop correcting

---

Mods/Core_SK/Defs/Storyteller/Incidents_Map_Threats.xml

add earliestDay to psychic part and increase minThreatPoints to event start spawn.
Добавил значение earliestDay психообломку и увеличил minThreatPoints  до нормальных значений.
Ко мне тут в огород прилетел обломок где-то на втором году колонии, а у меня только винтовка, пистолеты и арбалеты :D
Посмотрел как было в 1.0 - там были именно такие значения для этих эвентов. Учитывая, что мехи достаточно мощные, то такие ограничения вполне справедливые. (ниже скрин из 1.0)

Update ship part crash param

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_saltmine.xml

It's require crafting instead mining.
Добыча соли в соляной шахте требовало ремесло, хотя сама работа добычи соли находится в горном деле.
Также немного снизил объем работ для добычи соли (на 10%).
теперь требует горное дело.

Some salt mining fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Beds.xml

Single and double pod bed require different component. Fixed.

Fix pod double bed

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Weapon.xml

Убрал один тег у снайперки BFR, чтобы предотвратить появление её у пешек в их спец. эвенте (который не подразумевает снайперскую стрельбу).

Remove some weapon tag to prevent spawn with ratkin guerrilla raid

---

Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_LeatherAndWool.xml

1 ratkins hasn't wool like orassans (they have 1.6 too). Suggest decrease this value to 1.1;
2 some correcting hunger rate (ratkins has lower than other body size => they need to eat often than other races... too often);
3 fix heat armor of king hamster wool and leather, some flammability tweaks.
1 раткины не орассаны и шерсти у них нет (у последних 1.6). Предлагаю понизить значение до 1.1. (1.0 + хвост = 1.1);
2 продолжаю изучать прожорство жраткинов, ещё немного корректировки для множителя голода, сейчас все равно слишком часто едят... и много...
3 несколько правок текстиля королевского хомяка (забыл перенести из 1.0 их статы).

Some flammability, base hunger rate and king hamster textiles tweaks and fixes

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

Удалил think class для блока щитов, в СЕ есть свой аналог, который щиты раткинов получают из Shield_Base.

Remove duplicate think class. CE also have this

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

after this changes https://github.com/skyarkhangel/Hardcore-SK/commit/667124d4679dd07d167aa91ad3a22c4092b0392e
it's impossible to build stonecutter table (not enough same stone blocks drop from cairn)
после этих изменений невозможно построить на старте обычный каменный станок (каирны из разных материалов, просто не хватает одного типа материалов).
Учитывая будущие перерисовки станков, дерево будет выглядеть нормально.
P.S. я конечно не уверен, но вроде бы что-то подобное с каирнами было уже когда-то давным-давно...

Added stonecutter's bench Wood Logs stuff Categories

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml

Was cook and smelting (wat?) workSpeedStat. Replace to drug synthesis speed.
Исправил стат пешки, отвечающий за крафт медицины. Требовался навык готовки и переплавки (ват?). Заменил на скорость синтеза препаратов.

Fix workSpeedStat for medicine craft recipes

---

Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Meals_SK.xml

Поправил перевод, теперь новая еда должны быть переведена.
Пешки теперь корректно берут в инвентарь жаренное ассорти. Заметка на будущее для дочитавших: опция "любой рацион" в настройках снаряжения СЕ распознаёт только готовую еду с временем хранения не более 5-6 дней (пока что под это попадают все стандартные блюда).

Fixed pawns not picking up food, fixed translation

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture.xml

1) 1x2 and 1x3 table had same cost;
2) now one tile of this table costs 20 stuff.

Fix Millenium Tables costs

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Cold.xml

Redwood trees are found only in the NPS mod, but the trees themselves are in Core_SK (including plants). I suggest adding a small amount of them to some standard biome . For example, boreal forest. According to the description, there is snow in the redwood forest. In the game, the biome itself is located next to the boreal forest and it is also often cold there.
Предлагаю добавить красные деревья в тайгу.
Красные деревья встречаются только в моде NPS_SK, однако, сами деревья при этом находятся в моде Core_SK (в том числе растения). Предлагаю добавить немного этих деревьев в какой-нибудь стандартный биом. Например, тайгу. Согласно описанию леса красных деревьев, там есть снег. В игре этот биом всегда располагается рядом с тайгой и там также холодно, как и в тайге. Появится возможность …

Added redwood tree plant to boreal forest

---

Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Food.xml
Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Special.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Special.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Meals_SK.xml
Mods/RatkinRaceHSK/Defs/ThingDefs_Building/Buildings_Production.xml

New food: 
- Coconut curry - electric stove tier, boosts movement and increases max comfortable temperature. Great for desert runs
- Miso soup - professional stove tier, boosts consiousness, movement and increases skill learning rate. 
Changed:
- Cheese burger - professional stove tier, boosts pain resistance, movement and lowers hunger rate.
- Fruits have longer shelf time, meals lower shelf time 
-----------------------------
Новая еда: 
- Кокосовое карри - уровень электрической плиты, улучшает движение и увеличивает максимальную комфортную температуру. Идеально для пустынных колоний
- Мисо суп - уровень профессиональной плиты, улучшает сознание и движение, а также увеличивает скорость обучения навыкам
Изменены:
- Чизбургер - уровень профессиональной плиты, улучшает сопротивление боли, …

Foodchange

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Recipes_HandGrenades.xml

It's didn't work.
Не работал.
P.S. зачем-то вместо гранаты прописали сам летящий снаряд этой гранаты.

Fixed Flashbang grenade recipe x3

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Stun_SK.xml

This should reduce wanting to use fists instead of a stun gun for all pawns (especially thermoses):
Also I light reduced attack speed and increased melee penetration to balance.
Исправлен приоритет атаки пешек шокером и палкой-воспиталкой.
Эти правки должны сбавить пыл у пешек бить кулаками, держа в руке один из шокеров (особенно у термосов, которые вообще его не использовали (см. скрин выше)).
Взамен немного уменьшил скорость атаки и увеличил бронепробитие.

Fix Shocker & Electric Baton pawns attack priority.

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/AlienRace/AlienRace_Droids.xml
Mods/AsariRace/Defs/ThingDefs_Races/Races_Asari.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Neolithic.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Lance.xml
Mods/RatkinRaceHSK/Patches/ThingDefs_Races/Race_Rakinlike.xml

Fix pawn fists and some weapons attack priority pt.1 (hope it would be only one part).
This should reduce wanting to use fists instead of some melee weapon.
Also balancing armor penetration to androids/droids.
Немного подправил вес у кулаков и некоторого оружия. Теперь пешки будут меньше хотеть бить кулаками вместо оружия.
Также подправил бронепробитие у андроидов и дроидов.

Fix pawn fists and some weapons attack priority pt.1

---

Mods/RatkinRaceHSK/Patches/ThingDefs_Races/Race_Rakinlike.xml

Удалил дублирующуюся вкладку инвентаря у раткинов.

Delete duplicate gear tab (ratkins)

---

Mods/Core_SK/Defs/HediffDefs/HediffDefs_Enlighten.xml

Сыворотка исцеления снимала эффект освещенности. Убрал эту странность.

Remove healer mech serum and enlighten interaction

---

Mods/Minerals/Patches/01_HardcoreSK/DynamicMinerals.xml

stops sulfur and salt crystal spawns from destroying buildings

Same salt and sulfur fix for 1.1 version

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Farm.xml

Additional to https://github.com/skyarkhangel/Hardcore-SK/commit/cba3952ff5e3d9a1af48dcbaa6faf1ff916db39d
Allow to be packed animal but not added pack params.
Дополнение к коммиту выше.
Альпаке вернули возможность быть вьючным животным, но переносимый вес и объем добавить забыли.

Added alpaca weight & bulk carry param

---

Mods/ArcaneTechnology_SK/Patches/Pawn/Pawns.xml

Added space tech level to some ratkin pawns (these pawns carry weapons / armor, available only with researching power armor / 3D printing).
**Pawn list**:
- Ratkin Subject.
- Ratkin Elite Soldier.
- Ratkin Demon Man.
Добавил некоторым пешкам раткинов космический технологический уровень (эти пешки носят оружие/броню, доступные только с исследованием силовой брони/3D печати).
**Список пешек**:
- Раткин Подопытный.
- Раткин Элитный Солдат.
- Раткин Подрывник.

Added spacer tech level to some ratkin spacer pawn

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Matter.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Matter.xml

Добавляет в Конвертер материи рецепты на преобразование материи в парафин и сульфаты в дополнение к существующему рецепту на преобразование материи в полимеры. Позволяет на поздних этапах игры перейти к получению нефтепродуктов из материи.
Adds to the Matter Converter recipes for converting matter to paraffin and sulfates in addition to the existing recipe for converting matter to polymers. Allows in the late game to go to the production of oil products from matter.

Additional recipes for Matter Converter

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Petrochemistry.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Production.xml

I propose to slightly expand the possibilities of creating rubber from raw сaoutchouc, allowing to use this recipe before the discovery of oil. Reasons:
1) vulcanization recipe is almost never used by anyone due to its late availability and low efficiency;
2) there are some useful buildings in the game that require only rubber from other oil products for their construction, but access to their construction opens much earlier than the petrochemical industry itself (for example, a small tool cabinet).
3) growing hevea trees is quite problematic and it grows only in the tropics, so this expansion will not have a serious impact on the balance but at the same time it will bring a little variety to the game.
Sulfur or sulfur-containing substances (including ash) can be used as an analog of …

Vulcanize rubber recipe light expansion

---

Mods/Core_SK/Defs/CombatExtended/Ammo/HighCaliber/14.5x114mmSoviet.xml

I created some comparison why-table and noticed the following:
1 14.5x114 mm and 20x102 mm have same RHA penetration;
2 14.5 mm AP-I have more flame dmg than .50 bmg and 20x102 mm calibers;
3 14.5 & 20 mm HE have same (almost) damage;
4 14.5 mm HE and AP-I have different bullet dmg (45 and 38). .50 bmg (28 and 28) & 20 mm (46 and 45) have similar (or almost);
5 14.5 and 20 mm calibers are generally very similar, although their bullet energy differs radically (30-32 kJ versus 49-53 kJ). 12.7 mm (.50 bmg) has about 18-20 kJ. 14.5 should be closer to 12.7 mm, not 20 mm.
I suggest correcting this a bit.
Создал небольшую сравнительную why-таблицу и заметил следующее (см. таблицу выше):
1 14.5х114 мм и 20х102 мм имеют одинаковое бронепробитие в БКГ;
2 14.5 мм бронебойно-зажигательные патроны …

14.5x114 mm caliber param correction

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Beds.xml

Light beds param correction (industrial beds is op):
Небольшая корректировка параметров кроватей (некоторые топовые кровати были хуже индустриальных)

Beds immunity and rest param correction

---

Mods/Core_SK/Defs/ThingDefs_FishIndustry/Building_FishingPier.xml
Mods/Core_SK/Defs/ThingDefs_FishIndustry/Races_Animal_Fish.xml

1 fixed inability to build a swamp pier in swamps (Undefined terrainAffordanceNeeded param & deleted duplicates of this);
2 fixed inability to fish in swamp biomes. There was not a single fish. Added a couple. 
Mashgon – A medium shellfish often found in the swamps and marshes. Its name comes from the local tribespeople calling it "marsh dragon"... Marsh dragon who cannot be found in march & swamp of swamp biomes... how ironic.
1 исправил невозможность построить пирс для болот на болотах (требовал поверхность типа Undefined. Также удалил дубликаты требования к поверхности. У базы пирсов они уже были прописаны).
2 исправил невозможность рыбачить во всех болотных биомах. Там не были ни одной рыбки. Добавил парочку.
В описании Машгона сказано, что некоторые племена прозвали его "болотным …

Fishing tweaks & fixes

---

Mods/RatkinRaceHSK/Defs/FactionDefs/Factions_Misc.xml
Mods/RatkinRaceHSK/Defs/PawnKindDef_Ratkin/PawnKinds_Player.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

1 added high-tech only ratkin raid type (late game only);
2 delete gloves & boots from ratkin high-tech pawns (sometimes there was an red error when spawning). Battle suit now cover hands and feet. Also correcting insulation & germ param of it;
3 added wearing spacer helmet to ratkin mask;
4 removed redundant weapon tag.
1 добавил рейд раткинов, состоящий только из высокотехнологичных пешек (для лейта);
2 удалил перчатки и ботинки у высокотехнологичных пешек раткинов (из-за них иногда возникала красная ошибка при спавне, сама пешка при этом не спавнилась). Вместо них боевой костюм раткинов теперь закрывает кисти и ступни. Скорректировал параметры изоляции и параметры распространения микробов в связи с этими изменениями;
3 добавил маске раткинов эффект космического шлема (т.к. сам шлем …

Ratkin pawns & apparels tweaks & fixes

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Pistols/45ACP.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Pistols/9x19mmPara.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/303British.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/556x45mmNATO.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/762x39mmSoviet.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/762x51mmNATO.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Pistols/7.62x25mmTT.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/545x39mmSoviet.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/762x54mmR.xml

The following issues are currently observed with HP ammo:
1 HP ammo require carbon for crafting. By the time it's becomes possible to create this, their effectiveness tends to zero (cuz enemies with strong armor appear starting (like mechanoids));
2 to create HP ammo, lead or other heavy materials are not required at all, but at the same time it is possible to use ultra-solid bars when creating them. I think this is very strange cuz HP ammo cuz HP ammo and FMJ ammo have not so much differents. 
Main differents - no/not full metal jacket & hollow point.
I propose to rethinking the recipes by adding the ability to create several types of HP ammunition in one recipe:
- no/not full metal jacket version (heavy bars/solid bars + heavy bars + powder);
- polymer-tipped bullets version (plastic + …

HP ammo craft rethinking

---

Mods/Androids/Defs/FactionDefs/Factions_Androids.xml

https://discord.com/channels/272340793174392832/283226662970195969/758655495472152597
Исправление неработоспособности мода "Цифры" на сценариях андроидов (красная ошибка с отсылкой на apparelStuffFilter )

Fix unworking numbers mod with android scenarios (apparelStuffFilter red error)

---

Mods/Dubs-Bad-Hygiene/Defs/ThingDefs_Buildings/BuildingsB_Hygiene.xml

added some missed latrine stuff categories (Precious + Bricks).
добавлены две пропущенные категории у выгребной ямы (драгоценные металлы и глиняные кирпичи) (гальюн из золота!).

Golden latrine

---

Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Defences_SK.xml

Дублировался + некорректное описание и название. В CoreTranslation уже есть и оно корректное.

Fix barricade rus translation (duplicate)

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Pistols/45ACP.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Pistols/9x19mmPara.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/303British.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/556x45mmNATO.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/762x39mmSoviet.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/762x51mmNATO.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Pistols/7.62x25mmTT.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/545x39mmSoviet.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/762x54mmR.xml

I created some why-table and noticed the following:
1 .45 ACP FMJ and HP ammo have 2 more dmg than 9x19 mm FMJ and HP but have some lesser RHA armor penetration. .45 ACP AP and 9x19 mm AP ammo have similar dmg, but .45 ACP stil have lesser RHA penetration than 9x19 mm. It's strange I think;
2 parameters of the HP ammo lower than that of the FMJ and AP version (HP lose more % of the RHA penetration than it's receive % of damage) (it's very noticeable in pistol ammo);
3 some pistol HP ammo have worse dmg/RHApenetration param than metallic bolts (why?);
4 .45 ACP as the heaviest pistol bullet should have little more MPa penetration than other I think.
I suggest increasing the armor penetration of all HP ammo a little bit.
[rus]
Решил создать why-таблицу (см. выше) и заметил следующее:
1 .45 …

Some ammo dmg & penetration tweaks & fixes

---

Mods/Core_SK/Defs/ScenarioDefs/Scenarios_K_TheRichExplorer.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ScenarioDefs/ScenariosPatch.xml

1 fixed red errors log spam from missed multitool stuff material. Added stein alloy.
**Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
Verse.Log:Error(String, Boolean)
Verse.Widgets:EnsureMousePositionStackEmpty()
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Entry:Update()**
2 added starting weapon to Rich Explorer scenario (MA5 ICWS - looks futuristic enough and does not conflict with Arcane Technology mod);
3 replaced stuff material of starting tent from cloth to synthread (high-tech start after all).
[rus]
1 исправлен спам красных ошибок из-за отсутствия материала мультитула. Добавил штейн.
2 добавил стартовое оружие в сценарий Богатого Исследователя. По умолчанию его почему-то не было. Добавил винтовку Halo Fanon MA5 - …

Some Rich Explorer starting scenario tweaks & fixes

---

Mods/RatkinRaceHSK/Defs/FactionDefs/Factions_Misc.xml
Mods/RatkinRaceHSK/Defs/PawnKindDef_Ratkin/PawnKinds_Player.xml
Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

1 increased earliest raid days from 120 to 135;
2 more powerful pawns will appear later;
3 added new early raid type - ratkin murders:
4 some item quality & gears heals range tweaks & fixes;
5 light correction medieval ratkins armor & shield armor rating value;
6 fix meat amount & leather type by ratkin corpses butchering.
1 увеличил количество дней со старта колонии, после которых рейды раткинов могут начать приходить с 120 до 135;
2 самые мощные пешки раткинов будут появляться несколько позже (в зависимости от стоимости колонии);
3 добавил новый тип ранних рейдов раткинов (см. картинку выше);
4 некоторые правки качества предметов и прочности у пешек при их спавне. Местами были выше нормального значения;
5 немного скорректировал значения брони у средневековой брони и щитов раткинов;
6 …

Some ratkins raids tweaks & fixes

---

Mods/RatkinRaceHSK/Defs/FactionDefs/Factions_Misc.xml
Mods/RatkinRaceHSK/Defs/PawnKindDef_Ratkin/PawnKinds_Player.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Weapon.xml

1 In continuation https://github.com/skyarkhangel/Hardcore-SK/pull/2482 (raids fixes);
2 replace titanium bars to ferrotitanium bars in battlesuit and mask recipes.
1 небольшое продолжение правок фиксов рейдов раткинов;
2 в рецептах боевого костюма и маски раткинов титан заменен на ферротитан.

Some ratkin's raids & recipes tweaks & fixes

---

Mods/Core_SK/Defs/FactionDefs/Factions_Mech.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Norbal.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Pirate.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Mercenary.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Norbals.xml

1 added pikeman pawn to mechanoid raids;
2 light combat power cost boost to Mercenary Slasher (~ 10%, cuz this pawn has very strong guardian power shield);
3 light mercenary slasher amount to pirates melee only raid fixes (~ 10% reduced);
4 added norbal guardian shield to some high tier norbal melee pawns;
5 norbal raids curve correction (cuz (4)).
1 добавил драгуна в обычные рейды механоидов;
2 немного увеличил стоимость пешки "наёмник-вышибала", (~ 10%, т.к. приходит с сильным для своей стоимости силовым щитом);
3 немного уменьшил вес пешки "наёмник-вышибала" в мили-рейдах пиратов (~ 10%);
4 добавил силовой щит норбалов некоторым самым сильным пешкам ближнего боя;
5 в связи с пунктом (4) немного откорректировал кривую силы рейда норбалов (чтобы пешки с силовыми щитами не приходили …

Some raids tweaks & fixes

---

Mods/CombatExtended/Patches/Core/HediffDefs/Hediffs_Local_Injuries.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Arrows.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Bolts.xml
Mods/Core_SK/Defs/HediffDefs/HediffDefs_ResistPain.xml

1 light arrow & bolt armor penetration correction;
2 returned berserk state passive pain factor to 75%;
3 added missed cut & bite painPerSeverity CE patch.
1 небольшая корректировка бронепробития стрел и болтов;
2 откатил изменения пассивки норбалов до предыдущего состояния (=75%);
3 добавил отсутствующие патчи на накопление боли от порезов и укусов (странно, что СЕ не пропатчили эти типы урона, раны от них оставляют намного меньше боли, чем от остальных атак).

Some neolithic ammo & pain giver tweaks & fixes

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorBrick.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorMetallic.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorStone.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorWood.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_Floors_SK.xml
Mods/Core_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_Floors_SK.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Buildings/PatchesFineFloors.xml

1 fixed silver & metal tile colors;
2 fixed silver tile work amount (did not match the description);
3 added copper & tin metal tile floors;
4 increased royalty fine carpets (4->8) & fine stone tiles beauty (3->6);
5 added exquisite category (royalty patch) to some top-tier HSK floors (bamboo, red floors, golden & silver tiles and etc);
6 correcting some bamboo & redwood floors cost (cuz (5));
7 some bricks-like floors now can be build from clay bricks.
[rus]
1 поправлены цвета серебряной и металлической плитки (не соответствовали цвету материалов);
2 поправлен объем работ для серебряной плитки (не соответствовал описанию);
3 добавлены медные и оловянные металлические плитки (медь и олово все равно редко используется, хоть полы из них сделаем);
4 добавил патч на увеличение красоты от …

Some floors tweaks & fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Exotic.xml

Поправил крафт тотема. Теперь при разборе будет выпадать не дерево, а материал тотема.

Fix stuff count type cost of totem crafting

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Synthetic.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_ProstheticsInstall.xml

Patch enable existing surgery recipes for muscle stimulator.
Now you can craft, sell or buy and INSTALL them.

Fix muscle stimulator surgery bug

---

Mods/RatkinRaceHSKFaces/Defs/BodyAnimDef_Ratkin_Thin.xml

Fix ratkins head position:
Исправил положение головы раткинов. Это было слабо заметно, но она немного отходила от их тела.

Fix ratkins head position

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Tech.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml
Mods/Core_SK/Languages/Russian/DefInjected/ResearchProjectDef/ResearchProjects_Tech.xml

Moved ground-penetrating scanner research research prerequisites (Geophysics -> Geology):
- before:
- after:
Cuz drill and mine extractor can't work without scanner.
Сдвинул требования исследований для глубинного сканера (Геофизика -> Геология).
См. скриншоты выше.
Связано с тем, что бур и добывающая установка без него работать не могут (т.к. залежи генерируются этим сканером).

Moved ground-penetrating scanner research research prerequisites

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Boots.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Feral.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Fullarmor_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Gloves.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Outlander.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Mask.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_SlaveOutfit.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Special.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Vests.xml

1 some medieval & neolitic apparels now requires primitive components instead of (industrial) components;
2 some industrial apparels required advanced & medieval components instead of (industrial) components. Fixed;
3 remove hexcell requirements from marine storm mask (it's not spacer armor).
1 некоторая одежда средневековья и неолита теперь требует примитивные компоненты вместо индустриальных компонентов;
2 часть индустриальной одежды требовала продвинутые и примитивные компоненты вместо индустриальных. Исправил;
3 убрал из крафта маски штурмовика модуль питания (это простая индустриальная маска, а не хай-тек броня).

Apparel's component type cost fixes

---

Mods/Core_SK/Patches/Minerals_Patch.xml

Disables screen shake for dynamic minerals (sulphur, salt, etc) when mined

Disables screen shake while mining (part 2)

---

Mods/Core_SK/Defs/CombatExtended/Ammo/AmmoBases.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons.xml
Mods/Core_SK/Patches/ThingSetMakerDefs/ThingSetMakers_RewardPatches.xml

1 replaced steel to melchior (cuz steel use plasteel def, but steel has very low cost. Melchior have high cost and not so strong properties (almost like steel but better a bit);
2 added non high-tech weapon to quest reward pull;
3 added ammo to quest reward pull.
1 заменил сталь на мельхиор в наградах за выполнение квестов (сталь использует def пластали, но при этом стоит намного меньше (пласталь в ваниле стоит 9, а сталь - 2). Мельхиор дороже (8) и при этом не сильно лучше стали. Должно избавить от 15к+ стали в наградах);
2 добавлено невысокотехнологичное оружие в награды квестов;
3 добавлены патроны в награды квестов.

Some quest rewards tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Stuff_Leather.xml
Mods/Core_SK/Royalty/Patches/QuestScriptDefs/QuestScriptDefsPatches.xml

1 Corrected costs, rewards and threat points of Building Monument Quests (~2.5 fold lesser) (very large monuments and very large rewards/threat. Fixed);
2 Lightly increased chance to spawn apparel from some rare leather (I have never seen dragon or thrumbo skin clothing).
1 Скорректировал размеры монумента, награды за выполнение задания и силу угроз (стало примерно в 2.5 раза меньше) (слишком большие постройки/награды/силы рейдов для текущей стоимости. Поправил);
2 Немного увеличил частоту появления одежды из редких шкур (драконьей, Трумбо и т.д. Не припомню, чтобы хоть раз видел одежду из них).

Corrected costs, rewards and threat points of Quests pt.1 - Building Monument Quests & some rare leather commonality fixes

---

Mods/Dubs-Bad-Hygiene/Defs/DesignationSubCategoryDefs/SubCategories_dubs.xml
Mods/Dubs-Bad-Hygiene/Languages/Russian/DefInjected/ArchitectSense.DesignationSubCategoryDefs/SubCategories.xml

Renamed categories, conflicted with existing ones.
Переименованы категории, для устранения конфликта с уже существующими.
"Showers" перевел как "души". Выглядит странно, но кажется это допустимо.
https://ru.wiktionary.org/wiki/%D0%B4%D1%83%D1%88#%D0%B4%D1%83%D1%88_I

minor revision of hygiene categories and their translation

---

Mods/ArcaneTechnology_SK/Patches/Pawn/Pawns.xml

Fixed a bug when spacer pawn couldn't wear spacer items. On default Arcane Technology params if you want to wear spacer item you need (spacer+1) tech level (= Ultra).
Исправлен баг, когда высокотехнологические (далее просто spacer) пешки не могли носить spacer предметы. В настройках по умолчанию мода Arcane Technology пешка будет носить spacer предметы только в случае, если её технологический уровень будет на единицу выше (т.е. spacer+1=ultra).

Fix bug when spacer pawn can't wear spacer items

---

Mods/CombatExtended/Defs/HediffDefs/Hediffs_CE.xml

It should help to prevent spawn pawn with mask hediff without any mask or other hats with PC (PrepareCarefully) randomizer
Небольшая правка хедиффа от масок. В редакторе мода PC будет возможность его добавить/убрать. При использовании рандомайзера этого мода, хедифф маски сохраняется, даже если пешка уже без шлема, но убрать его все равно никак нельзя.

Some mask hediff fixes

---

Mods/Core_SK/Royalty/Patches/PawnKindDefs_Royalty/PawnKinds.xml

1 correcting weapon money (ASN2 and ASN3 tags have weapon with cost higher than 3000);
2 base IndustrialGunAdvanced and SpacerGun weapon tag don't work with HSK (no weapons with this tag), but SniperRifle works -> Janissaries have only sniper rifles (in vanilla Janissaries also use other guns). Correcting tags.
1 скорректировал стоимость оружия у янычар (в состав тегов ASN2 и ASN3 входит только оружие со стоимостью более 3000);
2 базовые оружейные теги IndustrialGunAdvanced и SpacerGun не встречаются среди оружия ХСК, но тег SniperRifle встречается у всех снайперских винтовок из-за чего янычары приходят только со снайперками (в ванили у них большее разнообразие оружия). Корректировка тегов.

Fix Janissary royalty patch

---

Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Bakery.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Bakery.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated_Manufacture.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated_Vegetables.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_CookingSupplies.xml
Mods/Core_SK/Defs/ThoughtDefs/Thoughts_Memory_Special.xml
Mods/Core_SK/Defs/TraitDefs/Expanded Traits.xml
Mods/Core_SK/Languages/Russian/DefInjected/HediffDef/Hediffs_Food.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Meals_SK.xml

Rebalanced half of the baked dishes, cornbread muffins are not as good now, pizza requires more ingredients but gives really nice buffs now (lowers pain, improves consiousness and **reduces incoming damage**). Baking is a lot more viable in general now.
Misc:
- increased aurora buff duration, now it actually worth waking up your pawns to see it
- for some reason religious trait increased mental break threshold despite description saying the opposite
------------------------------------------
Перебалансил половину выпечки, булочки из кукурузной муки не имеют таких больших баффов, пицца теперь требует больше ингредиентов, но даёт очень сочные баффы (снижает боль, улучшает сознание и уменьшает получаемый урон). Выпечка теперь в целом гораздо более жизнеспособный путь прокормить колонию. 
- …

Food changes pt.2 1/2

---

Mods/Rimatomics_SK/Defs/ThingDefs_Misc/RadSuits.xml

Rimatomic apparels armor rating correction to CE.
Скорректировал показатели брони одежды из риматомикса под СЕ.

Rimatomic apparels armor rating correction to CE

---

Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml

Ironman/low pain tolerance have conflict with tough trait, but tough have not conflict. Fixed.
Поправил конфликт между чертами характера "Необычная стойкость"/"Непереносимость боли" и "Живучесть". У первых двух в списке конфликтных есть "Живучесть", а у "Живучести" в списке конфликтов нет первых.

Fix ironman/low pain tolerance and tough traits conflict.

---

Mods/SeedsPlease/Defs/ThingDefs/Buildings_Production.xml

Поправил отрисовку у стола агронома. Зачем-то был растянут и выглядел слишком крупно (и даже немного мыльно).

Fix plantprocessing bench draw size. It was so big

---

Mods/Core_SK/Defs/WorkTypeDefs/WorkTypes_SK.xml

Предлагаю уменьшить приоритет работы в карьере. Пешки в первую очередь будут копать обычные залежи ресурсов и только потом работать в карьере.

Decreased quarry natural priority. Now pawns will mine ore deposits first, not quarry mining

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml

Исправил перегонщик норбалов в топливо. Во время простоя потреблял столько же энергии, сколько и во время работы.

Fix bio refinery idle power consumption (didn't work)

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Mechanoid.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Buildings/Patches2.xml

1 Patched Mechanoid drop beacon (cluster). It didn't spawn mechanoids.
2 Crawler had lesser armor rating than simple clothes apparels. Light boost.
1 маяки кластера механоидов не вызывали подкрепление при срабатывании. Исправлено;
2 механические крабы имели слишком низкую броню (меньше, чем обычная одежда из текстиля). Немного увеличена.

Some mechanoinds tweaks and fixes

---

Mods/Hospitality/Defs/MainTab/PawnColumnDefs/PawnColumns.xml
Mods/Hospitality/Defs/MainTab/PawnTableDefs/PawnTables.xml

Hospitality column always shows player faction name. That useless. Vanilla shows temporary quest factions.

Stop vanilla worktab faction column override by hospitality

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Spacer.xml
Mods/Core_SK/Royalty/Patches/ResearchProjectDefs/ResearchProjectsPatches.xml
Mods/SurvivalToolsLite/Patches/ImplantsPatches.xml

1 Replaced hexcell in cryptopod bodysuit reciple to spacer component.
2 Added survivle tools patch to drill arm.
3 Correcting royalty techprints market value.
1 заменен модуль питания на высокотехнологичный компонент у крипто комбинезона (что делал модуль питания в обычном комбинезоне? причем у других такого даже близко нет);
2 руке-буру добавлен патч для мода Survival tools lite;
3 скорректирована рыночная стоимость чертежей роялти (увеличена в 2 раза).

Some tweaks and fixes

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Recipes_HandGrenades.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Grenades.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

1 corrected grenade recipes craft (replace advanced component to industrial);
2 corrected grenades smelt products (some grenades hadn't products, like smoke, stick and foam);
3 fix ratkin summer dress incorrect icon texture path.
1 скорректированы рецепты крафта гранат (в основном сверхпрочные продвинутые компоненты заменены на индустриальные);
2 скорректирован дроп после переплавки гранат (из дымовой, пенной гранат и гранаты на палке вообще ничего не выпадало; дроп от переплавки теперь чуть более разнообразный (например, от переплавки молота тора и гранаты на палке можно получить немного взрывчатого экстракта);
3 поправлен некорректный путь к текстуре иконки летнего платья раткинов.

Some grenade recipes tweaks and fixes

---

README.md

Add Windows executable location to readme, in lieu of the launcher automatically locating it.

Add to launcher instructions

---

Mods/CombatExtended/Defs/TraitDefs/Traits_Spectrum.xml
Mods/CyberneticOrganism_SK/Defs/Hediffs/Cyborg_hediffs.xml

Update: also returned CE traits commonality (cuz suppression now works). Also gave this traits small mental break threshold boost/penalty (if someone want play without suppression then trait become useless).
P.S. please don't adding conflict with other mental traits! CE traits are primarily designed to interact with the suppression mechanic!
Исправлена энергетическая кисть. Отсутствовала поддержка CE и бронепробитие (из-за этого она игнорировала любую броню).
Update: также вернул частоту появления CE черт характера, связанных с подавлением (т.к. теперь подавление работает). Также добавил этим чертам небольшой бонус/штраф к порогу нервного срыва (если кто-то захочет поиграть без подавления, то эти черты становятся бесполезными).
P.S. не надо добавлять их в конфликтные с другими чертами на …

Fixed energy fist. Had not CE tool compatibility (and therefore ignored any armor).

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Turrets.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Security.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Crate.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Turrets_SK.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Ammo_SK.xml

1 fixed mini turret misdescriptions;
2 replaced SMG component to Rifle (cuz it now have 5.56 mm caliber).
1 актуализировано описание мини турели и всех связанных с ней предметов;
2 заменены компоненты ПП на винтовочные в крафте деталей мини турели (т.к. калибр нынче промежуточный (5.56 мм)).

Some mini turret tweaks and fixes

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_LeatherAndWool.xml

Fixed king Hamster wool duplicates in textile categories
Исправлено задвоение шерсти королевского хомяка в категории текстиля (одновременно отображался в двух категориях, вместо одной).

Fixed king Hamster wool duplicates in textile categories

---

Mods/Core_SK/Defs/ThingDefs_Items/Items_Fluffy.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Caravan_Outlander_Exotic.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Orbital_ExoticTrader.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Orbital_PirateMerchant.xml

- changed trade tags on kirin and fenix hearts to make them tradable (nerfed their cost to account for the change)
- added a few missing tags from vanilla caravans mainly to maintain compatibility with other mods and give their items a chance to appear in hcsk caravans (also probably a few interesting things will become tradable)
- добавил теги для покупки/продажи сердец кирина и феникса, сильно снизил стоимость сердец т.к. сами существа не то что бы очень сильные, а предметы не очень то и ценные
- добавил теги для торговли из ванили, многие моды их используют, а из за того что в хск в караванах используется своё распределение - многие предметы никогда не появляются у торговцев, тесты не выявили каких то серьёзных сдвигов в ассортименте

Trade tags fix

---

Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Advanced.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Grenades.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_HighCaliber.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Pistols.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Rifles.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Rockets.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Shells.xml
Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Ammo_Shotgun.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Ammo_SK.xml
Mods/HMC weapon pack – USSR/Languages/Russian/DefInjected/ThingDefs/Ammo_SK_HMC.xml

Корректировка русского перевода для видимости количества боеприпасов в окне инвентаря.
Подробная информация о боеприпасе по-прежнему доступна в описании предмета.
---
Correction of the Russian translation for the visibility of the amount of ammunition in the inventory window.
Details of the ammunition are still available in the item description.

Ammo naming adjustments

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Furniture_SK.xml

1 corrected damage data param;
2 fixed rus translation (was 2x4).
1 исправлено отображение повреждений на обычном столе 2х3 (трещины отображались где-то в воздухе);
2 исправлен русский перевод (назывался 2х4).

Some 2x3 table fixes

---

Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/9x39mmSoviet.xml

Скорректировал параметры урона у 9х39 мм патронов (EMP и SH).

Corrected 9x39 mm EMP and SH ammo damage types

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Furniture.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Storage.xml
Mods/Core_SK/Languages/Russian/DefInjected/ArchitectSense.DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_TestStorages.xml
Mods/Rimefeller_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml

1 added sub categories to all storages;
2 corrected skip and serving table recipe craft (replaced medieval component to industrial, removed woody stuff categories (for skip only), increased max number stack to 7 (serving table only) and incresed construction skill prerequisite to 6 (both));
3 moved storage II researsh to industrial tech level (cuz most storages on this researsh level require industrial component);
4 added refinery loading bay to refineries sub category;
5 corrected weapons cabinet and weapons locker recipes;
6 some rus translation fixes.
1 добавлены подкатегории всем хранилищам (сортировка);
2 скорректированы параметры контейнера (улучшенная палета) и сервировочного стола (примитивные компоненты заменены на индустриальные, у контейнера убрана возможность быть созданным из …

Some storage tweaks and fixes

---

Mods/Skynet_SK/Defs/FactionDefs/Skynet.xml
Mods/Skynet_SK/Defs/PawnKindDefs/PawnKinds_Skynet.xml

1 slightly corrected max pawn cost per total point curve (this value always should be more than max pawn power point of this faction pawns (at least a little bit));
2 T-800 origin pawn in high tech armor and absolutely naked T-800 pawn have same cost? really? Fixed this.
1 немного откорректирована максимальная стоимость пешек скайнета в кривой рейдов (верхнее граничное значение (в нашем случае это 20к поинтов) должно быть выше (хотя бы чуть-чуть), чем максимальная стоимость самой дорогой пешки этой фракции (иначе она не будет появляться в рейдах в обычных условиях, по крайне мере мои тесты это выявили));
2 пешка Т-800 Origin в плаще скайнета (хайтек броня с силовым щитом и уклонением) и абсолютно голая Т-800 пешка стоили одинаково. Исправлено.

Some skynet pawns tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Beds.xml

удалил категорию древесины из мед кроватей

Deleted "woody" category from medical beds

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Special.xml
Mods/Core_SK/Defs/ThoughtDefs/Vanilla/Thoughts_Memory_Misc_VanillaRework.xml

Reduced debuff duration of butchering humans from 6 to 3 days.
Reduced stacked effect multiplier form 1.0 to 0.95 so max mood debuff from butching 30 corpses downed drom -90 to -47.
Yep its wired exponential dependency of stacked effect multiplier.
Praise those filthy corpse eaters. Awful.
Update 1: Reduced stacked effect multiplier to 0.92 and 0.88 for personal and colony debuffs (-34 and -24 total). Fixed RUS translation for mood labels.

Mood penalty adjustments

---

Mods/Core_SK/Defs/ScenarioDefs/Scenarios_C_LostTribe.xml
Mods/Core_SK/Defs/ScenarioDefs/Scenarios_L_MoonFall.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ScenarioDefs/ScenariosPatch.xml

- Changed clubs to be made of planks instead of logs
- Changed spears to be made out of bronze instead of planks.... I mean... What's the *point*?
- Changed starting axes to be made out of bronze instead of planks - what a great idea to cut wood with another piece of wood
- Removed heads on pikes from starting objects - they behave incorrectly if spawned by game instead of being constructed from actual corpses
-----------------------
- Поменял материал стартового топора и копья с досок на бронзу
- Поменял материал стартовой дубины с брёвен на доски
- Убрал головы на пиках их стартовых объектов - игра не может их корректно заспавнить и выкидывает ошибку, придётся украшать карту самим.

FIxes for starting scenarios

---

Mods/Core_SK/Defs/FactionDefs/Factions_Pirate.xml

Corrected Pirate faction (was "Abstracted" and don't replace vanila pirate faction (incorrect icon, should have scorpion icon)). Also slightly corrected raid point curve.
Поправил фракцию Пиратов (почему-то была "Абстрактной" и не заменяла собою одноименную ванильную фракцию (сейчас у нас две фракции с похожими иконками в виде черепа и костей - одна - ванильные космические пираты, вторая - агрессивное племя. Теперь пираты будут индустриальными со своей родной иконкой скорпиона). Также немного скорректировал кривую рейдов этих пиратов (т.к. на мой взгляд иначе слишком долго будут рейдить одни оборванцы с деревянными дубинками).

Corrected Pirate faction

---

Mods/Core_SK/Defs/FactionDefs/Factions_Pirate.xml

Убрал ванильное ограничение в 1000 поинтов для одной из рейдовых групп фракции пиратов (зачем нужно - не понятно, у остальных групп фракции такого нет, шанс спавна такого рейда при этом около нулевой).

Removed vanila max point limitation for one of pawn group maker of pirate raid (was 1000 points)

---

Mods/Core_SK/Defs/ThoughtDefs/Extratraits/Thoughts_Situation_General.xml

Nyctophobe in dark environment will not receive buff from other darkly traits (NightOwl, Undergrounder, etc).

Fix of fix of dark mood thoughts.

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/AlienRace/AlienRace_Droids.xml
Mods/Skynet_SK/Defs/ThingDefs/Races_Skynet.xml

Удален путь к старой унифицированной текстуре иконке пешек (в виде желтого силуэта) (неактуальна, т.к. игра генерирует их самостоятельно на основе внешнего вида пешки).

Removed old pawn icon texture path (obsolete)

---

Mods/RatkinRaceHSK/Defs/AlienRaceSettings/AlienRaceSettings.xml
Mods/RatkinRaceHSK/Patches/PawnKindDefs/PawnKinds_Ratkin.xml

1 corrected ratkin subject refugee chance spawn. Added ratkin vagabond refugee spawn chance;
2 added few ammo to Ratkin Vanguard pawn (was no ammo);
1 скорректирована вероятность появления раткина-подопытного в качестве беглеца. Добавлена возможность спавна пешки "Раткин бродяга" в качестве беглеца;
2 добавил немного боеприпасов пешке "Ratkin Vanguard" (их просто не было).

Some ratkin tweaks and fixes

---

Mods/Core_SK/Royalty/Defs/ThingDefs_Apparel/ArmorLocust.xml
Mods/Core_SK/Royalty/Defs/ThingDefs_Apparel/ArmorMarineGrenadier.xml
Mods/Core_SK/Royalty/Defs/ThingDefs_Apparel/ArmorMarinePrestige.xml
Mods/Core_SK/Royalty/Defs/ThingDefs_Apparel/ArmorReconPrestige.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Misc/ApparelArmorCataphractBase.xml

1 light locust armor nerf (slightly more cost/work, added few ultra component and chemfuel to craft recipe), increased warmup time to jump (0.5 -> 0.75 sec.);
2 replaced golden ore to gold bar in all royalty armor recipes. Also added few spacer component to this armor recipes.
1 небольшой нерф брони богомола (немного увеличена стоимость/время создания, в рецепт добавлено немного ультра компонентов и химтопливо (как в рецепте прыжкового ранца), увеличено время задержки перед прыжком (0.5 -> 0.75 сек.);
2 золотая руда в рецептах королевской брони Роялти заменена на золотой сплав. Также в рецепт крафта этой брони добавлено немного высокоточных компонентов.

Some Royalty armor tweaks and fixes

---

Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Pistols/7.62x25mmTT.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/545x39mmSoviet.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/762x54mmR.xml
Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/9x39mmSoviet.xml

1 replaced generateCommonality param to generateAllowChance to correction chance of ammo type spawn (raids);
2 fixed incorrect 9x39 emp base projectile (was SH instead of EMP).
1 заменен параметр generateCommonality на generateAllowChance (отвечает за шанс появления у рейдов тех или иных видов боеприпасов) (заменил, т.к. первый перестал работать после введения второго);
2 исправлен некорректный базовый снаряд у 9x39 emp боеприпасов (был SH вместо EMP).

Some USSR ammo fixes

---

Mods/CombatExtended/Languages/Russian/DefInjected/RecipeDefs/Recipes_AmmoNeolithic.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/CatapultaBalls.xml

1 stone and explosive balls had similar texture. Fixed;
2 increased amount of balls (3 -> 5) from crafting recipe (I hope this helps to make catapults a little more popular);
3 some rus translation fixes.
1 каменные и взрывные шары имели одинаковую текстуру, хотя у нас есть две разные текстуры. Исправлено;
2 увеличен выход шаров при крафте с 3 до 5 (надеюсь, это поможет сделать катапульты чуточку популярнее);
3 поправлены переводы рецептов крафта шаров для катапульты.

Some stone balls tweaks and fixes

---

Mods/RatkinRaceHSK/Defs/FactionDefs/Factions_Misc.xml
Mods/RatkinRaceHSK/Defs/PawnKindDef_Ratkin/PawnKinds_Player.xml

1 fixed ratkin kingdom (hostile faction) natural colony goodwill param (it will reducing now);
2 corrected melee ratkin raider pawns weapon cost to remove chance to spawn with hi-tech materials (like alpha/beta poly, titan etc). Also disabled chitin and velour spawn for ratkin's apparels (raids only).
1 поправлено периодическое изменение отношения враждебной фракции раткинов (теперь должно уменьшаться со временем, а не увеличиваться);
2 скорректирована стоимость оружия ближнего боя у пешек-рейдеров раткинов (для исключения возможности появления хайтек материалов вроде альфа/бета поли, титана и т.д). Также выключена возможность спавна одежды из хитина и велюра.

Some ratkin's pawns tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Storage_Fridge.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Storage_WallFridge.xml

Refrigerators should be available much earlier in the games progression. I dont see much sense in this, because we can easy & early build up our walk-in fridges but not small fridges. Refrigeratros also should not use higher tec components like microelectronics. They are also only available about late industrial stage, and up then you already have you big walk-in fridge that cost only some basic resources.
Холодильники должны быть доступны намного раньше в процессе игры. Я не вижу в этом большого смысла, потому что мы можем легко и рано построить наши "Walk-in" Холодильники, но не маленькие холодильники. Холодильники также не должны использовать высокотехнологичные компоненты, такие как микроэлектроника. Они также доступны только на поздних стадиях промышленного производства, и вплоть до …

Earlier fridges and with no microelectronics required

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Heavy.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Rifles.xml

ENG:
MA39X was too heavy for a LMG. Most LMGs weight (kg) is about 8kg. But this one, dont know why, has 20. Way to much, for what you get. Easier to just use the microgun.
SCAR-H was way to common. Sometimes you get some ferals with pistols and smgs, and then you also see some with a SCAR-H. I for my part had same issue. Had about 4 SCARs but no other rifles. Its because you get that easy feral raids, where they have about 4 SCARs, even if most of them are only armed with pistols and SMGs. You get faster a SCAR-H then you get a M16 or AK.
RU:
MA39X был слишком тяжелым для LMG. Вес большинства LMG (кг) составляет около 8 кг. Но у этого, не знаю почему, 20. Слишком много, за то, что ты получаешь. Легче просто использовать microgun.
SCAR-H был очень распространен.Иногда бывают одичалые с …

Small Weapon Fix

---

Mods/Dubs-Bad-Hygiene/Defs/ThingDefs_Buildings/BuildingsD_WaterManagement.xml
Mods/Dubs-Bad-Hygiene/Defs/ThingDefs_Buildings/BuildingsE_Heating.xml

ENG:
Water tower where to weak from HP side. A big water tower had same HP as the little water butt. 
Now all tower have more HP and they wont die after two shots.
Also removed wood requirement for water tower. I dont see any sense, why i need wood if i build a metal water tower. 
Base cost is bit higher, but no wood cost because of this. (Yay desert players)
Added electronic cost to "electric boiler" and "solar heater". Before they had no electronic cost at all. (what dont make sense for that technology)
RU:
Водонапорная башня, слаба со стороны ХП. Большая водонапорная башня имела те же самые ХП, что и маленькая водонапорная Бочка. 
Теперь у всех башен больше ХП и они не умрут после двух выстрелов.
Также удалены требования древесины для водонапорной башни. Я не вижу никакого смысла, …

Small Dubs Hygine Fixes

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Alloys.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Industrial.xml

This alloy not contain aluminium.
Скорректирован рецепт выплавки мельхиора (убран алюминий). В этом сплаве его на самом деле нет.

Corrected melchior craft recipe (removed aluminium)

---

Mods/Core_SK/Defs/Drugs/Garden Drugs.xml

1 added "is combat enhancing drug" tag to berserk herb;
2 added missed CE param (bulk and suppressability) to berserk herb. Also slightly increased mass param.
1 добавлен "is combat enhancing drug" тэг для berserk herb (для возможности использования рейдерами при их спавне);
2 добавлены пропущенные параметры CE (объем и вероятность подавления) для berserk herb. Также немного увеличил массу (была меньше, чем у дымолиста раз в десять).

Some berserk herb tweaks and fixes

---

Mods/Core_SK/Defs/ThoughtDefs/Vanilla/Thoughts_Memory_Misc_VanillaRework.xml
Mods/Core_SK/Defs/TraitDefs/Expanded Traits.xml
Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml
Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/Expanded Traits.xml
Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/RCT_Traits.xml
Mods/Core_SK/Patches/TraitDefs_Core_Patch.xml
Mods/MultiLang Colorful Traits/Defs/Mod_SK.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Weapon.xml

1 Fixed some casuses with trait conflicting (like introvert + extrovert combination);
2 Corrected traits conflicting param of some traits (illogical connections);
3 Corrected vanilla traits patch (added some trait missed conflict param);
4 Moved all additional bonuses (stats and thoughts) from Tough trait to Hardened (cuz Tough and Hardened was almost similar));
5 Returned green thumb trait (cuz we have not any traits with plant work bonuses. The trait completely copies a bad gardener, but gives bonuses instead of penalties);
6 Some trait color corrections;
7 Remove ratkin autocrossbow recipe from fueled smithy.
1 Исправлены некоторые казусы из-за некорректно проставленных конфликтов черт характера (например, комбинация интроверта + экстроверта);
2 Скорректированы конфликты черт характера …

Some trait tweaks and fixes

---

Mods/Core_SK/Royalty/Defs/RoyalTitles/RoyalTitles_Kingdom.xml

при выполнении квеста за 12+ очков короны пешкой у которой ещё не было титула - невозможно начать квест церемонии присвоения титула ("аколит" или выше), так как для церемонии требуется наличие тронного зала у пешки, а пешку на трон посадить нельзя, потому что у неё нет титула.
для сравнения: в ванили в аналогичной ситуации сразу после выполнения квеста за очки, пешка немедленно получает самый простенький титул "фриголдер". и её можно посадить на трон.
причина бага: в хск были добавлены дополнительные титулы для другой фракции Kingdom. изза неаккуратной копипасты деф фриголдера Kingdom переопределил деф фриголдера Роялки.

Исправление бага невозможности получения титула

---

Mods/HMC weapon pack – USSR/Defs/CombatExtended/Ammo/Rifle/9x39mmSoviet.xml
Mods/HMC weapon pack – USSR/Defs/DamageDefs/Damages_LocalInjury_HMC.xml
Mods/HMC weapon pack – USSR/Defs/ThingDefs_Weapons/Weapons_Carabines.xml
Mods/HMC weapon pack – USSR/Defs/ThingDefs_Weapons/Weapons_Heavy.xml
Mods/HMC weapon pack – USSR/Defs/ThingDefs_Weapons/Weapons_Rifles.xml

1 fixed 9x39 SH ammo (ignored any armor value). Now penetration based on RHA armor value;
2 some weapon tag and cost fixes.
1 поправлены 9х39 SH боеприпасы (игнорировали любую броню). Теперь бронепробитие зависит от значения брони в БКГ;
2 некоторые правки тегов и стоимости вооружения мода.

Lite update HMC weapon pack – USSR mod

---

Mods/Core_SK/Defs/Storyteller/Incidents_Map_Misc.xml
Mods/Core_SK/Defs/Storyteller/Incidents_SK_Events.xml
Mods/Core_SK/Royalty/Patches/IncidentDefs/IncidentPatch.xml
Mods/NPS_SK/Patches/incidents-patches.xml

[ENG]
1 added 200 day delay to "ProblemCauser" event (this a set of some mechanoid clusters or enemy base events with different dangerous buildings (like weather changer, psy suppressor and etc));
2 added more allowed biomes to alphabeavers events (+ added NPS biomes patch). Also expanded temperature range of this event;
3 very slightly expanded temperature range of "crop blight", "devourers of crops" and "psychic rain" events;
4 slightly decreased spawn chance of "caravan animals wander in", "battle animals wander in" and "colonist stash" events (~10-20%) (very high spawn frequency).
[RUS]
1 добавлена задержка в 200 дней для события "ProblemCauser" (это набор событий, состоящий из эвентов вида "пси-подавитель с кластером механоидов/вражеской базой появился рядом с вашим поселением и пока …

Some incedent tweaks and fixes

---

Mods/Core_SK/Royalty/Patches/QuestScriptDefs/QuestScriptDefsPatches.xml

Increased power points of Intro_Wimp quest (cuz HSK hasn't any weak animal with enable manhunting (except mosquito)).
Увеличено число очков угрозу у квеста Intro_Wimp (стартовый квест роялти с убегающей от утки/морской свинки/другого мелкого животного знатной персоны) (т.к. в ХСК не осталось ни одной безобидной зверушки, что могла бы преследовать эту самую знатную персону (кроме москитов)).

Increased power points of Intro_Wimp quest (cuz HSK hasn't any weak animal with enable manhunting (except mosquito))

---

Mods/Arachnophobia_SK/Defs/PawnKindDefs/ROMA_Spiders.xml
Mods/Arachnophobia_SK/Defs/PawnKindDefs/ROMA_SpidersGiant.xml
Mods/Arachnophobia_SK/Defs/PawnKindDefs/ROMA_SpidersQueen.xml

Added missed mass param to ROM spider pawns
Добавлена пропущенная масса у пауков из арахнофобии (было нулевое значение, из-за чего их нельзя было повесить на мясные крюки).

Added missed mass param to ROM spider pawns

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Arid.xml

Currently they're only vendorable to Royalty settlements, Orbital traders, and Animal trader caravans.
I can't figure out what else i need to change to make then as normal vendorable animals to any settlement on the map like Horses/Muffalo/Sheep etc.
If anyone has any idea tag me in discord and I can make the changes or someone else can.

Changed Dromedary trader tag from Uncommon to Common

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Giants.xml

1 corrected armor and armor penetration of some giant animal (like mamonth, elephant, megabadger and etc);
2 added missed thick leather hediff to mega badger and woolly rhinoceros;
3 added missed armor to megasloth;
4 enabled manhunting for megabagder and significant increased all battle params of him (the description says that he is very dangerous and should be avoided, but in fact, he is a rag...).
1 скорректирована броня и бронепробитие у некоторых гигантских животных (вроде мамонтов, мегабарсуков и т.д.);
2 добавлен пропущенный хедифф "Толстая кожа" для мегабарсука и шерстистого носорога;
3 добавлена пропущенная броня гигантскому ленивцу;
4 мегабарсук теперь может приходить в качестве агрессивного животного (не совсем понятно, почему запретили – мяса и шкур из него много не падает) + …

Some giant animals tweaks and fixes

---

Mods/SeedsPlease/Defs/ThingDefs/Items_Seeds_Base.xml

Add nutrition to seeds for chemfuel recipe work. also NeverForNutriton for not consuming
Добавил питательность для семян, чтобы можно было из них гнать биотопливо. Кушать их нельзя

Add nutrition to seeds

---

Mods/SeedsPlease/Defs/ThingDefs/Items_Seeds_Base.xml

Изменение категории еды для семян на "семяна", в надежде, что караваны не будут кушать их так активно

Change seeds food category for "seeds"

---

Mods/ArcaneTechnology_SK/Patches/Pawn/Pawns.xml

1 fixed Planetary Recon starting scenario (starting pawns couldn't wear some starting apparels);
2 added all Orion's and Syndicate's pawns ability to use any spacer items;
3 added some faction leader pawn ability to use any spacer items (most faction leaders often use equipment of a higher technological level than ordinary pawns of this faction). Pawn-leader and faction list:
**_Faction = Leader label_**:
Nova alliance = Nova commander;
Orassan enclave = Tactical commander;
Bloodmoon brotherhood = Brotherhood sentinel;
Church of violence = Sectarian sentinel;
Android enclave = Town councilman.
1 исправлен стартовый сценарий "Колонизация" (стартовые пешки не могли носить некоторую стартовую одежду);
2 всем пешкам фракции Корпорации Орион и Синдикат добавлена возможность носить и …

Some Arcane Technology tweaks and fixes

---

Mods/EnergyTab_SK/Languages/English/Keyed/Manager_Keyed.xml

Storage and consumption labels switched as it should be.

Fixed Energy Tab mismatch labels on English language

---

Mods/Core_SK/Defs/Storyteller/Incidents_SK_Events.xml

Changed Enemy ship event letter def from simple negative event to big threat (visual only, replaced color from yellow to red).
Изменен параметр выпадающего письма для события "Вражеский десант" с обычного негативного события на "Большая угроза" (только визуальные изменения, жёлтый цвет заменен на красный).

Light Enemy ship event fixes

---

Mods/Infused_SK/Defs/InfusionDefs/IndustrialBoosted.xml

Some low tier insulation infusions had very low value (0.02 or 0.08). Corrected.
Некоторые низкоуровневые зачарования с бонусом к изоляции имели очень низкие значения (например, 0.08 градусов). Скорректировано. Весь раздел Industrial Boosted в целом имел очень низкие значения изоляции. Немного увеличены.

Corrected industrial insulation infusions value

---

Mods/Core_SK/Defs/FactionDefs/Factions_Mech.xml

After adding pikeman to mech raids in this commit https://github.com/skyarkhangel/Hardcore-SK/commit/2f776db0ac099c3f63fc04d6cbb5f86a211b482b balance shifted towards flimsy snipers. This should help correcting this.
После добавления драгунов в рейды механоидов в https://github.com/skyarkhangel/Hardcore-SK/commit/2f776db0ac099c3f63fc04d6cbb5f86a211b482b, баланс рейдов механоидов сильно сместился в сторону хлипких снайперов. Предлагаю немного скорректировать это и уменьшить общее кол-во снайперов в рейдах механоидов, где есть драгуны (драгуны тоже снайперы, к сведению).

Corrected mechanoid's raids

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml

It's allow use any wood planks (like bamboo or redwood) in recipe.
В рецепте строительства пассивных охладителей доски из обычного дерева заменены на примитивные компоненты.
Это позволит использовать любые доски (бамбук или красное дерево), а не только обыкновенные.

Replaced wood planks to primitive components in passive coolers

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Grenade/30x29mmGrenade.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Grenade/40x46mmGrenade.xml

1 corrected 30x29 and 40x46 mm grenades dmg param (too high dmg HE grenade(almost similar 90 mm shell). Reduced. Too low EMP dmg (need ~25 30x29 mm grenades to kill one centiped against 5-7 of HE grenades), slightly up dmg and radius).
1 скорректированы параметры 30x29 и 40x46 мм гранат (HE гранаты по мощности сопоставимы с 90 мм снарядами, урон уменьшен. У ЕМП гранат напротив, урон был слишком низкий (для убийства одной сентипеды требовалось около 25 ЕМП гранат, когда как HE гранат нужно было около 5-7 штук). Немного увеличен урон и радиус ЕМП гранат).

Lite 30x29 and 40x46 mm fixes

---

Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_WeaponComponents.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Futuristic_Charged.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Futuristic_Lasers.xml
Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Futuristic_Plazma.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Chargeblasters.xml

1 removed all basic metals from hi-tech weapon's components and weapon craft recipes;
2 added few sendust alloy to R6 Splitter craft recipe (to slightly increasing difficulty of craft this weapon compared R3);
3 slightly corrected R3 and R6 param (light boost R3 range and light nerf R6 accuracy (~5-10%)).
1 из рецептов всего хайтек вооружения (оружие + оружейные компоненты) удалены все базовые металлы, крафт немного перебалансирован (сплавов требуется меньше, но использовать, например, бронзу уже не выйдет);
2 добавлено немного альсифер сплава в рецепт R6 Splitter (чтобы немного усложнить его крафт в сравнении с менее эффективным R3, сейчас их крафт идентичен и отличается только кол-вом ресурсов);
3 немного скорректированы параметры R3 и R6 энерговинтовок (немного увеличена дальность …

Some hi-tech weapon craft tweaks and fixes

---

Mods/CyberneticOrganism_SK/Defs/Hediffs/Cyborg_hediffs.xml

Added missed armor penetration to outer blade and power arm. Also corrected dmg params.
Добавлено пропущенное бронепробитие для протезов "Встроенное лезвие" и "Силовая рука" (мод "Сybernetic organism SK"). Также немного скорректирован их урон.

Some cybernetic organism SK fixes

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_UniversalFermenter.xml

Из фильтра по умолчанию рецепта извлечения селитры из тел удалены колонисты игрока.

Removed colonist corpses from saltpeter pit's extracts nitre from body recipe's default filter settings

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/HediffDefs/Hediffs_AndroidLike.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/Laserbeam.xml
Mods/Skynet_SK/Defs/HediffDefs/Hediffs_AddedParts_Skynet.xml

1 corrected new laser params;
2 added missed armor penetration param to terminator's spike arm and jackhammer arm;
3 increased andriod pawn market value (6000->8000);
4 added missed administer mech serum healer recipe to android pawn.
1 скорректированы параметры новых лазеров;
2 добавлено пропущенное бронепробитие для терминаторских руки-молота и руки-шипа;
3 увеличена базовая рыночная стоимость андроидов с 6000 до 8000;
4 добавлен пропущенный рецепт возможности использования сыворотки исцеления на андроидов через операции.

Some alpha tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

- Torches only use kindling as their fuel (coz they take the closest item that is in the filter and adding them a complicated fuel system like for fire bowl would be an overdo)
- Fire bowls use SK fuel system with filters and search range to push their role as a lasting light source (and to retain some flexibility that torches were stripped of)

Small fueled lightning rework

---

Mods/Core_SK/Defs/StatDefs/Stats_Pawns_WorkGeneral_FishIndustry.xml
Mods/Core_SK/Defs/StatDefs/Stats_Pawns_WorkRecipes.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Items/Items_Tools.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Alloys_Hightech.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Alloys_Industrial.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Alloys_Medieval.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Ore.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Stuff.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Wood.xml

1 added to tailoring and smithing speed params dependence of сrafting skill (cuz 99,7% of all apparels craft and smithing craft recipes requires some сrafting skill);
2 removed A16-A17 capacity factors legacy from fishing and electronic crafting speed params (consciousness counts twice and pawns get twice bonus);
3 reduced tools base smithing factor (~20%) (120%->100% for hammer for example);
4 added base smithing factors to all resources (like other params);
5 deleted duplicate patches for wood log, steel alloy and jade in survival tools lite mod;
6 expanded saltpeter pit safe temperature from 10-30 to 5-35 (cuz it was similar with ideal temperature and didn't work at all).
1 для навыков шитья и ковки добавлена зависимость от навыка ремесла (т.к. 99,7% всех рецептов ковки и шитья требуют …

Stats, tools and saltpeter pit params update

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Orassan.xml
Mods/RatkinRaceHSK/Defs/HediffDefs/Hediffs_Local_AddedParts.xml
Mods/RatkinRaceHSK/Defs/PawnKindDef_Ratkin/PawnKinds_PlayerSK.xml
Mods/RatkinRaceHSK/Defs/RecipeDefs/Recipes_Surgery_Installations.xml
Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Weapon.xml
Mods/RatkinRaceHSK/Defs/Things_ItemDefs/Items_BodyParts.xml
Mods/RatkinRaceHSK/Patches/Bodies/Bodies_Ratkin.xml

1 removed ratkin bionic tail. Added ability to use other tails and claws in ratkin's surgery recipes (bionics and cybernetics too);
2 fixed armor penetration of advanced claws (very low value);
3 fixed ratkin shotgun stock (=blunt dmg) armor penetration (sharp -> blunt).
1 бионический хвост раткинов был упразднен. Добавлена возможность имплантировать раткинам все прочие хвосты и когти (в том числе бионические и кибернетические);
2 исправлено бронепробитие у продвинутых когтей (очень низкие значения);
3 исправлено бронепробитие в ближнем бою у дробовика раткинов (удар прикладом использовал не тот тип бронепробития).

Tails unification update

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml

Fixed embrasures incorrect displaying with wooden and stony materials (always looks like made from metal).
Исправлено некорректное отображение амбразур из деревянных и каменных материалов (всегда выглядели как сделанные из металла).

Fixed embrasures incorrect displaying with wooden and stony materials (always looks like made from metal)

---

Mods/NPS_SK/Defs/BiomeDefs/BiomeDef_NPS.xml

Replaced red mushroom to agave (forage food only) in wasteland and desert and salt fields biomes (cuz first one haven't nutrition value).
Красный гриб заменен на агаву в биомах пустошей и соляных полей (только добыча на глобальной карте) (т.к. красный гриб не имеет питательности и из-за этого караваны могут начать голодать).

NPS SK biomes forageability fixed

---

Mods/Core_SK/Defs/ThoughtDefs/Extratraits/Thoughts_Exotic.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThoughtDef/Thoughts_Exotic.xml
Mods/Core_SK/Patches/Thoughts_Situation_Special.xml

1 updated cultist trait base mood effect of psychic drones to last vanilla values;
2 fixed the bug that caused both negative and positive psychic drones effect to pawn with cultist trait at same time;
3 updated cultist trait eng and rus translations.
1 актуализировано влияние на настроение психических дронов на пешек с чертой "оккультизм" до последних значений ванильного римворлда;
2 исправлен баг, из-за которого пешка с чертой "оккультизм" получала положительный и отрицательный эффект от пси-дронов одновременно;
3 обновлены переводы черты характера "оккультизм".

Cultist trait update and fixes

---

Mods/Infused_SK/Defs/InfusionDefs/IndustrialBoosted.xml

It's gave offset instead of multiplier (for example +102% instead x1.02).
Был чистый бонус вместо множителя (т.е. +102%, а не х1.02)

Fixed research infuses bug

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/AsariRace/Defs/ThingDefs_Races/Races_Asari.xml
Mods/CombatExtended/Defs/Stats/Stats_Pawns_Combat.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/RatkinRaceHSK/Patches/ThingDefs_Races/Race_Rakinlike.xml

1 reduced unarmed damage bonus param scaling by 20%;
2 reduced base unarmed damage value by 1-2.
This changes should help reduce chance some strange melee weapon swaps caused by too high unarmed damage values on not high value of pawn melee skill.
1 уменьшено скалирование бонуса к урону без оружия от навыка ближнего боя на 20%;
2 уменьшен базовый урон без оружия на 1-2 единицы (в зависимости от изначального базового урона).
Изменения должны помочь исправить ситуации (или уменьшить их шанс), когда из-за слишком высокой скорости роста урона без оружия, пешки с невысоким навыком ближнего боя предпочитали использовать кулаки вместо холодного оружия.

Unarmed damage tweaks and fixes

---

Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml

It's should help preventing spawn ratkins without ears in raids.
Возвращены параметры litterSizeCurve и lifeStageAges без наследования. Должно помочь предотвратить появление раткинов без ушей в рейдах.

Returned litterSizeCurve and lifeStageAges param without inheriting

---

Mods/RatkinRaceHSK/Patches/Apparel_STL.xml

When trying use ratkin's backpacks.
Исправлен баг с отображением инвентаря CE при одновременно выключенном моде Survivle tools lite и использовании рюкзаков раткинов (thx Нея).

Fixed CE inventory bug when Survivle tools lite was disabled 

---

Mods/Arachnophobia_SK/Defs/BodyDefs/ROMA_Bodies.xml
Mods/Core_SK/Defs/Bodies/Bodies_QuadrupedAnimalWithHoovesAndAntlers.xml
Mods/Core_SK/Defs/Bodies/Bodies_QuadrupedWithPawsTailAndHeartGroup.xml
Mods/Core_SK/Patches/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithHoovesAndAntlers.xml

Fixed yellow alert "BodyDef *body name* has BodyPartRecord of *body part name* whose children have more or equal coverage than 100% (100.00% or more (need 99% or less))".
Исправлено жёлтое предупреждение вида "BodyDef *body name* has BodyPartRecord of *body part name* whose children have more or equal coverage than 100% (100.00% или больше)" (из-за некорректных патчей сумма превышала 99%).

Fixed BodyDef *body name* has BodyPartRecord of *body part name* whose children have more or equal coverage than 100% (100.00% or more)

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_Quarried.xml
Mods/Core_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_SK.xml

Восстановленную карьерную почву теперь нельзя разметить для посадок

Recultivated soil is no longer sowable without terraforming

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Temperate.xml
Mods/Core_SK/Defs/SK.ObjectsSpawnsDefs/ObjectsSpawnsDefs.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorCarpet.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorWood.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_Floors_SK.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_PrimitiveFloors.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Ore.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Parts.xml
Mods/Fences and Floors_SK/Defs/TerrainDefs/Terrain_Floors.xml
Mods/SeedsPlease/Defs/ThingDefs/Buildings_Production.xml

1 added missed marsh terrain type to temperate swamp biome;
2 replaced cairn's base stuff from granite to limestone (cuz granite is boring and op);
3 fixed an issue where some heavy structures and floors could be placed on top of weak soils and bridges;
4 added missed bricks appearance param to jade.
1 добавлен пропущенный болотный тип почвы в умеренный болотный биом;
2 базовый материал каирнов заменен на известняк (гранит приелся, даешь разнообразие!);
3 исправлена ошибка, из-за которой некоторые постройки и полы можно было ставить поверх слабых почв и мостов;
4 добавлен пропущенный параметр внешнего вида для нефрита.

Some terrain tweaks and fixes

---

Mods/Core_SK/Defs/TraitDefs/Expanded Traits.xml
Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml
Mods/Core_SK/Patches/TraitDefs_Core_Patch.xml

1 added missed required work tags and required work types to some traits (it could cause some strange situations when pawns had trait with cooking (for example) boost but couldn't cook (backstory restrictions and etc));
2 some commonality and meditation type param lite tweaks.
1 добавлены пропущенные теги и типы работ для некоторых черт характера (их отсутствие могло вызвать ситуации, когда, например, пешка получала черту характера с бонусом к готовке, но готовить не умела (запрет от предыстории, например));
2 некоторые небольшие правки частоты появления черт характера и разрешаемых типов медитации.

Some traits tweaks and fixes

---

ModsConfig.xml

disabled work rebalancer mod by default (cuz it has some tps impact from WorkRebalancer.Patches.CompEggLayer_CompTick_Patch:CompTick)
выключен мод work rebalancer по умолчанию (оказывает некоторое негативное воздействие на тпс из-за одного из патчей + используется в основном для тестов, обычному игроку он ни к чему)

disabled work rebalancer mod by default (cuz some tps impact from WorkRebalancer.Patches.CompEggLayer_CompTick_Patch:CompTick)

---

Mods/Infused_SK/Defs/InfusionDefs/IndustrialBoosted.xml
Mods/Infused_SK/Defs/InfusionDefs/MedievalAmplified.xml
Mods/Infused_SK/Defs/InfusionDefs/MedievalEnchanted.xml

1 decreased market value modifier of industrial infuses (~33%);
2 some infuses tweaks (mainly decreased bonuses to move speed, aiming delay, weapon cooldown and armor rating params. Also corrected some infuses with very high or low values).
1 уменьшен множитель стоимости для индустриальных модификаций (на ~33%);
2 некоторые корректировки модификаций (в основном были ослаблены бонусы на скорость бега, время прицеливания, время между атаками и рейтингом брони. Также скорректированы некоторые модификации ну прямо с очень высокими и низкими значениями).

Some infused tweaks and fixes

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Shell/120mmCannon.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Shell/90mmCannon.xml
Mods/Core_SK/Patches/Bodies/Bodies_Mechanoid/AdjustCentipedeRingsCoverage.xml

1 sligtly corrected centipeded coverages of fifth and sixth rings (the value was very high, which made the Sentipeda's butt more likely to hit than its front);
2 corrected 90 and 120 mm tank shells param. HE and HEAT ammo had non-correct params (HEAT had more explosive radius than HE and non-high direct hit damage, which contradicts its description. HE just had a low explosive radius and small amount of large fragments. Fixed).
1 немного скорректирована степень покрытия пятого и шестого колец гусеницы (сентипеды) (значения были немного завышенными и вероятность попасть по заду сентипеды была выше, чем по её переду);
2 скорректированы параметры 90 и 120 мм танковых снарядов. HE и HEAT имели некорректные параметры (у HEAT радиус взрыва больше, чем у HE, а урон при прямом попадании невысок, …

Some tank cannons and centipedes tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets.xml
Mods/HMC weapon pack – USSR/Defs/ThingDefs_Weapons/Weapons_Shotguns.xml

1 removed any chances to spawn pawn with turret's gun (pawns from other race mod (Revia race for example));
2 increased Toz-34 draw size (~25%) and reload time from 1.1 to 1.25 sec.
1 убрана возможность спавна пешек с орудиями от турелей (такое встречалось с пешками из других модов (например, Revia Race));
2 увеличены визуальные размеры дедушкиного ружья (на ~25%) и время перезарядки с 1.1 до 1.25 сек.

Some light tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Ship.xml

Cuz all spaceship parts requires ultra component research but all parts uses only spacer components to build (old research tree legacy):
Постройка всех деталей космического корабля теперь требует ультра компоненты вместо высокотехнологичных.
Связано с тем, что для постройки частей корабля требуется исследование ультра компонентов, но в самом корабле они почему-то не используются (наследие пред. дерева исследований).

Replaced spacer components to ultra one for all spaceship parts

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Basic.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Bionic.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Cybernetic.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Simple.xml

Исправлено бронепробитие протезов рук. Были слишком низкие значения.

Fixed arm's prosthesis armor penetration (very low value)

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Bionic.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Cybernetic.xml
Mods/Core_SK/Defs/ThingDefs_FishIndustry/Races_Animal_Fish.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Exotic.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Mechanoid.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_MechanoidZeon.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Mutant.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Blasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Chargeblasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Lasers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Launchers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Plasma.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Weapon.xml
Mods/Skynet_SK/Defs/ThingDefs/Races_Skynet.xml

1 fixed missed fishes meat amount (used base very high value);
2 added bionic and cybernetic eyes prostheses night vision efficiency bonus;
3 added some high tech weapon night vision efficiency bonus;
4 added night vision efficiency base value to mechanoid's, terminator's and some exotic animal's pawns.
1 добавлено пропущенное количество мяса для рыб (бралось завышенное базовое значение);
2 добавлен бонус эффективности ночного зрения для бионических и кибернетических глазных протезов;
3 добавлен бонус эффективности ночного зрения для некоторого высокотехнологичного оружия;
4 добавлен бонус эффективности ночного зрения для пешек механоидов, терминаторов, огров и некоторых экзотических животных.

Some night vision and fish tweaks and fixes

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/12x64mmCharged.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/15x65mmDiffusingCharged.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/6x24mmCharged.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/80x256mmFuelCell.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/9x44mmCharged.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/AmmoBases.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Pistols/45ACP.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/303British.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/762x39mmSoviet.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Shell/81mmMortar.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Art.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Medical.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Synthetic.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Medicine.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Chargeblasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Rifles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SMGs.xml
Mods/Core_SK/Patches/ThingSetMakerDefs/ThingSetMakers_RewardPatches.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Misc/Apparel_Psychic_Patch.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Misc/Weapons_Melee.xml

1 reduced eltex stuffs spawn chance as quests reward;
2 removed some non-using ammo from quest rewards;
3 removed some art from quest rewards (like potteries and urns);
4 removed medieval warhammer from quest rewards;
5 added few sets rewards as quest reward.
1 уменьшена вероятность появления предметов из эльтекса в качестве награды за задания;
2 убраны неиспользуемые игровым оружием боеприпасы из наград за выполнения заданий;
3 убраны некоторые произведения искусства из наград за выполнения заданий (урны и гончарные изделия);
4 удален средневековый боевой молот из наград за выполнения заданий;
5 добавлено несколько наборов в качестве награды за задания.

Some quests tweaks and fixes

---

Mods/CombatExtended/Languages/Russian/DefInjected/CombatExtended.AmmoSetDefs/Sets.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rocket/RPG7.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Launchers.xml
Mods/Dubs-Bad-Hygiene/Defs/DesignationSubCategoryDefs/SubCategories_dubs.xml

1 R3 Blast-Rocket Launcher now divide one RPG-7 shot to three smaller and weaker one (shooting with three rocket simultaneously);
2 fixed holy basin sub category.
1 Ракетница «Тройка» при выстреле разделяет один крупный снаряд на три меньших осколка (стреляет тремя ослабленными ракетами одновременно);
2 исправлено некорректное расположение священного стирального тазика с включенной гигиеной (возвращен в категорию "Разное").

Triple launcher tweaks

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Boots.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Fullarmor_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Fullarmor_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Gloves.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Kits.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_NightVision.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_SlaveOutfit.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Vests.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Ore.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Blasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Chargeblasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Lasers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Launchers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Plasma.xml
Mods/Core_SK/Ideology/Patches/ThingDefs_Misc/Apparel_Ideology.xml
Mods/Core_SK/Ideology/Patches/ThingDefs_Misc/Apparel_IdeologyHeadgear.xml
Mods/Core_SK/Ideology/Patches/ThingDefs_Misc/Race_Animal_Dryads.xml
Mods/Core_SK/Royalty/Patches/PawnKindDefs_Royalty/PawnKinds.xml

1 added some vanilla apparel and weapon tags to some apparel/weapon to make more compability with royalty and other mods;
2 fixed some non-working royality pawn's patches;
3 fixed dryad CE weird patches;
4 fixed 100% flammability of iron wall;
5 fixed incorrected ideology apparel's armour params.
1 добавлены некоторые ванильные теги для оружия и одежды для лучшей совместимости с Роялти и прочими модами;
2 исправлены неработающие патчи Роялти;
3 исправлены странные патчи СЕ для дриад;
4 исправлена 100% горючесть стен из железа;
5 исправлены завышенные значения брони одежды идеологии (пуленепробиваемая паранджа?).

Some pawns tweaks and fixes

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_PrepareFishes.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Special.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml

1 added missed carnivore and vegetarian meal recipes;
2 added bulk (x4) recipes for pelmeni, potatoes with cheese, coconut curry, mushroom madness, kebab, maki rolls, hearty stew, meat soup and grill cheese sandwich to professional cook stove;
3 replace fine meal to carnivore fine meal in grill fish recipes;
4 added all fish types to grill fish recipes (notes: some fishes gives more benefit if you use its in grill fish recipe immediately instead of butchering and cook carnivore fine meal afterwards);
5 fixed grill fish x4 (bulk) recipe inability using various fish corpses at once.
1 добавлены пропущенные рецепты мясных и вегетарианских блюд;
2 добавлены x4 рецепты для пельменей, картофеля с сыром, кокосового карри, грибного безумия, кебаба, маки роллов, домашнего рагу, мясного супа и …

Some cooking tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Carabines.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Heavy.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Rifles.xml

Добавлены ванильные оружейные теги для некоторого ХСК вооружения (для большей совместимости с некоторыми модами и DLC).

Added vanilla weapon tags to some HSK weapon (for more compatibility with some mods and DLCs)

---

Mods/CombatExtended/Defs/HediffDefs/Hediffs_CE.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Arrows.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Bolts.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Darts.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml

1 decreased poison buildup speed from projectiles by ~25%;
2 increased darts, posion arrows and posion bolts posion dmg from 1 to 3 but decreased physical damage by 2 (posion arrows and bolts only);
3 added new CE textures to arrow's and bolt's projectiles to all arrows and bolts types;
4 some bows and crossbows param and tags light tweaks and fixes.
1 уменьшена скорость накопления яда от снарядов на ~25%;
2 ядовитый урон дротиков, ядовитых стрел и ядовитых болтов увеличен c 1 до 3, но уменьшен физический урон на 2 ед. (только у ядовитых стрел и болтов);
3 добавлены новые текстуры для стрел и болтов из СЕ для каждого типа стрел и болтов;
4 некоторые небольшие правки параметров и тегов луков и арбалетов.

Some bow, arrow, bolts, poison tweaks and fixes

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Extracts.xml

Removes the biocoded weapon filters from the list of hidden filters so that the player can set smelting bills to target biocoded weapons specifically.

Un-hide biocoded filter for smelting weapons

---

Mods/Minerals/Patches/01_HardcoreSK/HardcoreSK.xml

Patch 'Stone-Rocky dirt' and 'Stone-Topsoil' terraforming buildings so that they work on the Basalt, Claystone, and Mudstone terrains added in Minerals mod. Thanks to Spaniard for helping me out with getting the xpath working.

Update Minerals mod patch to include terraforming patch

---

Mods/CombatExtended/Defs/DamageDefs/Damages_LocalInjury.xml
Mods/Core_SK/Defs/DamageDefs/Damages_LocalInjury_SK.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Insectoids.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Kingdom.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Norbal.xml
Mods/Core_SK/Defs/Storyteller/Incidents_Map_Threats.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Hive.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Base.xml
Mods/Core_SK/Patches/DamageDef_Patch.xml

1 removed some duplicate damage's multipliers for plants and buildings. Some of them moved to damage defs;
2 corrected building damage factor of impassable buildings to 1.2 HSK values;
3 added missed hive's arrows damage multiplier (like bullets one);
4 disable duplicate manhunter pack event;
5 increased earliest raid days of kingdom faction (20->30 days), norbal faction (0->15 days) (to prevent early siege raids spam) and insectoids (0->15 days) (cuz arriving only one antises).
1 удалены некоторые дублирующие множители урона по растениям и постройкам. Некоторые из них перемещены в настройки урона для их корректного отображения в игре;
2 скорректированы некоторые значения множителей урона (частично откатил до значений из 1.2, т.к. в ваниле 1.3 появились подмножители, которые не …

Removed some duplicate damage's multipliers and some tweaks and fixes

---

ModsConfig.xml

Mod by default does unexpected things and many players are confused. Moreover, even after explaining people prefer to turn this off.

Removed toggleable overlays from default modsconfig

---

Mods/Core_SK/Defs/ThingCategoryDefs/ThingCategories_SK.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_CookingSupplies.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fungi.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Vegetables.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingCategoryDef/Categories_SK.xml

- All fungi related edibles are now in "Fungi" category
- Champignon are now recognized by ideology as fungi
- Giant leaves are no longe considered fungi
-------
- Все съедобные грибы теперь в категории "грибы"
- Шампиньоны теперь корректно распознаются идеалогией
- Гигантские листья теперь не считаются грибами

New category for fungi

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_PrepareFishes.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Bakery.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Special.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Drinks.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_CookingSupplies.xml
Mods/Core_SK/Patches/MealsRemover.xml

- Removed separate vanilla meat/veg meals as similar system already exists in HSK
- Lowered cost of some foods to make them a bit easier to but from traders
- Integrated recent fungi category into existing recipes
- small tea fix 50%->5% rest need reduction
-------
- Убрал ванильные веганские/мясные блюда т.к. дублируют функционал ХСК (+ идиотские рецепты)
- Снизил стоимость большинства еды чтобы её было проще покупать у торговцев
- Внедрил недавно добавленную категорию "грибы" в существующие рецепты
- Небольшой фикс чая 50%->5% снижения усталости

Food update

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Security.xml

+The mortar is lot more accurate than before, so no shell falling 60 tiles off of the target
+Aim mode is added
+Reinstallable/minifiable, so you can buy it from traders and move it to other place or your stockpile
+Reduced mass and bulk
*Now they are Stealable

Mortar Fix/Update for 1.3 Dev Branch

---

Mods/Core_SK/Ideology/Patches/ThingDefs_Buildings/Buildings_Ideo.xml

Increased power draw (400W -> 1500W) and build cost of Neural Supercharger in favour of reduced cooldown (24h -> 4h) so Transhumanist colonies don't need to build one for each colonist which takes a lot of space.

QoL changes for Neural Supercharger

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Drinks.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml

1 added simple tea's and psychite tea's recipes to campfire and stoves (cuz its available with almost first neolothic researches). Removed ones from coffee machine;
2 added bulk version tea's and psychite tea's recipes to coffee machine.
1 добавлены простые рецепты чая и психинового чая костру и плитам (т.к. по исследованиям они открываются чуть не в самом начале неолита), но удалены у кофе машины;
2 добавлены оптовые версии рецептов чая и психинового чая для кофе машины.

Tea update

---

Mods/Core_SK/Defs/FactionDefs/Factions_Brotherhood.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Orion.xml

mustStartOneEnemy don't work on 1.3 ver.
naturalColonyGoodwill was removed on 1.3 ver.
Added new 1.3 ver. naturalEnemy property

Fixed non-hostile relation of Bloodmoon brotherhood and Orion Corporaion factions

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

Изменил количество дров для постройки (было 40).
На обычный факел тратится всего 10, а тут в 4 раза больше.
Возможно конечно что всё ради баланса :) Если так, извиняюсь что отнял время.

Изменен рецепт настенного факела

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/30x64mmFuelCell.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/6x24mmCharged.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/BlasterBolt.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/Laserbeam.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/PlasmaBolt.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Grenade/40x46mmGrenade.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/HighCaliber/14.5x114mmSoviet.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/HighCaliber/50BMG.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Pistols/9x19mmPara.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/556x45mmNATO.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Rifle/762x51mmNATO.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Shotgun/12Gauge.xml
Mods/Core_SK/Patches/ThingSetMakerDefs/ThingSetMakers_RewardPatches.xml

1 slightly reduced Royalty apparel items spawn chance as quest reward;
2 slightly increased non-Royalty item spawn chance as quest reward;
3 added new quest rewards sub-blocks with ammo to diversify types of entire ammo block rewards.
1 немного уменьшена вероятность выпадения Royalty предметов одежды в качестве награды за квесты;
2 немного увеличена вероятность выпадения прочих предметов в качестве награды за квесты (кроме Royalty);
3 добавлены новые подблоки наград с боеприпасами для увеличения разнообразия выдаваемых во всем блоке боеприпасов.

Some quest's rewards tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Launchers.xml

Changed Heavy Missile System ParentName from "BaseArtilleryGun" to "BaseGun_Turret", should fix the weird trajectory issue(no change for accuracy)
Guess not many people use them

Heavy Missile System Fix

---

Mods/CombatExtended/About/About.xml

This is for better compatibility with new patches for HSK. The old list is now pointless because all patches were deleted from CE.

Updated old loadAfter list

---

Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Items/Items_Tools.xml

Added Patch operation to sledgehammer that makes it a tool for constuction works with Survival toold hardcore mode allowing pawns to build. + removes notification that pawn needs a constuction tool if pawn has a sledgehammer.
Changed Construction speed multiplayer to 1.2 so it is like wrench but Monkeywrench is also a Smithing tool.

Pull Request, sledgehammer is now a tool

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/PlasmaBolt.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/PlasmaPelletBolt.xml
Mods/Core_SK/Defs/DamageDefs/Damages_LocalInjury_SK.xml

Updated the damage type plasma ammo when detonating (from simple flame to plasma dmg type with plasma visual and sound effects). Also increased the base plasma damage from 3 to 10 (like flame damage. Default damage is only used when detonating plasma ammo)
Обновлен тип урона при детонации плазменных боеприпасов (был обычный огненный, теперь плазменный с соответствующими визуальными и звуковыми эффектами). Также увеличен базовый урон плазмы с 3 до 10 (до уровня огненного урона. Базовый используется только при детонации плазменных боеприпасов)

Update plasma ammo explosive dmg type from flame to plasma

---

Mods/Core_SK/Ideology/Patches/ThingDefs_Misc/Apparel_IdeologyHeadgear.xml

1 slightly reduced stuff armor multiplier for textiles headgear (~8-9%);
2 added some tribal tags to some textiles headgear (many of them haven't any apparel tag).
1 немного снижен множитель брони для текстильных головных уборов идеологии (~на 8-9%);
2 добавлены некоторые теги племенных фракций для некоторых текстильных головных уборов идеологии (большинство вообще не имеет каких-либо тегов).

Some ideology headgear tweaks and fixes

---

Mods/Core_SK/Languages/Russian/DefInjected/GameConditionDef/GameConditions_SK.xml
Mods/Core_SK/Languages/Russian/DefInjected/IncidentDef/Incidents_SK_Events.xml

Скорректирован перевод события Wild fire ("дикий огонь" заменен на более корректный и понятный "лесной пожар", также скорректировано его описание).

Fixed Wild fire rus translation

---

Mods/Core_SK/Defs/HediffDefs/HediffDefs_Diseases.xml

- Lowered threshold for diseases to become visible - hidden diseases only make sense with communicable diseases because player still gets notification, but has to use workarounds to tuck pawns in beds. Questionable mechanic, but hopefully will be a pain in the ass without too big of a mechanical hinderance.
- Covid causes Pneumonia at later stages of disease (caused it only at earlier stages before) - treat your pawns quickly.

Diseases tweaks

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

Исправлено завышенное значение защиты деревянного щита раткинов

Fixed overvalued ratkin wooden shield armor params

---

Mods/MultiLang Colorful Traits/Defs/ColorBase.xml

Changed terrible (red) and unique (purple) traits color to little more readable on dark blue background:
- before:
- after:
Цвет ужасных (красных) и уникальных (фиолетовых) черт характера сделан более читабельным на темно-синем фоне (выше пример "До" и "После" соответственно).

Changed terrible (red) and unique (purple) traits color to more readable on dark blue background

---

Mods/Core_SK/Ideology/Patches/AlienRace/Removing_AlienCannibalism.xml

It does not work well due to the unification of humanoid meat (all races have the same human meat, which is why the principle does not work for people and works strangely with aliens in some places (you can have both a penalty and a buff for eating humanoid flesh at the same time)). I suggest removing this until a suitable solution is found. Compatible with existing saves
Временное отключение плохо работающих принципов и мемов "Пожирание пришельцев".
Плохо работают из-за унификации гуманоидного мяса (все расы имеют одинаковое человеческое мясо, из-за чего принцип не работает для людей и местами странно работает с пришельцами (можно одновременно иметь и штраф и баф за поедание плоти гуманоида)). Предлагаю удалить их пока не будет найдено подходящее решение проблемы. Совместимо с …

Temporary removing badly working alien eating precepts and memes

---

ModsConfig.xml

Forgot to add it back into the default ModsConfig after fixing it

Add Pick Up And Haul back into ModsConfig load order

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/AlienRace/AlienRace_Droids.xml

Relating to issue: https://github.com/TheLoneTec/Hardcore-SK/issues/17
Cannot blacklist melanin genes, otherwise graphical errors will occur.

Invisible Androids fix

---

Mods/Core_SK/Defs/ThingDefs/Projectile_Dragon.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Exotic.xml

- Nerfed them slightly.
At some point this needs switching from the custom SK projectile to the ProjectileCE_Bursting class. It essentially does what the custom class does, it will then have support for suppression and other CE mechanics.

Dragon Projectile Balance.

---

Mods/Core_SK/Biotech/Patches/Scenarios/Scenario.xml

Replaced iron ore to steel.
Added few resources for build some starting mechanitor buildings.
Added few ammo for one of the mech (mechanitor scenario).
Железная руда заменена на стальной сплав.
Для сценария механитора добавлено немного ресурсов, необходимых для постройки некоторых стартовых построек. Также добавлено немного боеприпасов для одного из стартовых механоидов механитора.

Updated biotech scenario's starting resources

---

Mods/CombatExtended/Patches/Core/DamageDefs/Damages_LocalInjury.xml

Cuz this param used only by terminator suicide dmg and non HSK items (from other mods for example. Should increase other mods compatability)
https://github.com/skyarkhangel/Hardcore-SK/commit/a384c8f1fc1cb87818fa6e66c732a9d463ad5bd3

Revert default Bomb param

---

Mods/AsariRace/Defs/FactionDefs/Factions_Asari.xml
Mods/AsariRace/Defs/FactionDefs/Factions_Player.xml
Mods/AsariRace/Defs/PawnKindDefs_Humanlikes/PawnKinds_Asari.xml
Mods/AsariRace/Defs/PawnKindDefs_Humanlikes/PawnKinds_AsariWanderers.xml
Mods/AsariRace/Defs/PawnKindDefs_Humanlikes/PawnKinds_Player.xml
Mods/Better Pawn Control/About/About.xml
Mods/SeedsPlease/Defs/RecipeDefs/Recipes_Plants_CoreSK.xml
Mods/SeedsPlease/Defs/ThingDefs/Items_Seeds_Core.xml
Mods/SeedsPlease/Defs_OnDemand/ludeon.rimworld.ideology/Seeds.xml

- Added biotech checks for xenotypes
- Moved Tinctoria Seeds and recipes to Core (no longer Ideology)
- BPC and EL are currently incompatible with each other, added to incompatible list in About.xml

Asari and Seeds Please DLC Checks, Better Pawn Control and Extended Loadout are incomatible with each other

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Mutant.xml

Should prevent said error from popping:
```
Could not do PostLoadInit on RimWorld.Pawn_TrainingTracker: System.NullReferenceException: Object reference not set to an instance of an object
at (wrapper dynamic-method) RimWorld.Pawn_TrainingTracker.RimWorld.Pawn_TrainingTracker.CanAssignToTrain_Patch1(RimWorld.Pawn_TrainingTracker,RimWorld.TrainableDef,bool&)
at RimWorld.Pawn_TrainingTracker.CanAssignToTrain (RimWorld.TrainableDef td) [0x00000] in <95de19971c5d40878d8742747904cdcd>:0 
at Verse.BackCompatibility.PawnTrainingTrackerPostLoadInit (RimWorld.Pawn_TrainingTracker tracker, Verse.DefMap`2[RimWorld.TrainableDef,System.Boolean]& wantedTrainables, Verse.DefMap`2[RimWorld.TrainableDef,System.Int32]& steps, Verse.DefMap`2[RimWorld.TrainableDef,System.Boolean]& learned) [0x00082] in …
```

Set Ogre's trainability to None

---

Mods/Rimatomics_SK/Defs/RecipeDefs/Recipes_Production.xml

Fixed rimatomic's smelt turbine blades recipe (dropped iron ore instead of titanium)
Исправлен рецепт на переплавку лопастей турбин (вместо титана выпадала железная руда)

Fixed rimatomic's smelt turbine blades recipe

---

Mods/Core_SK/Biotech/Defs/ThingDef_Races/Races_Mechanoids_Medium.xml

As well as other comps that may be useful.
Notice that currently Apocriton says "Sabot" instead of "Toxic", but it can only use toxic needle. (Still, normally player cannot have Aporciton as colony mech)

Fix Scorcher and Apocriton missing inventory 

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Medical.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Medicine.xml

Added bulk recipes for bandages.
changed rot time for all medicines to be shorter(make sure you put them way  now)
Added long rot timer to industrial medicine.
All meds  have had their deterioration outside tripled(glitter tech is magic so its untouched)
Added some plastic to  glitter and industrial meds.

 The  leave no meds outside update

---

Mods/Core_SK/Biotech/Defs/ThingDef_Races/Races_Mechanoids_Light.xml
Mods/Core_SK/Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Light.xml

- Non-combat mech's armor needs to be manually repaired. It no longer regenerates by itself;
- Reduced minimal armor percentage of light mech

Fix cleansweeper has duplicate armor comp

---

Mods/CombatExtended/Defs/Stats/Stats_Apparel.xml
Mods/Core_SK/Defs/StatDefs/Stats_Apparel.xml

Heat & Electric armor no longer exceed 100%.
100% raw value provides 80% protection, but higher value provides significantly less armor

Ambient Armor Rework

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml

Now it actually follows some loose logic where buildings that are >=3 cells are no movable, but with a few exceptions.

Standardized minifiability of the buildings

---

Mods/Core_SK/Patches/BackstoryDefs/Backstories.xml

Removed backstories with firearms - having additional firearms both in hands of enemies and player can throw off flow of the game. Also removed backstories with spoilable stuff like meat and organs (why would anyone bring a slab of meat into a cryocapsule and how is it not spoiled?). Replaced Sun lamp with potato seeds (were we crushlanded or is it organized colonization already?)

Adjusted pawns' backstories

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_CatGroup.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_DogGroup.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Hyena.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_WildCanines.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Wolfs.xml

Allows them to use Rocketman performance optimization, but they will stop using nanite shields (hopefully I will modernize it later)

Remove ShieldPawn class from animals

---

Mods/Rimatomics_SK/Defs/ThingDefs_Buildings/Buildings_G_HSK.xml

Don't want to be such a party breaker - it is very much open for debate. But what was the idea behind giving them heat emission? Mechanical parts heating up from friction? But we have a lot of other heavy machinery that can do that as well, and the numbers are also insane (I don't think we have anything that can heat up to 1500C)

Removed heat generation from centrifuges

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Alloys.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Natural.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Extracted.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Ore.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Radioactive.xml
Mods/Minerals/Defs/ThingsDefs_Fossils/Fossils.xml
Mods/Minerals/Patches/01_HardcoreSK/Research.xml

- Ore smelting conversion rate is almost universally 1 to 1 now, with exception for some alloys that exist in parent ores in very small quantites (like cobalt in nickel).
- More streamlined ore stacking - now most ores are stored in stacks of 600 (more of a QOL than persuit of realism)
- Coal doesn't spoil outside (maybe there was some intention behind it, but better make it more clear next time)
- Ore and alloy prices are normalized with main changes: coldstone, glowstone, wolframite and ilmenite ores are not as ridiculously expensive now (I swear, some ores were almost more expensive than their respective alloys). Still can bloat your colony wealth, but less deadly. Carbon alloy is now also more in line with other materials.
- Fossil buildings now boost for more and also affect …

Ore-some changes to ores and alloys

---

Mods/Core_SK/Biotech/Defs/Factions/Factions_Misc.xml
Mods/Core_SK/Biotech/Patches/Factions/Factions_Patch.xml

Added missed earliestRaidDays param to all Biotech factions (based on the HSK factions and taking into account the xenotype of the pawns).
The fierce neanderthal tribe faction no longer replaces the regular fierce tribe faction to avoid the lack of raiders in the first 30 days of the game and a smoother increase in difficulty during the same period.
Добавлены пропущенные параметры earliestRaidDays (мин. кол-во дней с момента старта колонии, которое должно пройти для возможности рейдов этих фракций) для всех фракций Биотеха (значения основаны на фракциях ХСК, с учетом ксенотипов пешек этих фракций).
Фракция враждебного племени неандертальцев более не заменяет обычную фракцию враждебного племени во избежание отсутствия рейдов в первые 30 дней игры и более плавного нарастания сложности в …

Fixed missed earliestRaidDays (Biotech factions)

---

Mods/Core_SK/Biotech/Defs/ThingDef_Races/Races_Mechanoids_Light.xml
Mods/Core_SK/Biotech/Defs/ThingDef_Races/Races_Mechanoids_Medium.xml

Fixed incorrect cost (combatPower) of some biotech mech-s (was cheaper than crawler)
P.S. It’s probably worth reconsidering the cost of all mechanoids (especially the crawler), in my opinion the values are too high in some places, but for now let it be so.
Исправлена некорректная стоимость (combatPower) некоторых механоидов Biotech (стоили дешевле краба).
P.S. Вероятно стоит пересмотреть стоимость всех механоидов (особенно краба), по-моему значения местами завышены, но пока пусть будет так.

Fixed incorrect cost (combatPower) of some biotech mech-s

---

Mods/Core_SK/Biotech/Patches/RecipeDefs/Mechinator.xml
Mods/Core_SK/Biotech/Patches/Research/Research.xml
Mods/Core_SK/Biotech/Patches/Scenarios/Scenario.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ScenarioDefs/ScenariosPatch.xml

1 starting set of Mechanitor's resources, researches and items has been revised to be more consistent with his backstory and to eliminate cases where it is impossible to create mechanoids at the start of the game;
2 all lightweight mechanoids are now available for creation from the very beginning of the game in this scenario;
1 пересмотрен набор стартовых ресурсов, исследований и предметов механитора для большего соответствия его предыстории и исключения случаев невозможности создавать механоидов на старте игры;
2 все легковесные механоиды теперь доступны для создания в самом начале игры на этом сценарии.

Update Mechanitor Scenario and Mechtech researches

---

Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Ameiro.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Animu.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Diane.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Extended.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Jaffa.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Kantai.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Lolidrop.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Lovely.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_NB.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Norbal.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Piggy.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_RS.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_SPS.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Smoothawk.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Spikes.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Vanilla.xml
Mods/Core_SK/Defs/Misc/HairDefs/Hairs_Xeva.xml

Added missing hair length tags for hairstyles to work correctly with xenogenes of the same name.
Добавлены пропущенные теги длины волос для причесок для корректной работы с одноименными ксеногенами.

Added missing hair length tags

---

Mods/CombatExtended/Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

Disabled combat drugs for tribals patch. Tribal pawns already has berserker herb. This patch is redundant.
Отключен излишний патч СЕ на добавление случайных боевых наркотиков некоторым племенным пешкам (у них уже есть берсерк трава, доп. рандомные стимуляторы излишни).

Disabled combat drugs for tribals patch.

---

Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/Expanded Traits.xml

Renamed Fragile trait in the russian localization, because it duplicated the vanilla Delicate trait.
Переименовал черту "Хрупкость" на "Ломкость" в русской локализации, т.к. в ваниле появилась одноименная черта.

Renamed Fragile trait in the russian localization

---

Mods/AsariRace/Defs/PawnKindDefs_Humanlikes/PawnKinds_Asari.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Feral.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Syndicate.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Feral.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Norbals.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_NovaAlliance.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Orassan.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Syndicate.xml
Mods/RatkinRaceHSK/Defs/PawnKindDef_Ratkin/PawnKinds_Player.xml

An attempt to fix incorrect pawn spawning in the classic scenario by removing redundant xenotypes of raid faction pawns part 1 (and I hope last). These changes do not affect raiders generation.
Попытка исправить некорректное появление пешек в классическом сценарии путем удаления лишних ксенотипов пешек рейдовых фракций, часть 1 (и надеюсь, последняя). Эти изменения не затрагивают генерацию рейдеров

An attempt to fix incorrect pawn spawning in the classic scenario

---

Mods/Core_SK/Patches/CombatExtended/Ammo/Grenade/30x29mmGrenade.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Grenade/40x46mmGrenade.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/HighCaliber/14.5x114mmSoviet.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/HighCaliber/50BMG.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Rifle/303British.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Rifle/556x45mmNATO.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Rifle/762x39mmSoviet.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Rifle/762x51mmNATO.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Shotgun/12Gauge.xml

Updated intermediate, rifle, large-caliber, grenade and shotgun ammunition (some values were not transferred during the CE update and are now greatly reduced, I corrected this).
Дообновлены промежуточные, винтовочные, крупнокалиберные боеприпасы, гранаты и боеприпасы для дробовика (часть значений не были перенесены при обновлении СЕ и сейчас сильно снижены, поправил это).

Updated intermediate, rifle, large-caliber and shotgun ammunition

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Wood.xml
Mods/SurvivalToolsLite/Patches/Core_SK/ThingDefs_Resources/Items_Resource_Wood.xml

Removed CombatExtended.ToolCE and tools patch from all planks. Its have not equippable compClass and can break slave and prisoner AI and a significant drop in TPS (see discord link).
Also added missed verb to bamboo (bamboo could not be equipped as a weapon).
https://discord.com/channels/272340793174392832/272924909649395712/1225454217175629905
Удален CombatExtended.ToolCE и патч инструментов для всех видов досок. У них нет подходящего для этого compClass, что может привести к поломке ИИ рабов и заключенных и значительной просадке тпса (см. по ссылке дискорда).
Добавлен пропущенный verb обычному бамбуку (без него бамбук нельзя было использовать в качестве оружия).

Removed CombatExtended.ToolCE and tools patch from all planks

---

Mods/MultiLang Colorful Traits/Defs/Mod_Core.xml
Mods/MultiLang Colorful Traits/Defs/Mod_SK.xml

1 added missed color to biotech traits;
2 some tweaks with color of some traits (some colors are no longer relevant, for example, traits for psychosensitivity);
3 deleted duplucate traits;
4 fixed wrong translations.
1 добавлены пропущенные цвета чертам характера из Biotech;
2 некоторые перестановки цвета у некоторых черт характера (части из них цвет был выставлен до появления DLC и на текущий момент неактуален, например, черты на психочувствительность).
3 удалены дублирующиеся черты;
4 исправлена локализация в комментах.

MultiLang Colorful Traits mod update

---

Mods/CyberneticOrganism_SK/Defs/ThingDefs_Items/Items_Exotic.xml

All CONN Comps already destroy itself after doing effect, the `CompProperties_UseEffectDestroySelf` in base def is redundant

Fix CONN items erroring after use

---

Mods/HMC Biomes/Defs/ThingDefs_Resources/Items_Resource_Crops_CookingSupplies.xml

Increased stack limit from 75 to 300 (like corn and rice).
Увеличен размер стака с 75 до 300 (как у кукурузы и риса).

Update Raw buckwheat stack limit (HMC Biomes)

---

Mods/Androids/Defs/AlienRaceSettings/AlienRaceSettings.xml
Mods/CombatExtended/Languages/Russian/DefInjected/DamageDef/Damages_LocalInjury.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Bolts.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Neolitic.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Neolithic/Arrows.xml

Eng:
- Added missed CE arrows patches (some arrows had greatly reduced damage and armor penetration. For example recurve bow had significant less damage and penetration than short bow).
- Rebalanced venom bolts to better match other venom projectiles (like venom arrows) (increased venom damage and sharp penetration, decreased non-venom damage and blunt penetration).
- Fixed some medieval and neolitic helmet body part groups and layers covering (for example Nasal Helmet now cover Nose, all helmets with chainmail aventail now also covers a neck and so on) (https://discord.com/channels/272340793174392832/1213150642634489937).
- Fixed Chitin Head Garment crafting recipe and null armor param (added 14 leathery stuff categories to recipe (without a type of material, a helmet cannot have …

Updated Androids, Combat Extended and Core SK mods

---

Mods/Core_SK/Royalty/Patches/VariousPatches.xml

Added antidotes to the list of exceptions to the restrictions of the dishes of titled pawns upon request at the link below.
Добавил антидоты в список исключений ограничений блюд титулованных пешек по запросу по ссылке ниже.
https://discord.com/channels/272340793174392832/1224011503435386963

Antidotes are untied from the pawn royal title

---

Mods/Core_SK/Biotech/Defs/Factions/Factions_Misc.xml
Mods/Core_SK/Languages/Russian/DefInjected/ExpansionDef/ExpansionDefs.xml
Mods/Core_SK/Languages/Russian/DefInjected/RiverDef/RiverDefs.xml
Mods/Core_SK/Patches/ExpansionDef.xml

ENG:
- Fixed UI bug due to which the HSK was considered official Rimworld content during the loading screen.
- Added missed pawns with M79 GL to pirate/outlander Biotech factions.
- Added missed almost a lake river type russian translation.
RUS:
- Исправлена ошибка UI, из-за которой HSK считался официальным контентом Rimworld во время экрана загрузки.
- Добавлены пропущенные пешки с РГ M79 в пиратские/аутлендеровские фракции Biotech.
- Добавлен пропущенный перевод типу реки "Almost a lake".

Some UI and localization fixes №2

---

Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Tribal.xml

There is a small chance that PawnGenerator will fail to generate a Pawn with Tribal_ChiefMelee or Tribal_ChiefRanged PawnKindDef requested configuration.
It happens when game tries to generate Factions on a map so user might see empty map without any settlements (it depends how much user choose Factions on Create World screen).
Seems like Generator cannot find a correct Tribal backstory with Violent work tag after 120 retries so we must explicitly set Backstories (Adulthood category) filter to include a correct Spawn Category (that includes backstories with Violent requiredWorkTag).
Other PawnKindDef's might have the same issue and should be checked as well.

Fix PawnGenerator exception for Tribal PawnKindDef

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorMetallic.xml
Mods/Core_SK/Languages/Russian/DefInjected/ArchitectSense.DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_Floors_SK.xml

1 added some new metallic floors to fill gaps in "Metal floor III" and "Metal floor V" researches, its empty now (added: aluminium tile, melchior tile, stein tile for "Metal floor III" and titanium tile, beta poly tile for "Metal floor V");
2 fixed "Plate metal tile" sub category in russian translation.
1 добавлено несколько новых металлических полов, чтобы заполнить пробелы в исследованиях "Металлические покрытия III" и "Металлические покрытия V", сейчас они пусты (добавлены: алюминиевая плитка, мельхиоровая плитка, штейновая плитка для "Металлические покрытия III" и титановая плитка, бета-полимерная плитка для "Металлические покрытия V");
2 исправлено наименование категории с металлическими пластинами (сейчас она называется "Металлическая плитка", будет называться "Металлические …

Some metallic floors tweaks and fixes

---

Mods/Core_SK/Defs/FactionDefs/Factions_Tribe.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Tribal.xml
Mods/Core_SK/Languages/Russian/DefInjected/PawnKindDef/PawnKinds_Tribal.xml
Mods/Core_SK/Patches/CombatExtended/PawnKindDefs/PawnKinds_CE.xml

ENG:
1 Fixed a bug where the number of grenadiers in tribal faction raids was doubled.
2 Tribal factions have been given a small number of pawns with primitive incendiary grenades (the total number of grenadiers will still be less).
3 The cost of tribal pawns and the curves of dependence of tribal raids on the cost of the colony has been adjusted. Now they will correctly take into account the starting cost of the colony and the danger of tribal raids will gradually increase as the game progresses (now the game almost immediately dumps the entire available arsenal of tribal raids on the player).
4 Added missed tribal's pawns russian translations.
RUS
1 Исправлена ошибка, из-за которой количество гренадеров у рейдов племенных фракции удваивалось.
2 Племенным фракциям добавлено небольшое …

Some Tribal Faction tweaks and fixes

---

Mods/CoreTranslation/About/About.xml

Incorrect CoreTranslation load order breaks russian-sk language to properly load injected translations and apply necessary patches.
This mod should be loaded before any CoreTranslation.* mods.

Fix CoreTranslation mod load order

---

Mods/RT_Fuse/Languages/English/DefInjected/ResearchProjectDefs/ResearchProject_RTBasicFuses.xml
Mods/RT_Fuse/Languages/English/DefInjected/ResearchProjectDefs/ResearchProject_RTCircuitBreakers.xml
Mods/RT_Fuse/Languages/English/DefInjected/ThingDefs/Building_RTCircuitBreaker.xml
Mods/RT_Fuse/Languages/English/DefInjected/ThingDefs/Building_RTMakeshiftFuse.xml
Mods/RT_Fuse/Languages/German/DefInjected/ResearchProjectDefs/ResearchProject_RTBasicFuses.xml
Mods/RT_Fuse/Languages/German/DefInjected/ResearchProjectDefs/ResearchProject_RTCircuitBreakers.xml
Mods/RT_Fuse/Languages/German/DefInjected/ThingDefs/Building_RTCircuitBreaker.xml
Mods/RT_Fuse/Languages/German/DefInjected/ThingDefs/Building_RTMakeshiftFuse.xml

Fix discharge values for English and German locale.
Affected items: [Makeshift fuse, Circuit Breaker]
Issue description: 
[Issue-3925](https://github.com/skyarkhangel/Hardcore-SK/issues/3925)

RT_Fuse: Correct discharge values for Eng and Ger

---

Config/Mod_TechAdvancing_SettingController.xml

85% to advance a level is just too much.
- Right now Classic start has neolithic level which brings a variety of problems and I think it already has too many researches
- Having a bit lower requirement means players can skip most useless techs and not clog his building/recipe menues (for example snow techs are useless 90% of the time) and also help people with addons since they also add their own techs
Classic start has 79% of techs now which means they get nature shrines, but no landing markers for shuttles

lowered needed level to advance tech level

---

Mods/Core_SK/Languages/Russian/DefInjected/IncidentDef/Incidents_Map_Disease_SK.xml

`letterText` and `letterLabel` values are changed to match a vanilla description of diseases.
Also it will fix "cannot resolve {3} argument" error if ru translation is selected in game.

Fix ru translation for diseases.

---

Mods/DarkestNight_SK/Defs/GameConditionDefs/MapConditions_Darkest.xml
Mods/DarkestNight_SK/Defs/ThingDefs/Races_Darkest.xml
Mods/DarkestNight_SK/Patches/UpdateAnomalyEvents.xml
Mods/DarkestNight_SK/Patches/UpdateUnnaturalDarknessAnomalyEvent.xml

Small configuration changes to support new 1.5 pawn render system. Also forbid `Darkness` game condition if `UnnaturalDarkness` or `BloodRain` or `DeathPall` from Anomaly DLC is active (and vice versa).
**Main Darkest Night assembly is updated and available in hsk-source repo as PR.**

1.5 fixes for Darkest Night mod.

---

Mods/Core_SK/Patches/GeneDefs.xml

1. Gene description: "...They are totally immune to most normal illnesses."
2. HSK diseases are pretty normal illnesses.
Therefore, we add them to the gene's immunity list.

Add HSK diseases to Perfect Immunity gene

---

Mods/Core_SK/Royalty/Patches/ThingDefs_Misc/Apparel_Various.xml

Added back quality comp to Gun Links that got removed in 1.5.4241 which causes pawns unable to equip them if You restrict their outifts quality

Added back quality to Gun Links

---

Mods/Minerals/Defs/ThingDefs_Rocks/OresBase.xml

The base definition for the Minerals Weathered/Solid/Hewn ores includes a RoughGem drop with a chance of 0.01.
All custom minerals override this drop with the type of the ore (i.e WeatheredOreCopper has a mineableThing of Copper), but do not change the drop chance or the yield (Yield being 1, i.e it would drop 1 copper 1% of the time when destroyed), which leads to the UI displaying the main resource a second time, but with a low number. Such as WeatheredOreCopper showing "60 Copper, 0.01 Rough Gems, 0.01 Copper".
Changing the drop chance to 0 removes this extra readout, while having absolutely zero impact on gameplay as it was a drop of 1, 1% of the time.

Fixes duplicated resource readout when selecting ores

---

Mods/Core_SK/Patches/CombatExtended/ThingDefs_Races/Races_Mechanoid.xml

[ENG]
Fixed incorrect armor parameters for sentipedes (min armor was greater than base armor) and duplicated durability parameters for some mechanoids.
**Core_SK\Patches\CombatExtended\ThingDefs_Races** has mechanoid patches that are duplicated in **CombatExtended\Patches\Core\ThingDefs_Races**. 
I replaced "add" patches with "replace" patches and commented "Operation Class="PatchOperationConditional"" patches because it is already enabled in CE.
After making the changes it looks like this:
[RUS]
Исправлены некорректные значения брони у сентипед (минимальное значение брони было больше базового) и дублирование значений строк durability у некоторых механоидов (видно на первом и втором скриншотах выше).
В Core_SK были дубликаты патчей CE, произведена замена add на replace, закомментированы …

Fixed incorrect armor parameters for sentipedes and duplicated durability parameters for some mechanoids

---

Mods/Dubs-Bad-Hygiene/Defs/ThingDefs_Buildings/BuildingsD_WaterManagement.xml

I suggest replacing 200 wood log in the water tower recipe with 200 costStuffCount, since wood logs is not found in every biome.
Предлагаю заменить 200 ед. древесины в рецепте водонапорной башни на 200 ед. costStuffCount, т.к. чистая древесина встречается не в каждом биоме.

Tweaks water tower (Корректировка водонапорной башни)

---

Mods/AsariRace/Defs/FactionDefs/Factions_Player.xml
Mods/Core_SK/Defs/FactionDefs/Factions_Player.xml
Mods/Core_SK/Defs/Misc/ResearchProjectTagDefs/ResearchProjectTagDefs.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Animal.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Apparel.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Buildings.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Craft.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Floors.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Food.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Medicine.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Plants.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Terraforming.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Weapon.xml
Mods/Core_SK/Patches/ResearchTree/DubsBadHygiene.xml
Mods/Core_SK/Patches/ResearchTree/NewRatkinPlus.xml
Mods/RatkinRaceHSK/Defs/Scenario/RK_Scenarios.xml
Mods/RatkinRaceHSK/Patches/ResearchPatch.xml

[ENG]
1 Adjusted starting research set for the Ratkin scenario. It has not changed since they were added (including when the ResearchTree_SK research tree was added).
2 Norbal, Nova and Azari starting scenarios have been given their own starting research set (based on their scenario description, starting items, starting animals and technology level). 
Currently almost all starting scenarios have the same starting research set based on the classic scenario (except for the Norbals - it uses the tribal research set). I propose making these changes to add a little variety between the starting scenarios.
[RUS]
1 Скорректирован стартовый набор исследований для сценария Раткинов. Он не менялся с момента их добавления (включая добавление дерева исследований ResearchTree_SK).
2 Стартовым сценариям …

Some starting research tweaks and fixes

---

Mods/Core_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_Floors_SK.xml

This commit https://github.com/skyarkhangel/Hardcore-SK/commit/33f590253d1f50d94b67f76787893b9e0ab06751 forgot to rename one of the floor types.

Fix SteinTile russian translation

---

Mods/Androids/Defs/AlienRaceSettings/AlienRaceSettings.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Heavy.xml
Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml
Mods/Core_SK/Patches/CombatExtended/ThingDefs_Buildings/Buildings_Security.xml
Mods/Core_SK/Patches/Core/FactionDefs/Factions_Misc.xml

- 1) fixed phenomenally high accuracy of 81mm mortar;
- 2) fixed spawn of mechanoid faction (could attack in first year of colony);
- 3) removed the minimum attack radius of the ballista (I still haven't found the reason why it was added at all, and why it was so huge);
- 4) for better readability, replaced multiple 10% penalties to different work speeds with a 10% penalty to global work speed for the perfectionist trait.
- 1) исправлена феноменально высокая точность 81 мм миномета;
- 2) исправлен спавн фракции механоидов (могли напасть в первый год колонии);
- 3) удален минимальный радиус атаки у баллисты (так и не нашел причину, зачем он вообще был добавлен, да и ещё и такой огромный);
- 4) для лучшей читабельности, заменил множественные штрафы в 10% к разным скоростям работы на 10% …

another CE patches tweaks & fixes

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Arrow_Explosive.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Ballista.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Bolts.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/CatapultaBalls.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Darts.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Pillum.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Grenades.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/AmmoBases.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Neolithic/Arrows.xml
Mods/Core_SK/Patches/CombatExtended/ThingDefs_Weapons/Weapons_Grenades.xml

Some suppression tweaks & fixes:
- reduced significantly inflated suppression multipliers for primitive projectiles and grenades;
- the armor penetration value for some arrows has been rounded to tenths (it was rounded to hundredths).
Некоторые исправления и изменения параметров подавления:
- уменьшены значительно завышенные множители подавления для примитивных снарядов и гранат;
- округлено значение бронепробитие у некоторых стрел до десятых (было округление до сотых).

Some suppression tweaks & fixes
