skyarkhangel/Hardcore-SK

Mods/Core_SK/Defs/RecipeDefs/Recipes_Cremation.xml

Объем работы и количество пепла пропорционально сжигаемому предмету. Было странно получать от сжигания футболки столько же пепла, как и от сжигания тела или бревен

Баланс кремации

---

Mods/Core_SK/Defs/AdvancedResearchDefs/AdvancedResearch_Plants.xml
Mods/Core_SK/Defs/ThingDefs/Plants_Cultivated_SK.xml
Mods/SeedsPlease_SK/Defs/ThingDefs/Items_Seeds.xml
Mods/SeedsPlease_SK/Defs/ThingDefs/Plants_Cultivated_Seeds.xml

Гевея убрана с гидропоники и требует теперь те же технологии, что
фруктовые деревья
Так же исправлен баг с семенами

Исправление гевеи

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_ProstheticsCraft_SK.xml
Mods/Core_SK/Defs/ThingDefs/Items_Meals_SK.xml

тогда способ решения проблемы, подсказанный маской, но более логичный, чем у него.
кофе-чай не требуют морозилки для хранения, но теперь разлагаются на улице.
Также увеличил разложение курительных изделий, ибо 100 дней для сигаретки - это несколько многовато на мой взгляд

Deterioration meals

---

Mods/EdBInterface/Languages/Russian-SK/Keyed/EdBInterface.xml

Фикс перевода, не отображался пункт меню

translate fix

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_ProstheticsInstall_SK.xml

natural arm is installed to LeftArm/RightArm so prosthetic arm also should use the same place

fix for prosthetic arm

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Tech.xml

Bionics II had itself as a prerequisite. This fixes it so that Bionics I is the prerequisite.

Allow bionics II and bionics III to be researched

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Added accepted Fuel Types in desc

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml

Added power output for Corpse-fired Generator description.
Fix Capsule Reactor description, added power output.
Fix Antimatter Reactor power output description.

Added power output for some descriptions

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Повторил вот это https://github.com/skyarkhangel/Hardcore-SK/pull/87/files
Поменял названиями Tailor's Loom и Tailor's Workbench

Dev fix typos #87 by thadius856 

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml

Because Wind Turbines draw a constant output of watt currently
>From here : https://ludeon.com/forums/index.php?topic=12996.msg252639#msg252639

Wind Turbine : Change the CompPowerTrader to CompPowerPlantWind

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml

Solar panel not generating power - fix
Gause turbine description - fix
Gause turbine "placeworker" was as wind turbine - fix 
___
кстати говоря если построить гаус а потом накрыть все это дело крышей она будет продолжать работать...

Solar & gause turbine fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Primitive butcher table label fix

Primitive butcher table label fix

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Agro.xml
Mods/Core_SK/Defs/ThingDefs/Plants_Flowers_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

SK_FlowersI
Astralagus
Crocus
Dandelion
SK_FlowersII
Rose
Rosebay
Daylily
Delphini
На какое дерево технологий опираться? Они все разные...

Flowers fix

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Meals_SK.xml

Nutrition was being multiplied by 2100%. Proposed fix is a 29% improvement, which is more inline with other cooking recipes.

Fixed Dried Fruit critical imbalance

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml

- should fix 10 jobs in 10 ticks refueling problem when power plant off
- adjusted spaces
___
all credits here https://github.com/skyarkhangel/Hardcore-SK/issues/77

10 jobs in 10 ticks during refueling fix

---

Mods/Core_SK/Defs/ThingDefs_Items/Items_Resource_SK.xml

Wood Log maxstack 600 > 300
Bamboo Log maxstack 600 > 300
___
more info #129

Wooden logs stack reduce

---

Mods/Core_SK/Defs/HediffDefs/HediffDefs_SK.xml

- spiceA effect did not disappear fix
- spiceB effect did not disappear fix
- spiceB "fall" stage pawn killing fix
___
https://github.com/skyarkhangel/Hardcore-SK/issues/147

Spice must flow!

---

Mods/CombatRealism/Defs/BodyDefs/Bodies_Humanlike.xml

- should fix rib installation not listed

Ribs installation issue fix

---

Mods/Core_SK/Defs/ThingDefs_FishIndustry/Items_Luxury_FishIndustry.xml

Makes oyster to rot

---

Mods/Core_SK/Defs/ScenarioDefs/Scenarios_Classic_noncrash.xml
Mods/Core_SK/Defs/ScenarioDefs/Scenarios_Special_noncrash.xml

- two additional classic scenario (Prepare Carefully friendly)
___
костыли пока PC c CL не подружите

Two additional start scenario without crashlanding

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Added possibility to turn on\off ammo table

Flickable ammo table.

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

- Kiln description fix
- Ammo Crafting Table description electricity clarification

Description fix

---

Mods/Core_SK/Defs/ThingCategoryDefs/ThingCategories_SK.xml

Construction update fix :P

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Cloth.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Cremation.xml

- allows tanned leather be made from mixed leathers
- allows to burn mixed materials

Garbage free

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Cloth.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Resource_SK.xml

- no more tanned leather from tanned leather :O
- tanned leather now LEATHER
___
#166

Tanned leather fix

---

Mods/Core_SK/Defs/ThingDefs/Plants_Cultivated_SK.xml

Makes hay beds useful, and allow to feed herbivorous tamed animal.
По факту решает проблему с тем что до соломы запаришься ресерчиться и высаживать ее, а так можно хоть немного, но накоцать с кустов. Еще б кнопку отдельную для сбора травы, но я чот не понял как ее создать.

Allow to collect hay from grass

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml

- increased amount of HerbalMedicine 2 -> 8
- paraffin was replaced with ash
___
Заменил парафин на пепел, увеличил "стоимость". При игре за племя надо научиться перерабатывать нефть прежде чем делать самые простенькие медкиты, что есть немного странно.
https://github.com/skyarkhangel/Hardcore-SK/issues/180

Herbal meds rework

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

- added kibble recipe for TableButcherNeolithic
- formatting adjust
- added kibble recipe for TableButcher
- formatting adjust
___
https://github.com/skyarkhangel/Hardcore-SK/issues/211

Butcher table added kibble recipe

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Agro.xml

- removed mysterious draining pump from description
___
https://github.com/skyarkhangel/Hardcore-SK/issues/213

SK_SoilFertillizationI description fix

---

Mods/Core_SK/Defs/ThoughtDefs/Traits/Thoughts_Memory_Misc.xml

- fix receiving "I/We butchered human" for cannibals
___
https://ludeon.com/forums/index.php?topic=12996.msg260131#msg260131
Прагматизм в "I butchered human" добавлять не стал, имхо - лишнее.

Cannibal trait fix

---

Mods/Miscellaneous_Robots_Xtension/Defs/PawnKindDefs/AIRobot_PawnKinds.xml

- should fix cooking bot unable to spawn
___
как можно было удалить, я не пойму?

Cooking bot fix

---

Mods/Core/Defs/TraderKindDefs/TraderKinds_Caravan_Outlander.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Tech.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Chemical.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Extracted.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Orbital_ExoticTrader.xml
Mods/Core_SK/Languages/Russian-SK/Keyed/SN.xml
Mods/Miscellaneous_Robots/Defs/ThingDefs/AIRobot_Races.xml

Decreased cost of glowstone lamp;
Decreased trade cost of the glowstone;
Added glowstone to exotic caravan/orbital trader.
Minor description fix.

Decreased cost of glowstone lamp

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/LT_RedistHeat/Defs/ThingDefs/Buildings_Duct.xml
Mods/LT_RedistHeat/Defs/ThingDefs/Buildings_TempController.xml
Mods/LT_RedistHeat/Defs/ThingDefs/Buildings_Vent.xml

- should fix unable to place on metallic wall
- medium cooler texture fix #250 
___
Пинки, а давай переименуем стены? Отличная идея, Брейн. :)

Wall mounted heaters\coolers\vents fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Doors.xml

- should fix unable place FenceGate between Fences
___
#246

FenceGate fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml

- should fix collapsing GH
- max temp reduced to 25 (а то 80 не оче комфортно думаю)
___
поганы ссл все портил :(

Geothermal heater fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

- added "ticker"
- added Flicker button
- format adjusting
___
http://hardcore-sk.ru/threads/bagi-i-oshibki.18/page-122#post-10533

Hand Assembling Workbench fix

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_Floors_SK.xml

The description says it gives 3 beauty. I'm guessing the description was right, if not, then that should be changed instead.

Paved Tile fix

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Power.xml

Gramma fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

- changed "Production" to "Misc" button to fit with other research benches.

HiTechResearchBench

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Alcohol.xml

- added all repices from Brewery to ElectricBrewery

ElectricBrewery fix

---

Mods/QualityBuilder/Languages/English/Keyed/Keys.xml

QualityBuilder fix

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Security.xml

- changed techlevel to industrial
___
#274

Research fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

- added forbiddable buttons for Kiln and TableFurnace
- changed flickable to forbiddable for FueledSmithy
___
@skyarkhangel не проще сделать анимацию огонька при работе, как в SK.Building_WorkTable_HeatPushAdvanced с дымком сделано? Или новую кнопку которая работает одновременно как флик и форбид...

Added forbiddable buttons

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml

- neolithic goes first
- various regrouping
- format adjust
___
Можно сделать что бы слева в окошке отображалась инфа(какие материалы нужны) об обьекте при наведении? Иначе то нихера не понятно что нужно... только через хелп. 
И желательно авто группировку по доступности, а потом уже по списку. Иначе возникают проблемы, если в категории несколько пунктов и которые идут первые у тебя не изучены, то выбрать тот который ты изучил не получается.

Hotfix for SubCategory

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

- removed duplicated storage tab

Item_shelf fix

---

Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Agro.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Power.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_Soil.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Arid.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Farm.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Giants.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Chemical.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Electronics.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Parts.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Buildings_Power_SK.xml

Alpaca wool 140 > 60
Dromedary wool 100 > 80
Megatherium cost 2100 > 3600
Megatherium wildness 97 > 90
Megatherium wool 280 > 200
SyntheticAmmonia cost 25 > 15
Fuel Power Plant 2800W > 3500W
Coal Power Plant 2300W > 2000W
Mechanism cost 32 > 22
Components cost 10 > 30
Electric Component cost 100 > 80
Drill Head cost 65 > 200
Sand (floor) cost 40 > 3
NuclearPowerI 1500 > 1600
NuclearPowerII 1600 > 1800
NuclearPowerIII 1200 > 2000
CerealsI 130 > 150
CerealsII 350 > 250

Balance fix

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Turrets.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Security.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Crate.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Artillery.xml

- added power and caliber info for AI manned turrets
- fixed some misprints

Turrets description fix2

---

Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Snipers.xml

Weapon description self-fix

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml

- шо это за бля баланс 1 к 1. Куда СкХардкорНаздор смотрит?

Baked popato WFT?

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml

- "Hammer", "Pickaxe", "Handaxe" description fix
- https://github.com/skyarkhangel/Hardcore-SK/issues/320
___
- "Parapet" now not merge graphically with sandbags
- "Barbed Wire" description fix
- https://github.com/skyarkhangel/Hardcore-SK/issues/304

Minor fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Doors.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Walls.xml

- "Power Conduit", "Heavy Power Conduit", "Fence Gate", "Fence" and
"Saturated soil" now not blocking wind

Added "not block wind" to some structures

---

Mods/Core_SK/Defs/RecipeDefs_Prostheses/Recipes_ProsthesesInstall_Basic.xml

- removed research prerequisite for "Peg leg" and "Hook hand" installation.
___
а то этот стол не туда, не сюда

Neolithic prostheses fix

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/RecipeDefs_Prostheses/Recipes_ProsthesesInstall_Basic.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/WorkGiverDefs/WorkGivers_SK.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Buildings_Production.xml

- grammar fix #333 
____
- removed research prerequisite for "Wooden foot"
- removed "unusable" recipes from "primitive prostheses table"

Prostheses and grammar fix

---

Mods/Miscellaneous_MapGenerator/Defs/MapGeneratorBlueprintDefs/MapGeneratorBlueprints_Bathhouse.xml
Mods/Miscellaneous_MapGenerator/Defs/MapGeneratorBlueprintDefs/MapGeneratorBlueprints_MainRoom.xml
Mods/Miscellaneous_MapGenerator/Defs/MapGeneratorBlueprintDefs/MapGeneratorBlueprints_MirrorTowers.xml

- reworked some blueprints to comply with "SK.PlaceWorker_DoorFix"
- should fix #287
___
В теории если заспавнится удачно "поврежденная версия" у которой будет отсутствовать тайл перед дверью то баг останется.

Collapsing doors on pre-generated terrain fix

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml

https://github.com/skyarkhangel/Hardcore-SK/issues/340

Exception for insects

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml

https://github.com/skyarkhangel/Hardcore-SK/issues/340 fx

Exception for insects fx

---

Mods/Core_SK/Defs/WorkGiverDefs/WorkGivers_SK.xml

- increasing refuel priority (now goes before hauling)

Increasing refuel priority

---

Mods/The Walking Dead/Defs/ThingDefs/Races_Zombie.xml

- added missing operations
- fix #358

[Zombie mod] fix

---

Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Tree_SK.xml
Mods/SeedsPlease_SK/Defs/ThingDefs/Items_Seeds.xml

- added fertillity info for seeds (for special guys how unable to use
"HELP" tab)
- renamed "Wild banana tree" to "Wild coconut tree"

Seeds improvement

---

Mods/Core/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_AJO.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Doors.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Joy.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml

Add <tickerType>Normal</tickerType> tag on every things which require
power.
see issue: Work stations drawing full power when idle #100

Idle from/to full power consumption on electric things.

---

Mods/LT_RedistHeat/Defs/ThingDefs/Buildings_TempController.xml

Remove <passability>Impassable</passability> otherwise MediumCooler can't be built

Unable to build MediumCooler

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

0) All storage building now have quality. Where is my legendary chest?!
1) All storage buildings are now deconstructable
2) Added miniscule beauty amount to pot, barrel, chest and basket. Other storage buildings have it, so these should have it too.
2.5) Chest can now be made of precious metals
3) Updated and unified descriptions. Some of them were just plain wrong.

Misc storage cleanup

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture.xml

1) Hay bed and sleeping spots are now horrible for injured (low immunity gain speed, instead of default 100%)
2) Simple bed (SK_BedroomI) is now worse than Comfy bed (SK_BedroomII)
3) Low tier double beds are slightly worse
4) Slight ingridient adjustments (mostly components)
5) Pod bed is a bit more comfortable now

Beds rebalance:

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml
Mods/RT_Fuse_SK/Defs/ThingDefs/Building_RTCircuitBreaker.xml
Mods/RT_Fuse_SK/Languages/English/DefInjected/ThingDefs/Building_RTCircuitBreaker.xml
Mods/RT_Fuse_SK/Languages/Russian-SK/DefInjected/ResearchProjectDefs/ResearchProject_RTCircuitBreakers.xml
Mods/RT_Fuse_SK/Languages/Russian-SK/DefInjected/ThingDefs/Building_RTCircuitBreaker.xml
Mods/RT_QuantumStorage_SK/Defs/ResearchProjectDefs/ResearchProject_RTCircuitBreakers.xml

1) Circuit breaker buffed to support 2 fission batteries. right now its capacity  is mere 3000W -- just 500W more than makeshift fuse. It is build from super high-end ingredients, so current capacity is ridiculous.
2) Brought compQuality for hand axe, pickaxe and hammer to be in line with other tools.

Circuit breaker buff and quality for basic tools.

---

Mods/Core_SK/Defs/ThingDefs_CR/Projectiles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRifles.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Projectiles_SK.xml

Fixes in other files using "Bullet_9x39Soviet"

Addition to "patch-1"

---

Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Player.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Power.xml
Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Tech.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Tree_SK.xml

Commit1
Change SK_ElectronicsI prerequisite from electricity to power.
Change NuclearPower to only GroundPenetratingScanner
Change Battery prerequisite to SK_ElectronicsI only
Updated for WandererJoin
Fix PlantWildBanana tag
Commit2
Fix <apparelMoney> for Pawndef

Batch fixes

---

Mods/Core_SK/Defs/ThingCategoryDefs/ThingCategories_SK.xml
Mods/Core_SK/Defs/ThingDefs_BodyParts/Items_BodyParts.xml
Mods/Core_SK/Defs/ThingDefs_BodyParts/Items_BodyParts_Natural.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Medicine.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Raw.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Orbital_BulkGoodsTrader.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Orbital_Foodtrader.xml

Changes Category RawPlant (SK) to PlantMatter(Vanilla)
Fixes Duplicate Implant Listing
Fixes Body Part Natural Listing
Updates Items to use PlantMatter Category
Changes Traders from RawPlant to PlantMatter.

Storage Fixes

---

Mods/Core_SK/Defs/ThingCategoryDefs/ThingCategories_SK.xml

Remove Unused Rawplant

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Wolfs.xml

Fix wolf bite CD from [130] to [1.85]

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Mechanoid.xml

Centipede CD from 140 to 2.00

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml

Changing maxSimultaneous to match what the description declares.

Cooking tools fix

---

Mods/CombatRealism/Defs/ThingDefs_LoadoutGen/LoadoutGen_SK.xml
Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_CyberneticParts.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Asari.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_AsariWanderers.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Brotherhood.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Feral.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_NovaAlliance.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Orassan.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Player.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Predators.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Sectarian.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Syndicate.xml
Mods/Core_SK/Defs/RecipeDefs_Prostheses/Recipes_ProsthesesCraft_Cybernetics.xml
Mods/Core_SK/Defs/RecipeDefs_Prostheses/Recipes_ProsthesesInstall_Cybernetics.xml
Mods/Core_SK/Defs/ThingDefs_BodyParts/Items_BodyParts_Cybernetic.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Items_BodyParts_SK.xml
Mods/RedistHeat/Defs/ThingDefs/Buildings_Duct.xml
Mods/RedistHeat/Defs/ThingDefs/Buildings_TempController.xml
Mods/RedistHeat/Defs/ThingDefs/Buildings_Vent.xml

This should fix the shorthash issues.
Smoothwall references removed too.

ShortHash fix and SmoothWall references removed

---

Mods/Core/Defs/ThingDefs_Misc/Various_Stone.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Extracts.xml

These got overwritten. Here they are again.

Stone cutting fix (reupload)

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

Fixes the descriptions to match the stats. Most were off by 1.

Storage descriptions fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_AJO.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Art.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Doors.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Exotic.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Animal.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Joy.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Lighting_LED.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hydroponics.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Security.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Ship.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Tent.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Walls.xml

HCSK building labels are sometimes capitalized, sometimes not, inconsistent.
I went through and made them all the same. Based on vanilla core files, everything should be lowercase because capitalization is handled on-the-fly in the game.

Label consistency sweep

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Animal.xml

Description states it could it any animal, but it was set to size 1 max. Removed the limit.

Animal bed fix

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Boots.xml

Since HCSK no longer has socks, all footwear is on the foot's 3rd layer now. Specifying this in the description only serves to confuse players with useless information.
If you think socks and multi-layered footwear are going to return to HCSK, then disregard this pull request.

Update boot descriptions

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml

Disarm was using the wrong path

Fix razor wire trap

---

Mods/Core/Defs/RecipeDefs/Recipes_Food.xml

I think there was change at some point that changed this recipe to calculate on nutrition instead of simple item quality, maybe? Either that or it was fine before. Fixing...

Kibble fix (again)

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Mushrooms.xml

Mushrooms are not BasicPlantFoodRaw, so this recipe could use mushrooms. (#661)

Fix Pot Roast with Mushrooms recipe

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Cloth.xml

Chitin was missing stuff properties which caused anything made out of it to disappear. I came up with some numbers for it.

Fix chitin head garment

---

Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated_Manufacture.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Tree_SK.xml

forgot requiments for planting fruit trees fixed now

fruit trees

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Moderate.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated_Manufacture.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Tree_SK.xml

lower apple gen on temperate
modify fertility sensitivity of oat and wheat
fix not able to plant berry type plants
lowered coconut spawn in jungle

fix for berry planting

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Martens.xml

These small, cat-sized critters were dropping 75+ meat, more than pigs.

Fix body sizes for martens

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Livestock.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/RecipeDefs/Recipes_Meals.xml

I do not see any reason for keeping Silage craft in high tech Biorefinery

Make Silage now in TableButcher instead Biorefinery

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Medicals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Mushrooms.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Medicine.xml

Update to medicines,
Changes base medicines to better suit neolithic starts
fixes defNames

Sidfu's medical update

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Medicine.xml

Sidfu medicine

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Hand assembling workbench clarification

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Radioactive.xml

Skynet Cloak weight (27->15)
Remove radiation from unrefined Uranium Ore
Fixes outdoor buildings to not have penalty

Various small fixes

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Abstract.xml
README.md

removes abstract from prepare carefully

Leather 2.0 Hotfix

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Exotic.xml

Bandits with dragonleather underwear is less common

Fix leather rarity

---

Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_BasicProsthetics.xml
Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_Bionics.xml
Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_CyberneticParts.xml
Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_Orassan_Parts.xml
Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_SimpleProsthetics.xml

Fixes removal of sub-parts upon installation of arms, legs and exoskeleton prostheses.

Prostheses fix

---

Mods/Core/Languages/Russian-SK/Backstories/Backstories.xml

Часть перевода (черновой вариант). Спасибо Prosto Dray и Deornot за
помощь!

Russian translate "backstories"

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml

removed mine able on terraforming pump till issue with stop working when moved is fixed.
lowered mats and changed description to reflect changes

removed mineable on terraforming pump

---

Mods/Core_SK/Languages/Spanish/Keyed/SN.xml

Corrections

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Arid.xml
Mods/Core_SK/Defs/BiomeDefs/Biomes_Cold.xml
Mods/Core_SK/Defs/BiomeDefs/Biomes_Moderate.xml
Mods/Core_SK/Defs/HediffDefs/Hediff_Common.xml
Mods/Core_SK/Defs/IncidentDefs/Incidents_Disease_sk.xml

last of the diseases i wanted to add. should be plenty of variety now

the last diseases

---

Mods/ADogSaid-full A16/Defs/ThingDefs_Items/Items_UnfinishedAnimalPart.xml

removed the stuff category to fix item disappear bug

fixed unfinished for a dog said

---

Mods/Dubs_Bad_Hygiene_SK/Defs/ThingDefs_Buildings/Buildings_ceramic.xml

replaced worktomake with worktobuild so has acutaly build times.

ceramic build fix

---

Mods/Dubs Bad Hygiene/Defs/ThingDefs_Buildings/Buildings_Hygiene.xml

fix for radiator size and ui error

radiator fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

missed the entry on update now fixed

salt mine building def

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

option to allow a bit faster Pemmican production

---

Mods/Core_SK/Languages/German-SK/Keyed/Alerts_tech.txt
Mods/Core_SK/Languages/German-SK/Keyed/CCL.txt
Mods/Core_SK/Languages/German-SK/Keyed/CL.txt
Mods/Core_SK/Languages/German-SK/Keyed/Caveflora.txt
Mods/Core_SK/Languages/German-SK/Keyed/Changeres.txt
Mods/Core_SK/Languages/German-SK/Keyed/Container.txt
Mods/Core_SK/Languages/German-SK/Keyed/DermalRegenerator.txt
Mods/Core_SK/Languages/German-SK/Keyed/EnhancedCraftingUI.txt
Mods/Core_SK/Languages/German-SK/Keyed/FloatMenu_40K.txt
Mods/Core_SK/Languages/German-SK/Keyed/Furniture.txt
Mods/Core_SK/Languages/German-SK/Keyed/HungryAnimal.txt
Mods/Core_SK/Languages/German-SK/Keyed/IL_Misc_Gameplay.txt
Mods/Core_SK/Languages/German-SK/Keyed/LettersIncidents.txt
Mods/Core_SK/Languages/German-SK/Keyed/Ocean.txt
Mods/Core_SK/Languages/German-SK/Keyed/Outfitter_Keyed.txt
Mods/Core_SK/Languages/German-SK/Keyed/PlaceWorkers.txt
Mods/Core_SK/Languages/German-SK/Keyed/PowerSwitch.txt
Mods/Core_SK/Languages/German-SK/Keyed/Quarry.txt
Mods/Core_SK/Languages/German-SK/Keyed/SKkeyed.txt
Mods/Core_SK/Languages/German-SK/Keyed/SN.txt
Mods/Core_SK/Languages/German-SK/Keyed/SmartSpeedStrings.txt
Mods/Core_SK/Languages/German-SK/Keyed/TC_Misc_Gameplay.txt
Mods/Core_SK/Languages/German-SK/Keyed/TempGauge.txt
Mods/Core_SK/Languages/German-SK/Keyed/mushrooms.txt
Mods/Core_SK/Languages/German-SK/Keyed/repbench_Languages.txt
Mods/Core_SK/Languages/German-SK/Keyed/terraformer.txt

I have created some files in German for you to add to the mod.

German translation

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml

adds surival meal to be made on pro cook stove.
it expensive to make as lasts forever. will need tweaking in future. 
cost as much as 4 lavish meals so good balance

add survival meal that was missing

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Artillery.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Blasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Carabines.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Chargeblasters.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Grenades.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Heavy.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Lasers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Launchers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Mechanoid.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Ogre.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Pistols.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Plasma.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Railgun.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Rifles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SMGs.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Shotguns.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRifles.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_SniperRiflesAdvanced.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Heavy.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Launchers.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Machineguns.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Turrets_Sentry.xml

increased all ranged weapons accuracy, and increased sway and cooldown for most mechanoid weapons.

Higher ranged weapon accuracy + Mechanoid nerfs

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Alcohol.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Brewery.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml

Changed Jerky into a travel/light/emergency/long lasting food.
Changed Whisky recipe.

Changed Jerky + Whisky recipe

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Arid.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Bears.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Giants.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Horse.xml

Added carry variables to  the packanimal tagged pawns.

Pack animals load changes

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Synthetic.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml
Mods/Dubs Bad Hygiene/Defs/ThingDefs_Buildings/Buildings_Hygiene.xml
Mods/RedistHeat/Defs/ThingDefs/Buildings_TempController.xml

removed flickable from both non power grid stoves.
fixed tofu recipe.
renamed RH heater so it overrides the vanilla one.
added chairsearchradius to cover all ingestible defs, removing the need for table diner patch.

Fixes and stuff

---

Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Malaria.xml

malaria nerf

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Alcohol.xml

fix winemash recpie

---

Mods/ADogSaid_SK/Defs/RecipeDefs/Recipes_InjuryHeal.xml
Mods/ADogSaid_SK/Defs/RecipeDefs/Recipes_Surgery.xml
Mods/Core_SK/Languages/Korean-SK/DefInjected/Verse.ThingDef/Races_Spiders.xml
Mods/Core_SK/Languages/Korean-SK/DefInjected/Verse.ThingDef/animal_leather.txt
Mods/Core_SK/Languages/Korean-SK/DefInjected/Verse.ThingDef/animal_leather.xml

Fixes outdated Thing.Def handles

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Pistols.xml

added 1h to a few pistols so that more than 1 is avaible

Add 1h to a few pistols

---

Mods/Dubs Bad Hygiene/Defs/ThingDefs_Buildings/Buildings_Hygiene.xml

fix for missing itab for art and story

fix missing itab

---

Mods/Core_SK/Defs/RecipeDefs/Orassan/Recipies_Orassan.xml
Mods/Core_SK/Defs/RecipeDefs/Orassan/Recipies_Orassan_Surgery.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_AlcoholBarrel.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Alloys.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Ammo.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Cloth.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Components.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Cremation.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Electronics.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Extracts.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_HitechCraft.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Items.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Matter.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Misc.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Ocean.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Petrochemistry.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_PrepareFishes.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Production.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Turrets.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_saltmine.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Alcohol.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Bakery.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Canned.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Drinks.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Ingridients.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Medicals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Mushrooms.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_AlcoholCrates.xml

Recipe label updates

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Neolithic.xml

Решил тоже потестить возможности githuba в меру своих знаний.
Изменим урон от "club" , что бы булова не "резала", а таки тупой урон наносила.

Club теперь наносит blunt урон, вместо stab

---

Mods/Arachnophobia_SK/Languages/Russian-SK/DefInjected/ThingDefs/PawnKinds_Spiders.xml
Mods/Arachnophobia_SK/Languages/Russian-SK/DefInjected/ThingDefs/ROMA_EggFertBase.xml
Mods/CombatExtended/Languages/Russian-SK/DefInjected/CombatExtended.AmmoCategoryDefs/Cats.xml
Mods/CombatExtended/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_Grenades.xml
Mods/CombatExtended/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_Shells.xml
Mods/CombatExtended/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_Shotgun.xml
Mods/Core/Languages/Russian-SK/Backstories/Backstories.xml
Mods/Core/Languages/Russian-SK/DefInjected/BodyPartDef/BodyParts.xml
Mods/Core/Languages/Russian-SK/DefInjected/ThingDef/Races_Animal_Insect.xml
Mods/Core/Languages/Russian-SK/Keyed/Messages.xml
Mods/Core_SK/Defs/TraitDefs/Expanded Traits.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/RecipeDefs/Orassan/Recipies_Orassan.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/RecipeDefs/Recipes_ProstheticsCraft.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/RecipeDefs/Recipes_ProstheticsInstall.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDef/Garden Drugs.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_SK.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Buildings_Nov.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Items_BodyParts_SK.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Orassans/Orassan_BodyParts_Basic.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Weapons_Melee.xml
Mods/Core_SK/Languages/Russian-SK/DefInjected/TraitDefs/Traits.xml
Mods/Diseases overhauled/Languages/Russian-SK/DefInjected/HediffGiverSetDefs/HediffGiverSets.xml
Mods/PawnsAreCapable/Defs/TraitsDefs/Traits_Singular.xml
Mods/PawnsAreCapable/Languages/Russian-SK/DefInjected/ThoughtDef/PAC_Thoughts_Situation_Traits.xml

В этот раз я нацелился работу с трейтами и русификацию оснащения, но как это обычно бывает, одно цепляется за другое.
Changes to be committed:
modified:   Mods/Arachnophobia_SK/Languages/Russian-SK/DefInjected/ThingDef/PawnKinds_Spiders.xml
modified:   Mods/Arachnophobia_SK/Languages/Russian-SK/DefInjected/ThingDef/ROMA_EggFertBase.xml
-Коррекция перевода.
modified:   Mods/CombatExtended/Languages/Russian-SK/DefInjecte/CombatExtended.AmmoCategoryDefs/Cats.xml
modified:   Mods/CombatExtended/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_Grenades.xml
modified:   Mods/CombatExtended/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_Shells.xml
modified:   Mods/CombatExtended/Languages/Russian-SK/DefInjected/ThingDefs/Ammo_Shotgun.xml
modified: …

 Trnslt add & fix request

---

Mods/Core/Languages/Russian-SK/Keyed/Dialogs_Various.xml

Из-за них сдвигался интерфейс и не было видно слайдера снятия с паузы на некоторых верстаках. fix #1166

Укоротил строки

---

Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Infused_CR/Defs/InfusionDefs/Suffixes.xml

I suppose PlantHarvestYield should be increased with this infusion

"of succes" infusion

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Terraforming.xml

Add Lichen covered dirt - soil terraforming.
Теперь лишайник можно превратить в обычную почву. Ранее с лишайником совсем ничего нельзя было сделать.

Add missing terraforming

---

Mods/Core_SK/Languages/Russian-SK/DefInjected/ThingDefs/Buildings_Security_SK.xml

Зашибись, основной файл по турелям кинуть забыл.

Hot add trnslt

---

Mods/Core/Defs/Stats/Stats_Basics_General.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

add MaxHitPoints to material info

MaxHitPoints

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Exotic.xml

removed feenix heat bug

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml

added missing 	<li>InstallPainkillerRib</li>

added missing

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml

Added bow for Makezilla (and spaces between thingdefs to make easier to read.)

Add bow for Patreon

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Medicals.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_CookingSupplies.xml
Mods/Diseases overhauled/Defs/HediffDefs/HediffDefs_BrainDamage.xml
Mods/Diseases overhauled/Defs/HediffDefs/HediffDefs_InduceComa.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Global_Malnutrition.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Coma.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Group_Parasites.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Group_TraumaSavant.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_HepatitisK.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Hyperthyroidism.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Hypothyroidism.xml
Mods/Diseases overhauled/Defs/HediffDefs/Hediffs_Local_Migraine.xml

add option to use yeast for antibotic
fix raw fungus use
fix hungerrate for disease mod

varous fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml

change <fillPercent>0.7</fillPercent> to <fillPercent>0.99</fillPercent> so cooler shows on wall

fix cooler being inside wall instead of outside it

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml

removes Makzilla bow from crafting.

Makzilla Bow fix

---

Mods/NPS_SK/Defs/Pawns/Races_Animals.xml

change crab meat to be <useMeatFrom>ThingDefFishMashgon</useMeatFrom> otherwise it is insect meat due to animal classification

change crab meat to be useable

---

Mods/Holy Washer/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Holy Washer/Defs/RecipeDefs/Recipes_Misc.xml
Mods/Holy Washer/Defs/ResearchProjectDefs/HolyResearchProject.xml
Mods/Holy Washer/Defs/ThingDefs_Buildings/Buildings_Production_HollyWasher.xml
Mods/Holy Washer/Defs/WorkGiverDefs/washing_WorkGivers.xml
Mods/Holy Washer/Languages/Russian-SK/DefInjected/ArchitectSense.DesignationSubCategoryDefs/SubCategories.xml
Mods/Holy Washer/Languages/Russian-SK/DefInjected/RecipeDef/Recipes_Misc.xml
Mods/Holy Washer/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects.xml
Mods/Holy Washer/Languages/Russian-SK/DefInjected/ThingDef/Buildings_Production_HollyWasher.xml
Mods/Holy Washer/Languages/Russian-SK/DefInjected/WorkGiverDef/washing_WorkGivers.xml

При старте приложения в протокол фиксируется ошибка при расположении исследования в дереве:
Couldn't relax research project coordinates apart after 200 passes.
Verse.Log:Error(String)
Verse.ResearchProjectDef:GenerateNonOverlappingCoordinates()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()
При этом стиральная машина этого исследования не требует
Плюс поправил русификацию и объединил предметы в подкатегорию

Fix holy washer mod issues

---

Mods/Core_SK/Defs/Bodies/Bodies_Env.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Livestock.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Visitor_Neolithic.xml
Mods/Core_SK/Defs/TraderKindDefs/TraderKinds_Visitor_Outlander.xml

Снорки раньше не могли перемещаться. Добавил им ноги от кролика как временное решение.
Животные теперь едят кошачий корм не в последнюю очередь
У путников теперь есть на продажу товары, а серебра увы нет, так как тяжёлое.

Snorks can move

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Livestock.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Rodentlike.xml
Mods/Core_SK/Languages/English/Keyed/Main.xml

Хватить убивать котиков!!! 
+ фикс разделочного стола (маленького)

soft leather from chinchilla

---

Mods/Core/Languages/English/Keyed/Incidents.xml

"tinny" to "tiny" for Rag

---

Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Base.xml

remove restricction on growing fruit trees

fix fruit trees

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Terraforming.xml

Removed terrainaffordanceneeded which fixes terraforming various water type tiles.

Terraforming water tiles fix

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Stuff_Leather.xml

Corrected Elephant skin immunity gain

Minor bug fix

---

Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cave.xml

added the missing <harvestYield>5</harvestYield> to glowstool

missing harvest ammount

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Wood.xml

"wooden" уже занято обычным деревом.

stuffAdjective redwood

---

Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Medical.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Meals_SK.xml

A source of medical stuff for early game / Чтобы папуасы могли отрубать ноги и вставлять крюки

Crude bandage kits

---

Mods/Minerals/Defs/ThingDefs_Rocks/Sandstone.xml

Adding missing hit points for solid sandstone

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml

Fix barbed wire linking

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Accessories.xml

Wall and ceiling lights can now be placed under other buildings (benches, beds..). Fixed/Updated description.

Fix for electrical lights

---

Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml

fix empty description
fix hoe missing category

fix missing entries

---

Mods/Core_SK/Defs/ThingDefs_BodyParts/Items_BodyParts_Natural.xml

А то как-то не реалистично и вообще не хардкорно.

Порча органических органов вне холодильника

---

Mods/Core_SK/Defs/ThingDefs_BodyParts/Items_BodyParts_Natural.xml

Лог ругается. Я так понимаю, это нужно для количества проверок порчи.

Added tickerType to NaturalSK_BodyPartBase

---

Mods/Core/Defs/Drugs/Psychite_Tea.xml

Мне кажется странным, что его нельзя сделать на самой крутой плите, пусть хоть так пока.

Пси чай на кофеварку

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Shell/120mmCannon.xml
Mods/Dubs Bad Hygiene/Languages/Russian/DefInjected/JobDef/Jobs_Hygiene.xml
Mods/Dubs Bad Hygiene/Languages/Russian/DefInjected/WorkGiverDef/WorkGivers.xml
Mods/Dubs Bad Hygiene/Languages/Russian/Keyed/DubsHygiene.xml

Перевод и устранение ошибки перевода.

Правки перевода гигиены.

---

Mods/NPS_SK/Defs/ThingDefs_Races/Races_Animals.xml

Changed crabs and salamanders to drop raw meat. Same for snails with insect meat coz why it wasnt like that?

Small change to meat drops

---

Mods/Dubs Bad Hygiene/Defs/ThingDefs_Buildings/BuildingsE_Heating.xml

dubs hygiene fix for gas broiler temp

dubs hygine temp fix

---

Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/RCT_Traits.xml

Исправление трейта,который давал -33 переносимости боли,но при этом назывался "Стойкость". Теперь трейт называется "непереносимость боли"

Трейт "Стойкость"

---

Mods/MultiLang Colorful Traits/Defs/Mod_SK.xml

Добавление трейта "Непереносимость боли" в плохие

Красный трейт "Непереносимость боли"

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Shields.xml
Mods/ExpandedRoofing/Defs/Roofs.xml
Mods/ExpandedRoofing/Languages/Russian/DefInjected/RoofDef/Roofs.xml

Доработал покрытие частей тела щитами. Теперь если пешка стоит на месте и ничего не делает, то щиты покрывают бОльшую область, чем если пешка двигается или сражается.
Покрытие для разных щитов:
1) Баклер. В движении покрывает только левую кисть. В неподвижном положении голову и левую руку с плечом
2) Щит туземца. В движении полностью левую руку. В неподвижном левую руку, плечи, тело, голову
3) Средневековый щит. В движении левую руку и торс. В неподвижном все кроме ног.
4) Костяной щит. В движении левую руку с плечом, торс и шею. В неподвижном все, кроме ступней
5) Баллистический щит. Так же, как и костяной.

Доработал покрытие частей тела щитами. В целом, щиты ослаблены

---

Mods/Infused_SK/Languages/Russian/DefInjected/Infused.Def/IndustrialBoosted.xml

Перевел строки что оставались на английском.

Перевод infused_sk

---

Mods/Core_SK/Defs/Drugs/Smokeleaf.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Livestock.xml
Mods/Rimefeller_SK/Defs/RecipeDefs/Recipes_Production.xml

Keeping around primitive benches for just one useful recipe is kinda ugly.
joints to druglab
silage to kitchen table
rimefeller pipes to advanced fabrication bench

Added some lowtech but useful recipes to later tech benches.

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Grenade/40x46mmGrenade.xml
Mods/Core_SK/Defs/HediffDefs/Implants/HediffDefs_Lifesupport.xml
Mods/Core_SK/Defs/RecipeDefs_Prostheses/Recipes_ProsthesesInstall_Lifesupport.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml

Added ability to install Life Support as Stomach (called "Feeding Tube")

Add Stomach Life Support

---

Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Resource_Stuff_Leather.xml

Fix some misprint (шкупы -> шкуры)

Fix some misprint (шкупы -> шкуры)

---

Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Apparel_SK.xml

Fix misprint for respirator (рспиратор -> респиратор)

Fix misprint for respirator (рспиратор -> респиратор)

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Drinks.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Ingridients.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Livestock.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Mushrooms.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Drinks.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml

- Changed most meals to use nutrition values instead of flat ingredient counts.
- Increased nutrition of Fruit Drinks.
- Made Fruit Yogurts nurseable.
- Reduced preferability of Pemmican.

Meal & Nutrition adjustments

---

Mods/HMC weapon pack – USSR/About/About.xml

Rename mod name (deleting №1)

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource.xml

Someone forgot about horns in melee rebalance patch. Fix this.
Забыли про рога в ребаланс патче милишного оружия. Исправил это недоразумение :peka:.

Someone forgot about horn's in melee rebalance patch. Fix this.

---

Mods/CombatExtended/Defs/ThingDefs_Misc/Gas_Various.xml

Отмена блокировки турелей при задымлении, снижение штрафа к точности (костыль, пока не будет реализован штраф в зависимости от степени задымления).

Временный фикс турелей

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorBrick.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorCarpet.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorMetallic.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorStone.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorWood.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_Floors_SK.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_PrimitiveFloors.xml
Mods/NPS_SK/Defs/TerrainDefs/TerrainDef_NPS.xml
Mods/Rimefeller_SK/Defs/TerrainDefs/Terrain_Floors.xml

Изменен баланс полов. 
1. В рамках одного технологического уровня (исследования) полы в основном различаются по стилю, а не по характеристикам.
2. Различие по характеристикам в рамках одного уровня, может быть обусловлено стоимостью (по материалам и работе).
3. Изменены характеристики различных полов, чтобы привести их к единому виду.
4. В Римфеллер внесены изменения для соответствия с основными полами.
5. Стерильный линолеум теперь открывается технологией "Стерильные материалы".
6. Добавлен нефритовый пол, чтобы расширить применение этого ресурса.
Changed floor balance.
1. Within the framework of one technological level (research), floors generally differ in style and not in characteristics.
2. The difference in characteristics within the same level may be due to the cost (for materials …

Floor balance

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_Floors_SK.xml

Someone saw floor tile from REINFORCED concrete? :D
Исправил рецепт бетонной плитки. Кто-нибудь хоть раз видел плитку из ЖЕЛЕЗОбетона? :D

Fix Paved Tile recipe cost

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml

It was lesser than other races.
Поправил бронепробитие андроидов для рукопашных атак. Было меньше, чем у остальных рас.

Fix Androids melee armor penetration blunt

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Terraforming.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Terraforming.xml

Правка длины описаний, чтобы они влезали для кастомных шрифтов.

Some bugs fixes in description for shrinking text to tooltip size.

---

Mods/NPS_SK/Defs/ThingDefs/ThingDefs_Resources.xml

Delete duplicate Beauty statFactor param.
Удалил дублирующее значение красоты. Были значения 3 и 6. Оставил наибольшее.

Delete duplicate Beauty statFactor param.

---

Mods/HMC weapon pack – USSR/Defs/ThingDefs_Weapons/Weapons_Heavy.xml

Fix PKM GPMG weapon description.

Fix PKM GPMG weapon description.

---

Mods/Core_SK/Defs/Storyteller/Incidents_Map_Misc.xml

Return Thrumbo Passes
Вернул приход Трумбо

Return Thrumbo Passes

---

Mods/MultiLang Colorful Traits/Defs/Mod_Core.xml

Add missed core trait
Добавил пропущенные трейты из Core

Add missed core trait

---

Mods/CombatExtended/Defs/HediffDefs/Hediffs_CE.xml
Mods/CombatExtended/Languages/Russian/DefInjected/HediffDefs/Hediffs_CE.xml
Mods/Core_SK/Defs/HediffGiverSetDefs/HediffGiverSets_Diseases.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Neolitic.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Armor_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Boots.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Feral.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Fullarmor_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Fullarmor_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Fullarmor_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Neolitic.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Outlander.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs_Hightech.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Spacer.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_SlaveOutfit.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Special.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Vests.xml
Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml
Mods/Core_SK/Patches/HediffGiverSetChanges.xml

Some changes to new diseases system:
- added few germ resistance and germ containment param to all (almost) apparel;
- added germ resistance and germ containment param to some traits;
- some hightech helmets rebalance (delete "Mask" hediff from some hightech helmets/replaced on light version of it);
- some helmets had mask effect but not look like mask. Corrected it.
Небольшие изменения для новой системы болезней:
- почти всей одежде добавлено совсем небольшое количество "стерильности" и "устойчивости к болезням";
- некоторым чертам характера также добавил эти параметры;
- немного перебалансил все хайтек шлемы (и одну индустриальную тактическую тряпку) - для части шлемов эффект маски был удален или заменен на облегченную версию;
- часть шлемов давала эффект маски, но не выглядела как …

Some changes to new diseases system (1.1)

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/AlienRace/AlienRace_Droids.xml
Mods/Androids/Defs/ThingDefs/Apparel_Android.xml
Mods/Core_SK/Defs/HediffGiverSetDefs/HediffGiverSets_Diseases.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml
Mods/Core_SK/Patches/HediffGiverSetChanges.xml

- all races takes some germ resistance and germ containment base param;
- diseases now have different germ drop rate. Germ drop rate was slightly reduced;
- give germ resistance and germ containment to some stuff.
Некоторые правки для новой системы болезней (часть 2):
- всем расам выдан небольшой базовый бонус к сопротивлению болезням и стерильности;
- у болезней теперь разная частота распространения грязи и в среднем немного ниже, чем была раньше;
- добавил ещё некоторым предметам бонус к сопротивлению болезням и стерильности.

Some changes to new diseases update pt.2 (1.1):

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/AlienRace/AlienRace_Droids.xml
Mods/Core_SK/Defs/HediffGiverSetDefs/HediffGiverSets_Diseases.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/Core_SK/Defs/TraitDefs/RCT_Traits.xml
Mods/Core_SK/Patches/HediffGiverSetChanges.xml

- all races takes some germ resistance and germ containment base param;
- diseases now have different germ drop rate. Germ drop rate was slightly reduced;
- give germ resistance and germ containment to some stuff.
Некоторые правки для новой системы болезней (часть 2):
- всем расам выдан небольшой базовый бонус к сопротивлению болезням и стерильности;
- у болезней теперь разная частота распространения грязи и в среднем немного ниже, чем была раньше;
- добавил ещё некоторым предметам бонус к сопротивлению болезням и стерильности.

Some changes to new diseases update pt.2 (1.0):

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

Fix Ratkin backpacks appearance in inventory.
Исправил отображение рюкзаков Раткинов в инвентаре.

Fix Ratkin backpacks appearance in inventory.

---

Mods/RatkinRaceHSK/Languages/Russian/DefInjected/ThingDef/RK_Apparel.xml

Fix rus translation

---

Mods/Core_SK/Defs/HediffGiverSetDefs/HediffGiverSets_Diseases.xml
Mods/Core_SK/Patches/HediffGiverSetChanges.xml

Some conclusions after testing:
- filth from disease has some influence to performance (very noticeable in large colonies with 15+ pawns);
- even in vanilla rimworld it's very dangerous thing with good medicine start.
Некоторые выводы после тестирования:
- грязь от болезней влияет на производительность (причем очень заметно, если пешек 15+);
- даже в ванильной римке с хорошим стартом (в плане медицины) мод на распространение болезней довольно опасен.
P.S. на текущий момент в относительно развитых колониях эта система неплохо так влияет на фпс, создавая 1000 единиц грязи буквально на глазах... заставлять всех пешек убираться тоже не выход - будут лагать уже пешки :D
P.S.S. хотя бы на 1.0 стоит принять эти правки, грязь никуда не пропадает, грязь никуда не пропадает.

Some small changes to new disease system (1.0)

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

Some ratkin glasses changes.
Некоторые изменения для очков раткинов.
(может хоть здесь найдется место непробиваемому стеклу...)

Some ratkin glasses changes

---

Mods/SeedsPlease/Languages/Russian/DefInjected/RecipeDef/Recipes_Plants_CoreSK.xml

Fix extract seed tree bamboo translation.
P.S. Интересно, откуда там взялся хмель?

Fix extract seed tree bamboo translation

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ThingDef/Buildings_Natural.xml

Fix russian translation to iron ore.

Fix russian translation to iron ore.

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Components.xml

Fix wooden components recipe filter.
Исправлен рецепт крафта деревянных компонентов. Материалы и фильтр имели разные категории.
Спасибо Vuursteen и GuardianDll за заметку.

Fix wooden components recipe filter.

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RaidStrategyDef/RaidStrategies.xml

Добавил небольшую дифференциацию. В описании в любом случае есть вся информация, но так хотя бы станет чуточку разнообразнее и немного удобнее.

Rus translation update

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ThingDef/Buildings_Furniture.xml

У нас оказывается два спальных мешка - один при этом выглядит как кровать и имеет забавное несоответствие реальных и описанных характеристик (особенно порадовало про "легкость" "спального мешка" (который на самом деле выглядит как кровать). Исправил. Обычную кровать назвал "удобной" (т.к. она и правда имеет высокую удобность в параметрах).

Rus translation update to beds

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Beds.xml

Swapped ImmunityGainSpeedFactor param. Bedroll it's cheap bed version. Why it's give more immunity bonus?
Поменял местали бонус к иммунитету у кровати и удобной кровати (спального мешка и кровати). Более дешевая версия почему-то имеет больший бонус к иммунитету.

Some fix to beds

---

Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml

Забыли подправить flammability раткинов
https://github.com/skyarkhangel/Hardcore-SK/commit/00694b3e338dbb4592875ff07b711237c89eccfb

Forgot fix ratkin flammability

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Components.xml

Fix mending kit recipe
Исправил рецепт ремонтного набора. Продвинутые компоненты открываются значительно позже ремонта.

Fix mending kit recipe

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Horse.xml

15? cool!
Исправил максимальную температуру шерстистой лошадки. 15 это как-то ну совсем странно)

woolly horse comfy temperature max fix

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Cold.xml

Terramorph max temperature fixes

---

Mods/Core_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_Floors_SK.xml

Удалил описание привлекательности у всех полов по следующим причинам:
1) не у всех полов прописана привлекательность в описании;
2) большое количество текста снижает производительность при создании блюпринтов для их строительства;
3) привлекательность дублируется в описании, значения при этом отличаются. Привлекательности, генерируемой игрой, достаточно:

Some rus translation fixes

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Archipelago.xml
Mods/Core_SK/Defs/BiomeDefs/Biomes_Warm.xml
Mods/Core_SK/Defs/BiomeDefs/Biomes_WarmArid.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Ingridients.xml

Tweaked a bit nutrition values for fruit trees. These decimals make no sense due to how recipes with nutrition work.
Reduced cost of cocnut milk 10 -> 2.3 to be in line with other milk + reduced shelf time 
Reduced spawn rate of coconut palms in all bioms except extreme desert (there were just too many of them)

Palm trees and coconut nuts

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Stuff_Leather.xml

does not match the description

Fix some leather insulation param

---

Mods/RatkinRaceHSK/Defs/ThingDefs_Races/RK_Animal.xml
Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Rotti.xml

Забыл добавить параметры массы (обоим), переносимого веса и объема (только хомяку) для королевского хомяка и Ротти.

Forgot to add mass, carry bulk and carry weight to king hamster and rottie

---

Mods/MineralsFrozen/Defs/ThingsDefs_Minerals/DynamicMinerals.xml

This was fixed, but the rollback put the bug back in.

Fix bug where ice and snow spawns destroy buildings

---

Mods/CombatExtended/Patches/Core/DamageDefs/Damages_LocalInjury.xml

See https://github.com/skyarkhangel/Hardcore-SK/pull/2343

Return fix bomb damage patch from 1.1. Blunt type broke it's

---

Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Weapons_SK.xml

Additional to https://github.com/skyarkhangel/Hardcore-SK/pull/2360/files

Forgot about recipe rus translation

---

Mods/CombatExtended/Defs/HediffDefs/Hediffs_CE.xml

Сыворотка исцеления снимала эффект противогаза. Убрал эту странность.

Remove healer mech serum and wearing gas mask interaction

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml

Исправил высоту костра. Была почти как у амбразуры (~ 1 метр).

Fixed campfire height param. It was almost like embrasure.

---

Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Production.xml

В одном месте называются компонентами, в другом - деталями. Неудобно искать. Да и множественное число непонятно откуда взялось в описании их рецепта (делаются по одной штучке).

Fixed weapon parts recipe russian translation

---

Mods/Core_SK/Defs/ThingDefs/Events_Meteors.xml

Make all meteorites unclaimable to avoid unplanned deconstruction

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml

Поправил рецепт создания пеммикана х4. Выгоднее было делать х1 (см. заявку ниже).
https://github.com/skyarkhangel/Hardcore-SK/issues/2391

Fix make pemmican x4

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Pawns_WorkRecipes.xml

https://github.com/skyarkhangel/Hardcore-SK/pull/2220

Fix general labor speed rus translation

---

Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Production.xml

Лаборатория бионики стала Верстаком кибернетики, как оно в оригинале 
Описание приведено с единому шаблону

Fix rus translate

---

Mods/Core_SK/Languages/Russian/DefInjected/HediffDef/Bodyparts/BodyParts_Cybernetic.xml

Пофиксил перевод кибернетического желудка. В игре был не переведен.

Cybernetic stomach rus translation fixes

---

Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Apparel_SK.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Accessories.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/RangedIndustrial.xml
Mods/Rimefeller_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_Floors.xml

изменил одинаковые названия для избежания путаницы

fix rus translation, the same name correction 

---

Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Food.xml
Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Meals.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Canned.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Temperature.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Special.xml
Mods/Core_SK/Defs/ThingDefs_Plants/Plants_Cultivated_Fruits.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml

Ok, problem: food preservation is kinda useless, coldstone is too good and extremely effective alternative to freezers.
Solution: 
- Changed early game preservation, meat jerkies and dried fruits no longer give debuff to mood
- Changed meat jerkies to be produced from usual and not salted meat
- Change numbers on drying racks, now production effficiency is about 90% (you get about 0.9 preserved nutrition for every 1.0 of raw products) 
- Coldstone battery now cools down surrounding area to ~~0C~~ -3C (was -5C)
- Increased cooling speed of coldstone battery to compensate
- Tweaked salted meat recipe to better match new mechanic
Preserving food this way creates some additional micromanage - choosing what part of food to preserve and what part to cook right away. Drying stuff is when you …

Food Preservation

---

Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/Expanded Traits.xml

Было два "Мясника" (второй с тем же названием - Butcher). Подобрал более-менее подходящий аналог.

Fix Reaver trait rus translation

---

Mods/Core_SK/Languages/Russian/DefInjected/TraitDef/RCT_Traits.xml

В Core есть одноименные черты характера. Заменил имя на синонимы для возможности отличать эти черты друг от друга.

Fix Constitution trait rus translation

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Rugs.xml

it was being built almost instantly

increase build time of patchwork rug

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Terraforming.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Terraforming.xml

At the moment there are the following problems with new terraforming system:
1 cost/drop amount – with significant terrain terraforming, just a huge amount of resources drops out, which can easily be tenfold higher than the total amount of all other resources. Most of the resources, in particular dirt, drop out simply in incredible quantities, being at the same time a completely useless resource (since it is not used anywhere else);
2 useless composting – cus fertilizers now can drop from some terrain and can be farming by marsh->marshy terrain->marsh cycle;
3 not too much, but the terraforming work amount is a bit overstated in my opinion.
I suggest making the following changes:
- reduce amount of sand and rubble (cost/drop);
- significantly reduce amount of dirt (cost/drop);
- slightly …

Fix terraforming very high resource amount (cost/drop) + fix terraforming rus translation

---

Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_LeatherAndWool.xml

Added by this commit https://github.com/skyarkhangel/Hardcore-SK/commit/e6ca2365638ceb515751d00c64a30224aeb9d61e
but...

Delete duplicate thing categories

---

Mods/NPS_SK/Languages/Russian/DefInjected/TerrainDef/Terrains.xml

Its time to translate it in Russian.

RUS translate for basalt floors

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
Mods/Minerals/Languages/Russian/DefInjected/ThingDef/Item_Resource_Chunks.xml

Материалы объектов из глины и базальта (из мода NPS) теперь переводится на русский язык.
Бафы и дебафы настроения в зависимости от красоты окружения теперь переводятся на русский язык (xml-тэги перевода не соответствовали английским названиям настроений из Core_SK\Defs\ThoughtDefs\RCT_Thoughts.xml).

Fix RUS translate for moods and materials

---

Mods/Minerals/Languages/Russian/DefInjected/ThingDef/Item_Resource_Chunks.xml

Translated description of basalt stone chunk in Russian

Another little basalt RUS translate fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Terraforming.xml

Fix SoilF-Sand description red error

---

Mods/Androids/Defs/ScenarioDefs/Scenarios_Androids.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_CookingSupplies.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Medical.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Mushrooms.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Vegetables.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Meals_SK.xml

Small fixes to translation; rearranges of defs; fixed dublicating stargates, cairns and totems in starts from Androids mod; fixed stargate texture to not be affected by material; commented out old mushroom food

Minor tweaks and cleanups

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

This temperature range will work better since it was supposed to be around normal indoor colony temperature

Slight buff to cheesemaking

---

Mods/CombatExtended/Languages/Russian/DefInjected/ThingDefs/Projectiles_Fragments.xml

Добавлены пропущенные переводы осколков CE

Added missed fragments rus translation

---

Mods/Core_SK/Patches/FilthRainWashes_Patch.xml

Now works 100% of the time and even smells like it used to back in the days

Added back filth patch

---

Mods/Core_SK/Languages/Russian/DefInjected/ThoughtDef/RCT_Thoughts.xml

Fix the Russian translation
Фикс перевода статуса пешки "Hot"

Fix  Ru translation

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Joy.xml

Corrects a terrible injustice in medieval entertainment

Replace industrial to medieval compnents for HorseshoesPin

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Stuff_Leather.xml

I think it's weird that dragon skin and scales have flammability param like other skin types. It's strange that it burns at all :D
Мне одному кажется странным, что чешуя дракона горит также, как и остальные типы кожи? Почему она вообще горит? :D

Fix red dragon skin flammability

---

Mods/Core_SK/Defs/ThingDefs/Events_Meteors.xml

Disables screen shake for meteor boulders (and for huge one) when mined

Disables screen shake while mining (part 3)

---

Mods/RatkinRaceHSK/Languages/Russian/DefInjected/BodyDef/Bodies_Ratkin.xml

RUS translation for Ratkin body parts

---

Mods/Minerals/Defs/Storyteller/Incidents_Map_Misc.xml
Mods/Minerals/Languages/Russian/DefInjected/GameConditionDef/Incidents_Map_Misc.xml

Fix "Empty letter text" error when Blue Snow event happened (issue #2428 )

Fixes Blue Snow event error

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorWood.xml

fix redwood floor description
Фикс описания паркета из красного дерева.

 fix redwood floor description

---

Mods/MineralsFrozen/Defs/ResearchProjectDefs/ResearchProjects_Tech.xml

Was: Neolithic -> Medieval -> Spacer;
Now: Neolithic -> Medieval -> Industrial -> Spacer;

Moved frozen construction VI to industrial tech level

---

Mods/Core_SK/Royalty/Patches/QuestScriptDefs/QuestScriptDefsPatches.xml

Corrected costs, rewards and threat points of Hospitality Quests (~2.5 fold lesser).
Скорректировал поинты заданий на прием гостей (стало примерно в 2.5 раза меньше).

Corrected costs, rewards and threat points of Quests pt.2 - Hospitality Quests

---

Mods/CSL/Defs/DesignationSubCategoryDefs/SubCategories_Classroom.xml
Mods/CSL/Languages/Russian/DefInjected/ArchitectSense.DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Medicals.xml

[bugreport on discord](https://discord.com/channels/272340793174392832/283226662970195969/776133194553884763)

fixed description, added translation

---

Mods/Dubs-Bad-Hygiene/Languages/Russian/DefInjected/RecipeDef/HCSK_Recipe_BiosolidsToAsh.xml
Mods/Dubs-Bad-Hygiene/Languages/Russian/DefInjected/ThingDef/Items_Resource_Stuff.xml

В игре с включенным Dubs-Bad-Hygiene существует два вида удобрений и два компостера.
Данное обновление призвано устранить путаницу между ними в русском переводе.

second attempt to correct the biosolids confusion (dubs hygiene)

---

Mods/Core_SK/Languages/English/Keyed/Main.xml
Mods/Core_SK/Languages/Russian/Keyed/Main.xml

[bugreport on discord](https://discord.com/channels/272340793174392832/283226662970195969/777541539584540692)
Still needs changes to translate resource name. I guess error in core_sk.dll SK.Events.IncidentWorker_HiddenResources.

fix HiddenResources letter label

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml

---------
Добавил всем фруктам небольшой шанс отравления

added a small poison chance to all fruits

---

Mods/Minerals/Patches/02_NaturesPrettySweet/NaturesPrettySweet.xml
Mods/NPS_SK/Defs/ThingDefs/ThingDefs_Resources.xml

fix for basalt fix

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Добавил месту разделки пропущенный параметр на эффективность разделки (в ваниле он есть, у нас почему-то нет).

Added missed work efficiency factor to butchering spot

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Natural.xml

Поправил цвет залежей англезита. Выглядели как залежи железной руды.

Fix anglesite deposits color. Its look like iron deposits

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Special.xml

Part 2 should be in core_sk.dll, class ApparelWithMiningLight, disablelight = true fix.
Your turn, :sky:

Return light to mining helmet part 1

---

Mods/HMC weapon pack – USSR/Defs/ThingDefs_Weapons/Weapons_Heavy.xml

Исправил скорострельность РПК-74М (720 -> 600 в/мин).

Fix RPK-74M rate of fire (720 -> 600 rpm).

---

Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml

Added Strong Metallic stuff categories to pickaxe.
Кирке добавлена категория Strong Metallic (для возможности создания её из, например, обедненного урана).

Added Strong Metallic stuff categories to pickaxe

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Advanced/6x24mmCharged.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Gloves.xml

1 Fixed combat gloves apparel base. It could be industrial (like combat boots from combat set, not spacer).
2 Some 6x24 mm param and cost tweaks and fixes (light nerf).
1 Поправлена базу боевых перчаток. Должны быть индустриальными (подобно боевым сапогам из их же сета).
2 Легкий нерф 6х24 мм боеприпасов (также уменьшил их рыночную стоимость).

Some tweaks and fixes

---

Mods/Core_SK/Languages/Russian/DefInjected/WeatherDef/Weathers_SK.xml

Поправлен перевод описания некоторых погодных явлений.

Fix weather rus translations

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/AsariRace/Defs/ThingDefs_Races/Races_Asari.xml
Mods/CombatExtended/Patches/Core/HediffDefs/Hediffs_Local_Injuries.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/RatkinRaceHSK/Patches/ThingDefs_Races/Race_Rakinlike.xml

1 some fists dps and penetration value correction;
2 added pain per severity patch to scratch and bruise dmg type.
1 немного скорректировал дпс и пробитие у кулаков/зубов/головы/и т.д.;
2 добавил патч на увеличение множителя боя с типов урона "ушиб" и "царапина" (по аналогии с другими типами урона, ранее использовались ванильные значения).

Some pain param and fist dps tweaks and fixes

---

Mods/RatkinRaceHSK/Defs/AlienRaceSettings/AlienRaceSettings.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

1 Alien race fix (nonexistent faction "Ratkin Caravan");
2 Slightly increased cold insulation to keep traders and raiders from freezing. Also some craft tweaks.
1 правка alien race (ссылка на несуществующую фракцию "Ratkin Caravan");
2 немного улучшил холодоизоляцию у некоторой одежды, чтобы рейдеры и торговцы не замерзали + раздал им все шарфики + несколько правок рецептов крафта одежды.

Some ratkin tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture_Beds.xml
Mods/Rimatomics_SK/Defs/ThingDefs_Misc/RadSuits.xml

1 Corrected Royal Bed rest, surgery and immunity gain param. Its should be like millenium bed (cuz require same research and almost same cost list).
2 Correcting rimatomic rad masks cost list and layers. Added industrial tech level.
1 Скорректированы параметры роскошной кровати (должны быть на уровне современной, т.к. открываются одним исследованием и имеют схожие требования для постройки).
2 Скорректированы радиационные маски риматомика (рецепт + укрываемые слои). Добавлен индустриальный технологический уровень маскам и костюмам.

Some small tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_DecorativeTree.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Defences.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Buildings/MechClusterBuildingCostPatch.xml

Changed oil barrel to polymer in shallow moad def
Adapted royalty resourses after destroying buildings to SK - mechanoid metals like uranium, ferrotitanium and carbon, some advanced components and electronics

Added 100% light on new year tree, for growing in room (only 1x1) (Neya asked about this)

---

Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Caffeine.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Drinks.xml

Fix coffee addiction

---

Mods/NPS_SK/Defs/ActiveTerrain.SpecialTerrain/ActiveTerrains.xml

Make lava lukewarm to avoid burns due to bad pathfinder and general engine unsuitability

---

Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_Medical.xml

I have medicine bandage kit in my home and it have only 25 g mass...

Fix bandages bulk and mass params

---

Mods/Core_SK/Languages/Russian/DefInjected/TerrainDef/Terrain_SK.xml
Mods/NPS_SK/Languages/Russian/DefInjected/TerrainDef/Terrains.xml

Too much "Лед"`s for icy stuff

Fixed RUS translate for ice surfaces to make difference between them

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml

https://github.com/skyarkhangel/Hardcore-SK/commit/8f85bea5f772d6e6773bc2502ea3e7a211aab2e5

Reverse pntr changes

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Archipelago.xml
Mods/Core_SK/Defs/BiomeDefs/Biomes_Warm.xml

Добавлена высокая трава в биомы тропических болот (в обычных тропиках и болотах высокая трава есть). Без неё негде брать сено для стартовых кроватей.

Added tall grass to tropical swamp biomes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Production.xml

1 decreased idle heating from some electrical benches, but increased heating in working;
2 corrected electrical oven power consumption (very low value);
3 corrected rus translation of some wooden crafts.
1 уменьшено/увеличено тепловыделение у некоторых электрических верстаков в простое/в работе;
2 скорректировано электропотребление у электрической духовки (было очень низкое значение, немного поднял);
3 скорректированы переводы крафта досок и дров на электрической дерево-пилилке (неверные значения).

Some electrical benches tweaks and fixes

---

Mods/Core_SK/Defs/ThoughtDefs/Vanilla/Thoughts_Memory_Misc_VanillaRework.xml

What an ugly action, make it stop! Madness!

More mood penalty for butchering human corpses.

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml

Changed pemmican recipe to a realistic one and removed poison chance from it. Also disallowed human meat on drying rack.
--------------------
Изменил рецепт пеммикана на гораздо более реалистичный (сухофрукты + вяленное мясо) и убрал базовый шанс отравления. Также на сушилке для мяса больше нельзя сушить плоть гуманоидов

Pemmican change

---

Mods/Core_SK/Defs/FactionDefs/Factions_Norbal.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Security.xml
Mods/Core_SK/Royalty/Defs/FactionDefs/Factions_Kingdom.xml

1 added siege strategy to medieval factions (catapults + ballista);
2 corrected turrets spawn (sieges) (works fine with arcane technology).
1 добавил возможность осаждать колонию средневековым фракциям (катапульты + баллисты);
2 скорректирован спавн туррелей (осада) (добавил более высокий тех. уровень, arcane technology не мешает их использовать).

Some sieges tweaks and fixes

---

Mods/CombatExtended/Patches/Core/HediffDefs/Hediffs_Local_Injuries.xml

Ещё одна небольшая корректировка боли от ранений и ушибов.

Another light pain per severety factor corrections

---

Mods/Core_SK/Defs/ThoughtDefs/Extratraits/Thoughts_Situation_General.xml
Mods/Core_SK/Defs/ThoughtDefs/RCT_Thoughts.xml
Mods/Core_SK/Defs/ThoughtDefs/Thoughts_Situation_Enlighten_SK.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThoughtDef/RCT_Thoughts.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThoughtDef/Thoughts_Situation_General.xml

NightOwl, Undergrounder and Photophobe will not receive debuffs from dark environment.
Photophobe in light will receive debuff from light.
Some minor RUS translation fixes.

Fixed some dark/light thoughts behaviour

---

Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Weapons_Melee.xml

This will make sure your dried fruits and meat will not be eaten immediately, but after simple meals

Lower dried stuff preferability 

---

Mods/Infused_SK/Languages/Russian/DefInjected/ThingDefs/Items_Artifacts.xml

Добавил перевод предмету "infusion amplifier"

Added infusion amplifier rus translation

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Mask.xml

Early game medical equipment should be more accessible, this will help.

Added stuff categories to plague doctor mask

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Canned.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Extracted.xml

Having salt as a main food source is bad

Nerfed salt as a food source

---

Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Weapons_Melee.xml

Reverse shiv translation, breaks "knife" translation

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml

Changed fermenters with Multiple mode to have 100% efficiency to avoid infinite unload bug (lowered output respectively)
Rolled back cheese basin to default fermenter behavior, suits it a lot better

Changes and fixes to "fermenters"

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

again, should have been in the first PR

Changes to fermenters

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops.xml

hopefully make kibble less preferrable for humans

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Legs.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Medieval.xml

which are similar to ones that already have hi-tech textiles available

add hi-tech textiles to clothing items 

---

Mods/RatkinRaceHSK/Patches/Bodies/Bodies_Ratkin.xml

It's should make compatible ratkin with any armored skin implants.
Добавлено броневое покрытие для частей тела Раткинов (исправляет ошибку с неработающими имплантами, повышающими уровень естественной брони пешки).

Added armor coverage to ratkin body

---

Mods/Core_SK/Royalty/Defs/PawnKindDefs/PawnKinds_Kingdom.xml

Also slightly improved apparel quaility of Kingdom King pawn.
Исправил появление одной пешки фракции Kingdom с двуручным оружием и щитом. Также немного увеличил качество брони у фракционного лидера данной фракции (король как-никак).

Fixed 2Handed melee weapon + shield combination with Kingdom Brigand pawn

---

Mods/Core_SK/Royalty/Defs/FactionDefs/Factions_Kingdom.xml
Mods/Core_SK/Royalty/Patches/FactionDefs/FactionPatch.xml

1 added 25 day delay to Kingdom faction raids;
1 added 150 day delay to Empire faction raids.
1 добавлена задержка в 25 дней для рейдов фракции Kingdom;
2 добавлена задержка в 150 дней для рейдов фракции Империя.

Some faction tweaks and fixes

---

Mods/Core_SK/Defs/Drugs/ActivatedCarbon.xml

Because of those dudes who don`t use Hygiene mod

Activated Carbon side effect hot fix.

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Industrial.xml

Will help to avoid thoughts that batteries can only be made out of nickel 
-----------------------------
Переместил свинец выше в списке сплавов, теперь будет меньше недоразумений типа "а почему батареи делаются только из никеля"

Moved lead alloy higher in the list

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Matter.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Matter.xml

Increases input/output item and work amounts for matter conversion recipes 10 times
x10 рецепты для конвертера материи, но я обновил старые и разобрался в ветках

Bulk recipes for Matter Converter

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml

Damn i forgot to did it after some tests

Delete CompFueled for silage pile

---

Mods/HMC Viles Pre-Industrial/Defs/Recipes/Recipes_Components.xml
Mods/HMC Viles Pre-Industrial/Defs/ThingDefs_Weapons/VileBlackPowder/VileTurretBuildings.xml

Cannon component ingredient - typo fixed which broke recipe.

Fixed cannon part ingredient, removed duplicate node

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_UniversalFermenter.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/SeedsPlease/Defs/ThingDefs/Items_Seeds_Base.xml

удалил питательность у семян, удалил категорию семян в крафте топлива, удалил неиспользуемый qualityDays у алкоголя (у него нет компа с качеством, так что смысл в нем отсутствовал, только людей путал)

deleting nutrition from seeds, aslo deleting unused alcohol quality on fermenting barrel

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_UniversalFermenter.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipies_Fermenter.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Buildings_Production.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Items_Meals_SK.xml

- Перевод на русский новых ферментеров
- Снизил объём рецепта на силос с 300 до 150 (пешки больно много бегают за рецептом и не очень удобно планировать запасы)
- Перенёс селитряницу и силосную кучу в группу "переработка" во вкладку "производство" (им там самое место)
--------------
- Rus translation
- Lowered silage recipe bulk from 300 units to 150
- Moved saltpeter pit and silage pile to "conversion" group in "prodcution" tab to keep things tidy

Fermenter polishing

---

Mods/Rimatomics_SK/Defs/ThingDefs_Buildings/Buildings_E_Weapons.xml

clean up Rim Atomic weapons file to be easier to tell buildings apart
fix default damage error

Fix and Cleanup

---

Mods/Animal Food Restrictions/Patches/AnimalTab_Patch.xml

adds diet column to animals tab

Animal Food Restrictions tab patch

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Art.xml

Increasing workToMake and decreace Beauty of Cat sculpture

---

Mods/CombatExtended/Patches/Core/DamageDefs/Damages_LocalInjury.xml

Исправлено дефолтное значение параметров взрывного урона.

Fixed default Bomb param

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
Mods/Core_SK/Defs/ThoughtDefs/Vanilla/Thoughts_Memory_Misc_VanillaRework.xml

Fixed RU translation of butchering thoughts
Fixed bug when butchering of humanlike does not affect pawn relations

Butchering fixes

---

Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Weapons/VileBlackPowder/Vile_Turrets_Heavy.xml

removed depreciated tag

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml
Mods/Androids/Defs/AlienRaceSettings/AlienRaceSettings.xml
Mods/Androids/Defs/PawnkindDefs/PawnKinds_PlayerSK.xml

1 added small chance spawn android's pawn to classic scenario;
2 added some missed new 1.1-1.2 and royalty surgery recipes to androids.
1 добавлен маленький шанс появления пешки-андроида в классическом сценарии;
2 добавлены некоторые пропущенные новые рецепты хирургии из 1.1-1.2 и роялти для андроидов.

Some androids tweaks and fixes

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Insectoid.xml

Corrected antises param after adding jump ability.
Скорректированы параметры антисов после добавления им способности прыжка.

Corrected antises param after adding jump ability

---

Mods/Androids/Languages/Russian/DefInjected/AlienRace.BackstoryDef/Backstories_Adult.xml
Mods/Androids/Languages/Russian/DefInjected/AlienRace.BackstoryDef/Backstories_Childhood.xml
Mods/Androids/Languages/Russian/DefInjected/AlienRace.ThingDef_AlienRace/AlienRace_Droids.xml
Mods/Androids/Languages/Russian/DefInjected/Androids.AndroidUpgradeDef/Upgrades_Archotech.xml
Mods/Androids/Languages/Russian/DefInjected/Androids.AndroidUpgradeDef/Upgrades_Physique.xml
Mods/Androids/Languages/Russian/DefInjected/Androids.AndroidUpgradeDef/Upgrades_Proficency.xml
Mods/Androids/Languages/Russian/DefInjected/Androids.AndroidUpgradeDef/Upgrades_Skin.xml
Mods/Androids/Languages/Russian/DefInjected/Androids.AndroidUpgradeDef/Upgrades_Utility.xml
Mods/Androids/Languages/Russian/DefInjected/RecipeDef/Recipes_Add_Make.xml
Mods/Androids/Languages/Russian/DefInjected/ResearchProjectDef/Research_Androids.xml
Mods/Androids/Languages/Russian/Keyed/Androids.xml

Андройды умерли, да здравствуют Андроиды

Few small translation fixes

---

Mods/NPS_SK/Defs/ThingDefs_Races/Races_Animals.xml

Исправлено бронепробитие животных из мода NPS_SK (сильно заниженные значения).

Fixed NPS's animals armor penetration params

---

Mods/Rimatomics_SK/Defs/ThingDefs_Buildings/Buildings_E_Weapons.xml

fix wrong constructionSkillPrerequisite at Rimatomics "Active Denial System"

fix wrong constructionSkillPrerequisite

---

Mods/Core_SK/Defs/FactionDefs/Factions_Pirate.xml
Mods/Core_SK/Defs/PawnKindDefs_Humanlikes/PawnKinds_Pirate.xml
Mods/Core_SK/Languages/Russian/DefInjected/PawnKindDef/PawnKinds_Pirate.xml

Добавлена новая ранняя рейдерская пешка пиратов с самым простым пистолетом для разбавления их стартовых, почему-то чисто милишных рейдов.

Added early pirate pawn with tier one pistol

---

ModsConfig.xml

Мод CSL (Children, school and learning) выключен по умолчанию.

Disabled CSL (Children, school and learning) by default

---

Mods/RocketMan2/About/About.xml

to avoid misunderstandings

---

Mods/Dubs-Bad-Hygiene/Languages/Russian/DefInjected/TraitDef/Traits_Spectrum.xml

Добавлен пропущенный русский перевод черт характера из мода Dubs Bad Hygiene.

Added missed Dubs Bad Hygiene's traits rus translation

---

Mods/Core_SK/Languages/Russian/DefInjected/ThingCategoryDef/Categories_SK.xml

Вместо категории "Корень" в складах теперь будет "Все категории".

Added correct "Root" category rus translation

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Arid.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Bears.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_BigCats.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Birds.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Bugs.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_CatGroup.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_ChickenGroup.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Cold.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_DogGroup.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Exotic.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Farm.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Foxes.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Giants.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Hares.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Horse.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Hyena.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Insects.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Martens.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Meerkat.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Ptarmigan.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Rodentlike.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_SmilodonPop.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Temperate.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Tropical.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_WildCanines.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Wolfs.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Insectoid.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Stuff_Leather.xml

1 updated all animal params to 1.3 to correctly ranching compatibility;
2 fixed some animals very low CE armor penetration;
3 changed texture of Feenix skin to scales;
4 slightly health increased of all vanilla insectoids and antises.
1 все параметры животных были обновлены до 1.3 для корректной поддержки животноводства;
2 исправлено сильно заниженное бронепробитие у некоторых животных;
3 текстура драконьей чешуи была скорректирована (теперь выглядит как чешуя, а не кожа);
4 немного увеличено здоровье всех ванильных инсектоидов и антисов.

Animals update to 1.3

---

Mods/Core_SK/Defs/FactionDefs/Factions_Syndicate.xml

Синдикат проповедовали трансгуманизм и биоконсерватизм одновременно. Исправлено.

Syndicate had opposite memes at the same time. Fixed

---

Mods/Core_SK/Defs/Storyteller/Incidents_Map_Threats.xml

Уменьшена вероятность создания события на агрессивных животных (слишком завышенное значение)

Decreased manhunter pack chance spawn (too high chance and value)

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/Core_SK/Patches/TraitDefs_Core_Patch.xml
Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml

Added night vision efficiency to some races (human, dova, orassan, ratkin) and trait (night owl).
Некоторым расам (человек, дова, орассан, раткин) и черте характера "Сова" добавлены небольшие бонусы к эффективности ночного зрения.

Added night vision efficiency to some races and trait

---

Mods/A Dog Said... Animal Prosthetics/Defs/HediffDefs/HediffDefs_AnimalBodyParts.xml

hediff descriptions for a dog said

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Lighting_LED.xml

Well, a weak led light bulb cannot explode like a grenade... cannot right?
Ну, не может маломощный светодиод взрываться как граната... не может же ведь, правда?

Fixed LED rope light earthqake interaction

---

Mods/Core_SK/Ideology/Patches/ThingDefs_Buildings/Buildings_Exotic.xml
Mods/Core_SK/Ideology/Patches/ThingDefs_Buildings/Buildings_Ideo.xml
Mods/Core_SK/Ideology/Patches/ThingDefs_Buildings/Buildings_Misc.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Buildings/Patches2.xml

Some Royalty and Ideology temporary buildings patches (just for better HSK compatibility)
Небольшие временные патчи новых построек Роялти и Идеологии (просто для лучшей совместимости с ХСК)

Some Royalty and Ideology temporary buildings patches

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_AJO.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Joy.xml

Исправлены параметры и стоимость столов для развлечения (стол неолита давал больше развлечения, чем средневековые столы)

Fixed joy table params and costs

---

Mods/Core_SK/Defs/DamageDefs/Damages_LocalInjury_SK.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Stun_SK.xml

Исправлено неработающее бронепробитие шокеров (они игнорировали любую броню)

Fixed shoker's unworking armor piercing properties (always ignored armor rating)

---

Mods/Core_SK/Defs/ThingDefs/CaveFlora.xml
Mods/Core_SK/Defs/ThingDefs/Events.xml
Mods/Core_SK/Defs/ThingDefs/Events_Meteors.xml
Mods/Core_SK/Defs/ThingDefs/Events_Skyfaller.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Exotic.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml

Вторая попытка исправить поведение прорывных рейдеров

Another fix breaching raids (part 2)

---

Mods/HMC Vile's Pre-Industrial/About/About.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel_00M_Smithy_Helmets.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel_01M_Headwear.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel_04M_Smithy_Shell.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel_09M_Pants.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel_11M_Outerwear.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Neolithic/Apparel_00Neo_Headwear.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Neolithic/Apparel_02Neo_Body.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Weapons/Vile_Turrets_Heavy.xml

Raised cannon prices, removed neolithic tag from barbute, fixed some mysterious red errors related to how 1.3 handles colorGenerator.

Raised cannon prices, removed neolithic tag from barbute, other fixes

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Hive.xml

Исправлена ошибка, из-за которой ульи инсектоидов не получали урон от снарядов (пуль, стрел и т.д.)

Fixed hives projectile invulnerability

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Arrows.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Alloys.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Components.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Cremation.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Extracts.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Misc_Mending.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Ocean.xml
Mods/Core_SK/Defs/RecipeDefs/Recipes_Production.xml
Mods/Core_SK/Defs/ResearchProjectDefs/Research_Craft.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Accessories.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_UpperHead_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Sheets_Industrial.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_SlaveOutfit.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Special.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Lighting_LED.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Rugs.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Storage_Fridge.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_CampingStuff.xml
Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Medieval.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_RangedNeolithic.xml
Mods/Core_SK/Ideology/Patches/ResearchPrerequisites.xml
Mods/Core_SK/Ideology/Patches/ThingDefs_Buildings/Buildings_Ideo.xml
Mods/Core_SK/Languages/Russian/DefInjected/ResearchProjectDef/Research_Craft.xml
Mods/Core_SK/Patches/ResearchTree/DubsBadHygiene.xml
Mods/Dubs-Bad-Hygiene/Defs/ThingDefs_Buildings/Buildings5_Floors.xml
Mods/Dubs-Bad-Hygiene/Defs/ThingDefs_Buildings/BuildingsB_Hygiene.xml
Mods/Minerals/Defs/ThingDefs_Rocks/Basalt.xml
Mods/Rimefeller_SK/Defs/TerrainDefs/Terrain_Floors.xml

Correcting prerequisites for removing multiple links.
Additional ResearchProjectDef, for recipes that are available from the start.

ResearchTree update

---

Mods/Core_SK/Defs/HediffDefs/Meal/Hediffs_Caffeine.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Drinks.xml

_Caffeine isn't a hard drug lmao_
- Coffee has a safe dose now. 2 cups per day
- Addiction chance decreased to match smokeleaf and alcohol
- Decreased rest in exchange for longer buff duration to make caffeine distinct from psychite drugs
Tea works like half a cup of coffee. It should probably have its own effect but oh well

Caffeine tweaks

---

ModsConfig.xml

Add smoke mod to default modsconfig

---

Mods/Core_SK/Defs/ThingCategoryDefs/ThingCategories_SK.xml
Mods/Core_SK/Defs/ThingDefs_Meals/Items_Meals_ Canned.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingCategoryDef/Categories_SK.xml

Фикс пеммикана в караванах + новая категория "консервы" для долго хранящихся продуктов

Fixed pemmican + added a new category "preserves" for long shelf time meals

---

Mods/Faster raids progression/Patches/HSK_Faction_Patch.xml

Исправлен патч для фракции "Хищники" (мод Faster raids progression)

Fixed Predators faction max pawn cost patch (Faster raids progression mod)

---

.github/FUNDING.yml
README.md

Adds `FUNDING.yml` linking to https://www.patreon.com/skyarkhangel & cleans up readme

Updates readme and adds funding button

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Misc_SK.xml

Very strange why so simple tables can't be moved.
So, this PR make primitive and simple research tables minimizable and less demanding to terrain.

Research tables minimization

---

Mods/CyberneticOrganism_SK/Patches/BodyPartsPatchesSK.xml
ModsConfig.xml

Fixed inability to install prosthetics from Cybernetic organism mod
Disabled christmasnoids mod by default
Исправлена невозможность установки протезов из мода Cybernetic organism
Мод Christmasnoids выключен по умолчанию

Fixed inability to install prosthetics from Cybernetic organism mod

---

Mods/Minerals/Defs/RecipeDefs/Recipes_Production.xml

Возвращен рецепт извлечения мягкой глины из версии 1.2

Added missed extract soft clay recipe from 1.2

---

Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Furniture.xml

Не логично что каменное кресло требует обычных компонентов, изменил рецепт на примитивные компоненты

Изменение рецепта каменного кресла

---

Mods/Core_SK/Languages/Russian/Keyed/Main.xml

Исправлена очепятка в статусе "корневище было уничтожено" грибов

Fixed rus translation when cluster root was removed

---

Mods/Core_SK/Patches/Bodies/Bodies_Humanlike/Human.xml

Добавлен патч, корректирующий шанс на перманентное повреждение мозга андроидов (по аналогии с прочими расами)

Added permanent brain injury patch to android

---

Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_Weapons_Futuristic_Charged.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee.xml
Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Hightech.xml

Increased build cost of Powered Shortsword and Wraith Blade, also moved recipe from electric assembly bench to futuristic weapon bench

Powered melee cost increase

---

Mods/CombatExtended/Languages/Russian/DefInjected/RecipeDefs/Recipes_AmmoNeolithic.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Arrows.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Ballista.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Bolts.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Neolithic/Darts.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Ammo_SK.xml

1 arrows, bolts, darts can be crafting from any wood log type now, not only from simple wood log;
2 added explosive ballista bolts.
1 добавлена возможность создавать стрелы, болты и дротики из древесины любого типа, а не только из обычной;
2 добавлены взрывные болты для баллисты.

Some low tech ammo tweaks and fixes

---

Mods/Faster raids progression/Patches/NyaronHSK_Faction_Patch.xml
Mods/Faster raids progression/Patches/RatkinRaceHSK_Faction_Patch.xml
Mods/Faster raids progression/Patches/Skynet_SK_Faction_Patch.xml

Added patches to Skynet and New Ratkin Plus mod incidents.
Добавлены патчи для событий модов Skynet и New Ratkin Plus.

Faster raids progression. Some fixes and new patches

---

Mods/Core_SK/Defs/ThingDefs_Weapons/Weapons_Melee_Hightech.xml

WeaponSpacerBase already have same recipeUsers

Remove duplicates of recipe user param (fixed recipe user red error)

---

Mods/Core_SK/Patches/ExpectationDef_Patch.xml

Немного сглажена зависимость ожиданий поселенцев от стоимости колонии

Slightly smoothed Expectation-Wealth curve

---

Mods/DismissTrader/Languages/ChineseSimplified/DefInjected/JobDef/DismissalJob.xml
Mods/DismissTrader/Languages/ChineseSimplified/Keyed/TraderDismissal.xml

The current version of Chinese is garbled, fixed the Chinese translation

The current version of Chinese is garbled, fixed the Chinese translation

---

Mods/DismissTrader/Languages/ChineseSimplified/DefInjected/JobDef/DismissalJob.xml
Mods/DismissTrader/Languages/ChineseSimplified/Keyed/TraderDismissal.xml
Mods/Industrial Rollers/Languages/ChineseSimplified/DefInjected/ThingDef/Building_Power_MovingFloor.xml
Mods/Industrial Rollers/Languages/ChineseSimplified/Keyed/IndustrialRollers.xml

Fix Simplified Chinese translation, translate Traditional Chinese to Simplified Chinese.

Fix Simplified Chinese translation

---

Mods/Core_SK/Defs/BiomeDefs/Biomes_Archipelago.xml
Mods/Core_SK/Defs/BiomeDefs/Biomes_Temperate.xml

Добавлены некоторые пропущенные животные в умеренные биомы

Added some missed animals to temperate biomes

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_AlcoholBarrel.xml

fix moonshine crate shown as patreon crate on recipes

---

Mods/RatkinRaceHSK/Languages/Russian/DefInjected/AlienRace.BackstoryDef/BackstoryDef.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/BodyPartDef/Bodyparts_Ratkin.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/CultureDef/Cultures.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/DamageDef/Buildings_Security.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/DamageDef/Damage_Def.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/DamageDef/RK_EnemyWeapon.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/IncidentDef/Storytellers.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/InteractionDef/InteractionDefs.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/JobDef/jobdef.xml
Mods/RatkinRaceHSK/Languages/Russian/DefInjected/ThoughtDef/ThoughtDefs.xml

Update RatkinRaceHSK rus translation

Update RatkinRaceHSK rus translation

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Exoskeleton.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Orassan.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Synthetic.xml

Fixed https://github.com/skyarkhangel/Hardcore-SK/issues/3386

Fixed issue 3386

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Bionic.xml
Mods/Core_SK/Defs/BodyParts/BodyParts_Cybernetic.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml
Mods/Core_SK/Languages/Russian/DefInjected/HediffDef/Bodyparts/BodyParts_Bionic.xml
Mods/Core_SK/Languages/Russian/DefInjected/HediffDef/Bodyparts/BodyParts_Cybernetic.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_ProstheticsInstall.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Bodyparts/BodyParts_Bionic.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Bodyparts/BodyParts_Cybernetic.xml

Added bionic and cybernetic neck implants. Boosts talking param and neck durability.
Добавлены протезы "бионическая шея" и "кибернетическая шея". Улучшают показатель речи пешек и имеют повышенную прочность.

Added neck implants

---

README.md

We don't have a stable cheat sheet to reference + optional mods make it everoutdated.
Changed Compatible mods link to discord #hsk-compatibility channel.
Changed supported languages to English and Russian. Having *some* things translated is far from supporting a language.

Minor changes to Readme.md

---

Mods/VSE - Winston Waves HSK/1.3/Defs/Rewards/GoodRewards.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/GameConditionDef/IncidentsMisc_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/HediffDef/BodyPart_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/HediffDef/HediffStatIncrease_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/HediffDef/ModifiersHediffs_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/IncidentDef/IncidentsMisc_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/RecipeDef/BodyPart_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/ThingDef/BodyPart_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.ModifierDef/Modifiers_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/ExcellentRewards_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/GoodRewards_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/LegendaryRewards_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/NormalRewards_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/OtherMods_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/PoorRewards_Winston.xml
Mods/VSE - Winston Waves HSK/Languages/Russian/DefInjected/VSEWW.RewardDef/VFEM_Winston.xml

Добавлен недостающий перевод на русский язык для мода VSE - Winston Waves

Update VSE - Winston Waves russian translation

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Medicine.xml

i get that the carbon alloy was probably for the case, but none of the previous medicines account for the material of the case. Also "MedicalDrink" is antibiotics. I feel that needs to stay. Considering its ultra tech medicine and biosynthetic material is spacer, i guess that makes sense.
If anything i would say antibiotics is too cheap, however i dont think that should be changed, as immunity in hsk is tough enough as it is.

Alternative Ultratech Medicine Recipe

---

README.md

Edit of description and various copy for readability. Added "more content" section, moved compatibility link there. Updated Credits.

Updated Readme for review

---

ModsConfig.xml

Enabled christmasnoids mod (master)

---

ModsConfig.xml

Enabled christmasnoids mod (dev)

---

Mods/Androids/Defs/AlienRace/AlienRace_Androids.xml

Androids Skin Color was missing its secondary tag

Android CE Comp + Possible Hair Color Gene Fix

---

Mods/AsariRace/Defs/ThingDefs_Races/Races_Asari.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml

- Corrected Orassan Tail (not invisible anymore)
- Adjusted east offsets for tail.

HAR Offset and BodyAddon Adjustments

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Industrial.xml

It was something that I kept all the way in 1.3, since I am working on 1.4 compatibility, I better merge it into HSK

Tactical Helmet buff and update for 1.4

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Helmets_FullHead_Industrial.xml

ToxicEnvironmentResistance, should generally be from 0-1. Its not normal to be in the negatives, as thats means its actually speeding up any toxic hediffs

Correct ToxicEnvironmentResistance

---

Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml

LifeStages -> 0,3,8,11,16
Growth Moments -> 5,8,11
Learning speed may need adjusting in the future, but until that is figured out, this should help the later stages for growth moments.

Adjusted Ratkin LifeStages and GrowthMoments

---

Mods/Core_SK/Biotech/Patches/PawnKindDefs_Biotech/PawnKinds.xml
Mods/Core_SK/Patches/Hair_under_hats.xml

- And Minor hair under hats patch fix

Added Grenades to pigskin (Its their favourite weapon)

---

Mods/CombatExtended/Patches/Core/HediffDefs/Hediffs_Local_Injuries.xml

Returned old 1.3 painFactor from injuries params (better balanced for HSK armor and penetration weapon params)
Also returned missed HediffDef patches
https://github.com/skyarkhangel/Hardcore-SK/commit/dc1e2e471b6e093ece6d78d36d113d29f435fffc
and
https://github.com/skyarkhangel/Hardcore-SK/commit/08a6fa06c72e3c9b1b832be9185bdecc7f04ecef

Returned old 1.3 painFactor from injuries params (better balanced for HSK armor and penetration weapon params)

---

Mods/AsariRace/Defs/ThingDefs_Races/Races_Asari.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Humanlike.xml

This will make them their correct skin color. In the future better Biotech support will be added.

Disabled Skin Color Genes for Asari, Nova, Dova & Orassan

---

Mods/Core_SK/Biotech/Patches/Scenarios/Scenario.xml
Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Mechanoid.xml

1. Subcore having no stuff causes error when editing the scenario;
2. Added 10 carbon to mechanitor start for a better experience when player cannot scrap it from the map;
3. Allowed pawn to give mechanoids ammo for now. 
4. Introduced PartialArmorExt into hsk

Small fixes

---

Mods/Core_SK/Biotech/Patches/PawnKindDefs_Biotech/PawnKinds.xml

Should reduce the amount of OP grenade spawns.

removed GrenadeDestructive tag from pigskin

---

Mods/Core_SK/Defs/ResearchProjectDefs/Research_Apparel.xml
Mods/Minerals/Defs/Research/Research.xml

Some minor yellow research error fixes.

Research Correction for Apparel + Minerals

---

Mods/Core_SK/Defs/ThingDefs_FishIndustry/Building_FishingPier.xml

- To clarify that the Fish Trap will catch fish slowly over time without fish bait, but will be sped up considerably with fish bait.

Fishing Trap Description Update

---

Mods/Rimatomics_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Production.xml

Добавлен пропущенный перевод рецепта переплавки лопастей турбины

Added missed smelt turbine blades rus translation

---

Mods/RatkinRaceHSK/Defs/ThingDefs_Races/Races_Rakinlike.xml

Fixed misalignment, etc.
Now ratkin should have 3 years each for study without losing their growth point

Ratkin lifestage fix

---

ModsConfig.xml

Turned mod on by default

---

Mods/Core_SK/Defs/ThingDefs_Items/Items_Tools.xml

Material and quality can still turn this around they do still pack a punch in a pinch

Lowered dps of tools. They should no longer be better then weapons in fights 

---

Mods/Mod Indicator/Languages/ChineseSimplified/DefInjected/ModIndicator.ModTypeDef.xml

Mod Indicator zh-cn Translation

---

Mods/Core_SK/Defs/CombatExtended/Ammo/Shell/155mmHowitzer.xml
Mods/Core_SK/Defs/CombatExtended/Ammo/Shell/81mmMortar.xml

Until we find how CompProperties_Charges work

Mortar shell speed fix

---

Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorCarpet.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_FloorMetallic.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_Floors_SK.xml
Mods/Core_SK/Defs/TerrainDefs/Terrain_PrimitiveFloors.xml
Mods/Core_SK/Patches/CleaningTimeFactor.txt

Official Dev fixed it some time, but didn't mention it iirc

Revert CleaningTimeFactor change

---

Mods/Core_SK/Biotech/Patches/Research/Research.xml

Otherwise it cannot be researched on Adv reserachbench

Add AdvancedResearchExtension to ToxGas

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Alloys.xml
Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Alloys_Industrial.xml

added some of Aluminiums properties and adjusted some to fit its descriptions and ingredients more

Proposed FerrosiliconAlloy (Sendust) changes

---

Mods/Core_SK/Languages/Russian/DefInjected/HediffDef/Hediffs_MedicalDrink.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_DragsInstall.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Meals.xml

Эти капсулы работают совершенно не как антибиотики и я беру на свою душу грех переименовать их (теперь уже вместе с рецептами)

Fixed updated translation.

---

Mods/CombatExtended/Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml
Mods/Core_SK/Defs/ThingDefs_FishIndustry/Races_Animal_Fish.xml

https://discord.com/channels/272340793174392832/1208314379175469066

fix (Fish) no fish in swamps

---

Mods/Core_SK/Biotech/Patches/ThingDefs_Apparel/Various.xml

This would make mech armor & helmets more into
HSK, including recipe, workbench for making them,
etc.

Biotech Mech Armor Patch

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Mechanoid.xml
Mods/Skynet_SK/Defs/ThingDefs/Races_Skynet.xml

Added missed armor durability to some mech and skynet pawns
Добавлена пропущенная прочность брони для некоторых механоидов и скайнета.

Added missed armor durability to some mech and skynet pawns

---

Mods/Core_SK/Defs/ExpandedRoofing/RoofThings.xml

Fixed solar roofing glass per cell cost. Looks like someone accidentally added an extra nil :D
Исправлено количество стекла на одну клетку у крыши из солнечной панели. Похоже, кто-то случайно добавил лишний нолик :D

Fixed solar roofing glass per cell cost

---

Mods/Core_SK/Defs/TraitDefs/Expanded Traits.xml

Added some Ideology modifiers to eligible traits (for example, a fanatic will be more likely to try to convert others, etc.).
Добавлены некоторые модификаторы идеологии некоторым подходящим для этого чертам характера (например, фанатик будет чаще пытаться обратить других и т.д.).

Added some Ideology modifiers to eligible traits

---

Mods/Need Bar Overflow/Common/Languages/ChineseSimplified (简体中文)/DefInjected/HediffDef/FoodOverflow.xml
Mods/Need Bar Overflow/Common/Languages/English/DefInjected/HediffDef/FoodOverflow.xml
Mods/Need Bar Overflow/Common/Languages/Russian/DefInjected/HediffDef/FoodOverflow.xml

The translation keys were wrong

Need Bar Overflow Translation Update

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Surgery.xml

CureChronicAlzheimers now cure Alzheimers instead of Dementia

fix (Surgery) CureChronicAlzheimers

---

Mods/CombatExtended/Patches/Dubs Rimatomics/Turrets_Rimatomics.xml
Mods/Core_SK/Biotech/Defs/ThingDefs_Misc/Apparel/Apparel_Child.xml

- Fix xpath invalid exception (XPath doesn't support inline comment)
- Fix duplicate Bulk node for Apparel_KidTribal (CE's patch already adds an identical one)

More Minor Fixes

---

Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Bears.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_Temperate.xml
Mods/Core_SK/Defs/ThingDefs_Races/Races_Animal_WildCanines.xml

Added missed natural armor to some combat animals (bears, boars and wargs).
Добавлена пропущенная естественная броня некоторым боевым животным (медведям, вепрям и варгам).

Added missed armor to some combat animals

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Matter.xml
Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production_Hightech.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Matter.xml

Added Convert to tin ore recept to inorganic matter converter by request below:
https://discord.com/channels/272340793174392832/1237675358405267457
Добавлен рецепт конвертации материи в олово в Конвертер материи по запросу выше.

Added Convert to tin ore recept to inorganic matter converter

---

Mods/Core_SK/Defs/BodyParts/BodyParts_Bones.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Production.xml
Mods/Core_SK/Languages/Russian/DefInjected/ThingDef/Bodyparts/BodyParts_Bones.xml

the translation was redone according to the requirements HSK

fix translation and name

---

Mods/Core_SK/Patches/HediffDefs/Hediffs_Local_Injuries.xml

Lost again as a result of the CE update. I decided to remake them and move them to the Core SK.
https://github.com/skyarkhangel/Hardcore-SK/commit/eeed86f1fa685f7cb8998f6a1377a04727d49bd5
https://github.com/skyarkhangel/Hardcore-SK/commit/a27040905d2a157bb7e9502f671018de2af27783
https://github.com/skyarkhangel/Hardcore-SK/commit/79916d6670e9fc57e2235c87561869f0d9523092
https://github.com/skyarkhangel/Hardcore-SK/commit/897f83cacbe5afc844ecfd8f8cf4f9cbc7b82587

Returned missed local injures and pain patches

---

Mods/Core_SK/Defs/RecipeDefs/Recipes_Production.xml
Mods/Core_SK/Languages/Russian/DefInjected/RecipeDef/Recipes_Production.xml
Mods/Core_SK/Patches/CombatExtended/Ammo/Neolithic/Arrows.xml

Adds a recipe for smelting silicon (x 20). To produce 20 silicon you need 200 sand. Takes more time to smelt 
Change fire arrows to be crafted with sulphur

Add Recipe for mass production of silicon in an electric arc furnace (EAF) / Change fire arrows to be crafted with sulphur

---

Mods/Core_SK/Defs/Drugs/Drugs.xml
Mods/Core_SK/Defs/HediffDefs/HediffDefs_ResistPain.xml
Mods/Core_SK/Patches/HediffDefs/Hediffs_Local_Injuries.xml
Mods/Core_SK/Patches/HediffDefs/Hediffs_Local_Misc.xml

[ENG]
In continuation of the changes at the link below:
https://github.com/skyarkhangel/Hardcore-SK/pull/3889
These changes have lost their relevance - since then, ideology and biotech have been released, adding many new mechanics (including those related to reducing pain received), due to which situations began to arise too often when the mechanics of pain simply do not work.
I propose to make these small (~5-12% on average) pain modifiers changes to partially correct this situation.
The patch also contains an adjustment to the previous aforementioned patch with the addition of a missing "Crush" damage type.
[RUS]
В продолжении изменений по ссылке ниже:
https://github.com/skyarkhangel/Hardcore-SK/pull/3889
Данные изменения утратили актуальность - с тех пор вышли в свет длц идеологии и …

Some pain modifiers tweaks and fixes (#3)

---

Mods/Core_SK/Royalty/Patches/PawnKindDefs_Royalty/PawnKinds.xml
Mods/Core_SK/Royalty/Patches/ThingDefs_Misc/Weapons/Weapons_Melee.xml

Added recipeMaker for MeleeWeaponUltratech ，Enhance market value

Updated Weapon_Melee.xml

---

Mods/Core_SK/Defs/DesignationSubCategoryDefs/SubCategories.xml
Mods/Core_SK/Languages/Russian/DefInjected/ArchitectSense.DesignationSubCategoryDefs/SubCategories.xml

These categories will allow addons to put their content in one place without relying on other addons.

New subcategories for different structures

---

.github/workflows/update_gitattributes.yaml

I don't mind the idea of having pending updates like that, but dev branch should also get this love

Added development to the tracked branches for mod updates

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Special.xml
Mods/Roos Painting Expansion/1.4/Defs/Thing_MiscDefs/Apparel_Various.xml

Also removed pointless buffs unrelated to mining

Mining helmet cost and stat rework

---

Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Terraforming.xml

The tree is fine with eating dessicated corpses, so this should fit thematically

Make rotted meat consumable by the harbinger tree

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/PawnCapacityDef/PawnCapacity.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/PawnRenderTreeDef/PawnRenderTreeDefs.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/PawnsArrivalModeDef/PawnsArrivalModes.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionMode.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RaidStrategyDef/RaidStrategies_Basic.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RaidStrategyDef/RaidStrategies_Breach.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RecipeDef/Hediffs_BodyParts_Bionic.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RecipeDef/Recipes_Production.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_2_Electricity.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_3_Microelectronics.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/ResearchTabDef/ResearchTabs.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RoomStatDef/RoomStats.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/RulePackDef/RulePacks_Book_Descriptions.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Basics_Special.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Building_Special.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Pawns_Combat.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Pawns_General.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/StatDef/Stats_Pawns_WorkGeneral.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/SurgeryOutcomeEffectDef/SurgeryOutcomeEffectDefs.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/TaleDef/Tales_SinglePawn.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/TipSetDef/Tips.xml
Mods/CoreTranslation/Update.txt
Mods/CoreTranslation_Anomaly/Languages/Russian-SK/Keyed/ITabs.xml
Mods/CoreTranslation_Biotech/Languages/Russian-SK/DefInjected/GeneDef/GeneDefs_Spectrum.xml
Mods/CoreTranslation_Biotech/Languages/Russian-SK/Keyed/Misc_Gameplay.xml
Mods/CoreTranslation_Ideology/Languages/Russian-SK/Keyed/Dialogs_Various.xml
Mods/CoreTranslation_Royalty/Languages/Russian-SK/DefInjected/ThingDef/Items_Exotic.xml
Mods/CoreTranslation_Royalty/Languages/Russian-SK/DefInjected/TipSetDef/Tips.xml

More Anomaly/Biotech translations.
Get it while it's hot.

Sync CoreTranslation mods with ludeon/rimworld-ru repo

---

Mods/Core_SK/Patches/Asphalt_Road_Patch.xml

Added patch to allow Broken Asphalt road from vanilla game to be buildable in "Natural Floors" category for those who like it.

Asphalt Road Patch

---

Mods/Core_SK/Defs/ThingDefs_Apparel/Apparel_Shields.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Apparel_06M_Shields.xml
Mods/HMC Vile's Pre-Industrial/Defs/ThingDefs_Apparel/Neolithic/Apparel_02Neo_Body.xml
Mods/RatkinRaceHSK/Defs/ThingsDefs/RK_Apparel.xml

...to make Combat Extended happy.

Update shields to use new render system

---

Mods/Core_SK/Defs/RecipeDefs_Meals/Recipes_Meals_Ingridients.xml

Added recipe of ground coffee to kitchen table

Ground coffee

---

Mods/HSK Autosort and Mod Assistant/Defs/ModListerSettingsDef/ModListerSettingsDefs.xml

https://steamcommunity.com/sharedfiles/filedetails/?id=3450332059

Mark Rim Languages workshop mod as Fully Compatible Mod.

---

Mods/HMC Biomes/Defs/BiomeDefs/Biomes_Temperate.xml

Исправлено отсутствие растений в биоме затопленной бамбуковой рощи

Fixed missing plants in the flooded bamboo grove biome

---

Mods/HMC Biomes/About/About.xml

Обновление порядка модов для корректной совместимости с модом Vile's Biomes From The Ground Up.

Updated mod order to be compatible with Vile's Biomes From The Ground Up mod.

---

.gitattributes
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/HistoryEventDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/HistoryEventDef/Precepts_AlienDating.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/HistoryEventDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/IssueDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/IssueDef/Precepts_AlienDating.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/IssueDef/Precepts_AlienRaces.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/IssueDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/MemeDef/Memes_Misc.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienDating.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienRaces.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/ThingCategoryDef/ThingCategories.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienDating.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienRaces.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/ThoughtDef/Thoughts.xml
Mods/AlienRaces/1.5/Languages/Russian/DefInjected/TraitDef/Traits.xml
Mods/MultiLang Colorful Traits/Defs/Mod_AlienRaces.xml

Added missed russian translation to Humanoid Alien Races mod. Fixed HAR trait (incorrect defName in MultiLang mod).
Добавлена пропущенная русская локализация для мода Humanoid Alien Races.

Added missed russian translation to Humanoid Alien Races mod

---

Mods/Core_SK/Defs/RecipeDefs_Weapons/Recipes_DeconstructPersonalShield.xml

Subj.
Tested.
No side effects detected.

Allows the ingredients filter for the "disassemble the power shield" recipe.

---

Mods/CoreTranslation/Languages/Russian-SK/DefInjected/BackstoryDef/Solid_Child.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/BackstoryDef/Solid_Rare.xml
Mods/CoreTranslation/Languages/Russian-SK/DefInjected/BackstoryDef/Tribal_Adult.xml
Mods/CoreTranslation/Update.txt
Mods/CoreTranslation_Anomaly/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_Misc.xml
Mods/CoreTranslation_Biotech/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_Mechanitor.xml
Mods/CoreTranslation_Biotech/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_Misc.xml
Mods/CoreTranslation_Royalty/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_Apparel.xml
Mods/CoreTranslation_Royalty/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_Implants.xml
Mods/CoreTranslation_Royalty/Languages/Russian-SK/DefInjected/ResearchProjectDef/ResearchProjects_MusicalInstruments.xml

Sync CoreTranslation mods with ludeon/rimworld-ru repo.
* More Research Projects translations;
* Fix CaravanChild53 and CoreworldStudent50 backstories description;
* Rare backstories (easter egg backstories?) are translated.

Update CoreTranslation mods

---

Mods/Skynet_SK/Defs/ThingDefs/Races_Skynet.xml

Fix Surgical Inspection for Skynet

---

Mods/AlienRaces/Languages/Russian/DefInjected/HistoryEventDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/Languages/Russian/DefInjected/HistoryEventDef/Precepts_AlienDating.xml
Mods/AlienRaces/Languages/Russian/DefInjected/HistoryEventDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/Languages/Russian/DefInjected/IssueDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/Languages/Russian/DefInjected/IssueDef/Precepts_AlienDating.xml
Mods/AlienRaces/Languages/Russian/DefInjected/IssueDef/Precepts_AlienRaces.xml
Mods/AlienRaces/Languages/Russian/DefInjected/IssueDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/Languages/Russian/DefInjected/MemeDef/Memes_Misc.xml
Mods/AlienRaces/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienDating.xml
Mods/AlienRaces/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienRaces.xml
Mods/AlienRaces/Languages/Russian/DefInjected/PreceptDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/Languages/Russian/DefInjected/ThingCategoryDef/ThingCategories.xml
Mods/AlienRaces/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienCannibalism.xml
Mods/AlienRaces/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienDating.xml
Mods/AlienRaces/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienRaces.xml
Mods/AlienRaces/Languages/Russian/DefInjected/ThoughtDef/Precepts_AlienSlavery.xml
Mods/AlienRaces/Languages/Russian/DefInjected/ThoughtDef/Thoughts.xml
Mods/AlienRaces/Languages/Russian/DefInjected/TraitDef/Traits.xml
Mods/AlienRaces/Languages/Russian/Keyed/UI.xml

HAR was updated to the latest version. This PR updates a Russian translation.

Update Russian translation for HAR (AlienRaces)
